### ISSUE TITLE
API Issues

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#102]
Two related tickets:

[DDF-429](https://jira.cdisc.org/browse/DDF-429)

Query/path parameter names for some of the API endpoint mentioned in Specs were not in alignment with data model. Details mentioned below.

Please rename path parameter "uuid" to "studyId" for below endpoints (Refer Attachment1).
GET /v2/studyDefinitions/{uuid}
PUT /v2/studyDefinitions/{uuid}
GET /v2/studyDefinitions/{uuid}/history
Please rename query parameter "study_uuid" to "studyId" for below endpoint  (Refer Attachment2).
GET /v2/studyDesigns?study_uuid={study_uuid}

[DDF-458](https://jira.cdisc.org/browse/DDF-458)

It would be better to enforce ID fields to be UUIDs rather than custom user defined string values, so that it supports other database implementation options like Graph DB, etc.

The current model allows duplication of identifiers within a particular study document and across different study documents.

Additionally the uniqueness of IDs for the master data element like address, intervention types etc. is not guaranteed and same master data can be replicated with potentially different identifiers across different studies.

**Comment by cupkes** [comment]
so, originally, the design was support to support UUID identity values for anything that you retrieve from the SDR.  The UUIDs were intended to by generated by the SDR and used for unique internal reference to SDR objects.  The SDR's own disambiguation mechanism.  Externally generated IDs are just strings with no other conformance rules.  Just to make sure we're still all on the same footing here.

**Comment by dih-cdisc** [comment]
I dont think the SDR generates UUIDs for the internal objects, just the top-level study class and its UUID. I am not convinced that the IDs should be UUIDs going in, imposes a little too much on systems posting to the SDR. If SDR wants to add them, great, but model does not demand it. Ids should be consistent/unique within a Study

**Comment by dih-cdisc** [comment]
OK, @jared-schreibman-cdisc lets just make these changes and these changes only

Query/path parameter names for some of the API endpoint mentioned in Specs were not in alignment with data model. Details mentioned below.

Please rename path parameter "uuid" to "studyId" for below endpoints (Refer Attachment1).
- GET /v2/studyDefinitions/{uuid}
- PUT /v2/studyDefinitions/{uuid}
- GET /v2/studyDefinitions/{uuid}/history

Please rename query parameter "study_uuid" to "studyId" for below endpoint (Refer Attachment2).
- GET /v2/studyDesigns?study_uuid={study_uuid}
