### ISSUE TITLE
Activity Instance / Epoch Relationship

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#103]
See JIRA [DDF-447](https://jira.cdisc.org/browse/DDF-447)

Can an epoch exist to represent a fixed timepoint with no associated encounter?

**Comment by dih-cdisc** [comment]
Also add [DDF-446](https://jira.cdisc.org/browse/DDF-446) to this ticket

"EOT and Treatment discontinuation associated with an encounter, are not periods, but specific timepoints. Can these be considered as EPOCH?"

**Comment by dih-cdisc** [comment]
We want to maintain the relationship between ScheduledINstance and Encounter but also relate every instance to an Epoch such that every instance is in an epoch but does not need to be in an encounter

![2023 05 24 DDF Model](https://github.com/cdisc-org/DDF-RA/assets/115090009/573207fe-36c0-49a4-9517-0b96b38d9adb)

**Comment by cupkes** [comment]
In your diagram, you moved the relationship (cut it from encounters to epochs) from encounters to scheduled instance.  You didn't change the name yet, but we should have a reference to a list of study epochs from every scheduled instance?

**Comment by dih-cdisc** [comment]
Cut & paste brain fade from myself there. Attribute should be "epochId"?? I think an instance should be connected to one and only one Epoch. Also it must be connected to an epoch, so 1:1. Thoughts?

**Comment by dih-cdisc** [comment]
Latest Sketch

![2023 05 25 DDF Model III](https://github.com/cdisc-org/DDF-RA/assets/115090009/43950bbf-8864-4987-a0e3-d7ccc226a277)

**Comment by dih-cdisc** [comment]
@cupkes On checking, should "encounterId" be "epochId" since now referencing Epoch class?
