### ISSUE TITLE
Activity/Procedure/BC Conditional [Model]

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#105]
See #231 for original issue

**Comment by dih-cdisc** [comment]
Add second JIRA

See [JIRA DDF-448 ](https://jira.cdisc.org/browse/DDF-448)

"How can conditional logic associated with Acitvities and timepoints related biomedical concepts be represented in the model? 

For e.g., q In the follow-up period, diagnostic CT scans, with or without PET/CT scans, should be obtained until patients develop progressive disease, including patients who proceed to new anti-lymphoma therapy, as follows (+- 14 days): at 3 and 6 months after the end-of-treatment response assessment, then every 6 months until disease progression, or death, or until 2 years from the end-of-treatment response assessment, whichever occurs first. PET/CT scans should be obtained during the study and the follow-up period at any time clinical findings suggest disease progression, and response should be recorded in the eCRF."

**Comment by BSnoeijerCD** [comment]
See ticket #181 for corresponding issues with footnotes

**Comment by dih-cdisc** [comment]
Initial sketch design

![2023 11 20 Conditional](https://github.com/cdisc-org/DDF-RA/assets/115090009/2e2b7dc2-76d3-4b62-a39c-b5388e106a12)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc
Makes sense.
How do you distinguish between context relationship to Activity and to ActivityInstance?

**Comment by BSnoeijerCD** [comment]
Added to UML: 
@dih-cdisc : can you check if you agree with cardinality for appliesTo relationships.
![Biomedical Concepts](https://github.com/cdisc-org/DDF-RA/assets/138679324/70147c62-a5c1-4886-95f3-dfeee7a7752a)

**Comment by dih-cdisc** [comment]
@BSnoeijerCD 

1. appliesTo should be 1..*, there should always be one or more things the condition applies to?
2. Needs to include Procedure class ... Condition--[:appliesTo]--> Procedure

**Comment by BSnoeijerCD** [comment]
@dih-cdisc 
1. Understood. There should be at least one to one of the "to" classes. But might be confusing if I add 1..* to all "to" classes. Let's discuss.
2. Yes. Missed that one. I will add it to the diagram.

**Comment by BSnoeijerCD** [comment]
newest version on UML including procedures class
![Biomedical Concepts](https://github.com/cdisc-org/DDF-RA/assets/138679324/c402add9-96cd-4f14-9275-4da7ce0adefa)

**Comment by BSnoeijerCD** [comment]
> @dih-cdisc
> 
> 1. Understood. There should be at least one to one of the "to" classes. But might be confusing if I add 1..* to all "to" classes. Let's discuss.
> 2. Yes. Missed that one. I will add it to the diagram.

1. As discussed during the scrum meeting today: Needs to be a CORE rule: testing that at least 1 class is referenced using the appliesTo relationship.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc :
During the last SME meeting we discussed that condition could inherit from syntax template to align with open study builder.
Then we can relate a condition to another item stored in the model like population or intervention or based on whether another activity is done or not. 
Are you ok with the following change?
![Activities](https://github.com/cdisc-org/DDF-RA/assets/138679324/9e9dd4b4-dbf0-41cd-bb71-a28257dff668)

**Comment by gerrycampion** [comment]
Where will Conditions go in the API? Currently it does not have a parent.
