### ISSUE TITLE
Arms & Epochs Duplication in API

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#107]
We need to fix the duplication of Arms and Epochs in the API JSON. Because a two cells will point at the same arm we see the Arm definition duplicated in the JSON. Same effect with the epochs.

**Comment by dih-cdisc** [comment]
Add collections for the Arms and Epochs and make the relationships from cells cross references.

![2023 05 25 DDF Model](https://github.com/cdisc-org/DDF-RA/assets/115090009/99647bc7-0d28-4600-9cb7-f13263ebf019)

**Comment by dih-cdisc** [comment]
@cupkes On checking studyArm looks like it has not been updated. Should now be "studyArmId" of type string

**Comment by cupkes** [comment]
You are correct, sir.  Fixed.

**Comment by dih-cdisc** [comment]
@cupkes @jared-schreibman-cdisc we need to do one more little change so as to remove the possibility of duplication of objects in the API. Same issue happens with StudyElement. So new same change as for Epochs and Arms

- new relationship from StudyDesign to StudyElement (studyElements, list of StudyElements)
- Change StudyCell studyElements type from list of StudyElement to list of string
