### ISSUE TITLE
Alignment of Definitions with ISO IDMP

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#108]
Couple of comments from public review re definition alignment with ISO IDMP

[JIRA 412](https://jira.cdisc.org/browse/DDF-412) 

The concepts of Product and Substance administration in the concept map are not precise enough and not aligned to ISO IDMP while covering very similar concepts. It would be important to align there as the ISO IDMP model will be used across regulatory procedures and systems as well as in safety E2BR3 standard.

ISO IDMP is having a modelling for "Investigational Medicinal Products" which include the relationship to their active substance(s) and aslo a modelling for devices.
- Product should be replaced / merged with “Investigational Medicinal Product” from ISO which is defined as "any pharmaceutical product or combination of pharmaceutical products or placebo(s) being tested or used as a reference in a clinical trial, including product already with a marketing authorization but used or assembled (packaged) in a way different from the authorised form, used for an unauthorised indication, or used to gain further information about the authorised form"
  - Investigational Medicinal Product is having a full modelling linking as well devices and active substances which cannot be pasted here unfortunately
- Medical Device (and not "product") should be used for the cases where the device is the main therapeutic mode of (for the cases where the drugs is the main mode of action the “Investigational Medicinal Product” is already encompassing the device dimension as part of the model).
Definition from ISO IDMP : "instrument, apparatus, appliance, software, material (3.1.47) or other article, whether used alone or in combination, including the software intended by its manufacturer (3.1.38) to be used specifically for diagnostic and/or therapeutic purposes and necessary for its proper application, intended by the manufacturer to be used for human beings for the purpose of:
  - diagnosis, prevention, monitoring, treatment or alleviation of disease;  
  - diagnosis, monitoring, treatment, alleviation of or compensation for an injury or handicap;
  - investigation, replacement or modification of the anatomy or of a physiological process;
  - control of conception, and which does not achieve its principal intended action in or on the human body by pharmacological, immunological or metabolic means, but which may be assisted in its function by such means"
- Substance administration should be replaced / merged by “Pharmaceutical product” administration (pharmaceutical product is “what the patient takes” and the dose form for administration so these concepts would match). 
  - Definition of Pharmaceutical Product : pharmaceutical product
qualitative (3.1.70) and quantitative composition (3.1.71) of a Medicinal Product (3.1.50) in the dose form approved for administration 
  - Pharmaceutical Product is having a modelling linking it to the corresponding active substance(s) and Investigational Medicinal Product(s)

[JIRA 413](https://jira.cdisc.org/browse/DDF-413)

Study and Clinical Trial definitions to be harmonized to ISO IDMP :

- Definition of Clinical Trial in ISO IDMP : clinical trial
"investigation in human subjects intended to discover or verify the clinical, pharmacological and/or other pharmacodynamic effects of an investigational product(s), and/or to identify any adverse reactions to an Investigational Medicinal Product(s) (3.1.31), and/or to study absorption, distribution, metabolism and excretion of Investigational Medicinal Product(s) with the object of ascertaining its safety and/or efficacy"
Note 1 to entry: The terms clinical trial and clinical study are synonymous

**Comment by dih-cdisc** [comment]
Defer to phase 3. We are going to see a lot of this when alignment of M11 comes along. I suspect we will see several "conflicts" with existing CDISC terms and what to do will not be simple.

**Comment by dih-cdisc** [comment]
Attach to #40. The work will be covered there

**Comment by dih-cdisc** [comment]
Also see JIRA tickets [JIRA 514](https://jira.cdisc.org/browse/DDF-514) [JIRA 515](https://jira.cdisc.org/browse/DDF-515) [JIRA 516](https://jira.cdisc.org/browse/DDF-516) [JIRA 517](https://jira.cdisc.org/browse/DDF-517)

**Comment by BSnoeijerCD** [comment]
Reviewed comments above and handled as follows:
-	USDM is focussed on clinical studies in general and thus may include interventions that are not medicinal products nor medical devices. 
  o	Definition: Clinical trials are interventional studies and involve investigational medicinal products, whereas clinical studies can include both interventional and non-interventional studies.
-	The definition of a Pharmaceutical Product is “pharmaceutical product is the qualitative (3.1.70) and quantitative composition (3.1.71) of a Medicinal Product (3.1.50) in the dose form approved for administration”. As the investigational product in the clinical trial stage is not yet in approval stage (hence this is the subject of the study) while other co-products could be approved products, the decision is made to align with the IDMP administrable product concept instead which covers both.
-	An administrable product used in a clinical study may include an investigational product and/or an approved pharmaceutical product.
-	USDM release 3.6 aligns to IDMP with the AdministrableProduct, Ingredient, Substance and corresponding Strength classes. 
   o	Elements relevant in the clinical study stage are included and aligned with the IDMP guide: “PMS – Implementation of IDO standards for the IDMP in Europe”. 
-	The ‘AgentAdministration’ class is more generalized to ‘Administration’ to include ‘administrations’ of products, devices, combinations of these and other interventions like psychological therapy.
-	The administration now includes the combination of what the patient takes including the dose form, the actual dose, duration and frequency.

Devices will be handled in #442 – relevant part of notes above is now copied there.
