### ISSUE TITLE
Timing Description [IG]

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#112]
Once the examples have been updated, add further description to the IG on the manner in which the Timing class and Instance class operate

See comments in JIRA tickets:

- [JIRA DDF-453](https://jira.cdisc.org/browse/DDF-453)
- [JIRA DDF-452](https://jira.cdisc.org/browse/DDF-452)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc : created UML picture for timeline:
![Timeline](https://github.com/cdisc-org/DDF-RA/assets/138679324/47ab33ad-0376-4ae1-adda-874786ed759a)

**Comment by dih-cdisc** [comment]
@BSnoeijerCD looks good, nice and compact

**Comment by BSnoeijerCD** [comment]
Updated UML to align with IG on referencing epoch. See IG which is updated and ready for review: https://wiki.cdisc.org/display/USDMIGv3/Study+Timing
