### ISSUE TITLE
ISO 3166 & The FDA [CT]

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#114]
Raised by [JIRA DDF-465](https://jira.cdisc.org/browse/DDF-465)

Also see [FDA announcement](https://www.access.fda.gov/access_images/FURLS_GENC_Migration_2021.pdf)

> Effective January 30, 2021, the FDA Unified Registration and Listing Systems (FURLS) will replace the
> use of ISO-3166 data standards with the Geopolitical Entities, Names, and Codes Standard (nga.mil)
> for populating country, state/province/territory codes and names within its systems.

And [FR Notice](https://www.federalregister.gov/documents/2019/07/19/2019-15352/electronic-submission-data-standards-support-for-geopolitical-entities-names-and-codes)

**Comment by dih-cdisc** [comment]
Look at IDMP and what is happening there. They must "hit" the same issue

**Comment by EMuhlbradt** [comment]
Here is the the link to the GENC page from current FDA sdTCG:
https://nsgreg.nga.mil/genc/registers.jsp?register=IE4

Here are the 2 and 3 letter GENC codes stored in NCIt (https://evs.nci.nih.gov/ftp1/GENC/About.html):
[NCIt-GENC_Terminology.xlsx](https://github.com/cdisc-org/DDF-RA/files/12818421/NCIt-GENC_Terminology.xlsx)

At the end of the day, they are still codes so presumably the model should be flexible enough to support ISO codes or GENC codes, no?

**Comment by dih-cdisc** [comment]
@EMuhlbradt @BSnoeijerCD  

I think what we do is make the country code reference AliasCode rather than Code, then the ISO3166 code can go into Code and the FDA equivavlent can go into an alias

So, I considered the principle we should follow

- Standardise on a code list / value set; be prescriptive
- Where misalignment, standardise on the best global standard
- Allow for regional differences (e.g. in this case FDA)

**Comment by dih-cdisc** [comment]
The GeograqphicScope class attribute 'code' is an AliasCode. This will allow for a standard code and multiple aliases.

Standard Code should be ISO3166
Aliases drawn from GENC (FDA), UN etc

@EMuhlbradt can we add a note to the CT spreadsheet  Row 315 Column I 'Has Value List' that notes that ISO3166 is the standard code?

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl 
Should the "codelist reference" column also be in USDM_CT Excel? I am seeing this information in the "codelist reference" column in the USDM_CT_Changes Excel file but not in the USDM_CT Excel.
