### ISSUE TITLE
Split Model

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#115]
Desire to improve the quality of the model by separating the Logical model from the logic used to serialize the model.

Background materials:

- [Scoping F2F slide deck](https://app.zenhub.com/files/534339959/a50c04e4-9336-4e5f-98e3-c247655d8534/download)
- [Document detailing rationale for splitting](https://github.com/cdisc-org/DDF-RA/files/11944693/Rationale.for.Splitting.USDM.pdf)

Split is into 

1. Logical model (UML)
2. API "rules" of taking UML -> JSON. What form does this take?

**Comment by dih-cdisc** [comment]
Diagram indicating which relationships we are talking about. Blue are the logical relationships and red the API relationships

![DDF USDM Model Split](https://github.com/cdisc-org/DDF-RA/assets/115090009/840134c9-5656-4be7-858b-c602890585a5)

**Comment by BSnoeijerCD** [comment]
Suggested split of PBI
1.  Create logical UML model (suggested as minimal requirement for end of sprint 1)
2.  Align on and document guiding format for the link between the logical model and API definitions
      - i.e. how are we presenting this ? Another UML diagram would be confusing
      - what in general changes in attributes and relationships from logical model to API
3. Implement the logical model to API process and show that this is done in alignment with the guide and with corresponding documentation.

**Comment by jowencdisc** [comment]
Affected IG page is https://wiki.cdisc.org/display/USDMIGv1/Internal+Identifiers+Within+the+Model

**Comment by EMuhlbradt** [comment]
There are 'orphan' relationships that are being renamed as part of this ticket. They are: activityTimeline; bcCategoryChild; scheduledActivityInstanceEncounter; scheduledInstanceTimeline; scheduleTimelineEntry; relativeFromScheduledInstance; relativeToScheduledInstance. 

Logically, shouldn't these be represented as attributes or entities somewhere else in the model so that they can be defined?

**Comment by EMuhlbradt** [comment]
Is the plural in the Id retained even if we remove the Id from the name? For example, 'biomedicalConceptIds': Is the new name biomedicalConcepts or biomedicalConcept?

There are a couple of instances of this throughout.

**Comment by EMuhlbradt** [comment]
Question about renaming of relationship names ('Id' being removed from end of relationship names): Should the new name reflect the model element (entity or attribute) that it is supposed to be representing? For example, 'bcCategoryIds' would change to 'bcCategory' (stripping out Ids) but then bcCategory does not match the entity name 'BiomedicalConceptCategory'. Inconsistency in naming for what is in essence the same concept could be confusing to implementers.

**Comment by EMuhlbradt** [comment]
For the 'Remove relationship from ScheduledInstance Entity' (red lines): Dave's drawing is slightly different to the published CT file at end of sprint 2. CT file has 'scheduledInstanceTimings' whereas Dave's diagram has 'scheduleInstanceTimingIds'. We'll need to confirm which should be correct? Is there an error in the Phase 2 CT or just a typo in Dave's diagram?

**Comment by data4knowledge** [comment]
> Is the plural in the Id retained even if we remove the Id from the name? For example, 'biomedicalConceptIds': Is the new name biomedicalConcepts or biomedicalConcept?
> 
> There are a couple of instances of this throughout.

I think we keep the plural, biomedicalConcepts in this case

**Comment by data4knowledge** [comment]
> Question about renaming of relationship names ('Id' being removed from end of relationship names): Should the new name reflect the model element (entity or attribute) that it is supposed to be representing? For example, 'bcCategoryIds' would change to 'bcCategory' (stripping out Ids) but then bcCategory does not match the entity name 'BiomedicalConceptCategory'. Inconsistency in naming for what is in essence the same concept could be confusing to implementers.

To be discussed with @cupkes but consistency is good :)

So classes ClassA and ClassB, a relationship from ClassA -> ClassB, attribute in ClassA, a 1:1 might be named 'classB' while a 1:M migth be named 'classBs' ???

Issue here is more "bc" or "BiomedicalConcept", the second gets a little long.

**Comment by data4knowledge** [comment]
> For the 'Remove relationship from ScheduledInstance Entity' (red lines): Dave's drawing is slightly different to the published CT file at end of sprint 2. CT file has 'scheduledInstanceTimings' whereas Dave's diagram has 'scheduleInstanceTimingIds'. We'll need to confirm which should be correct? Is there an error in the Phase 2 CT or just a typo in Dave's diagram?

Dave's diagram in error. 

Note going forward, we should not see "Id" appearing in our names in the future. The model should be "pure" and as such we should never need "Id". These should only ever appear in the API

**Comment by dih-cdisc** [comment]
New diagram with error corrected. Note this is now on github in the /Documents directory

![DDF USDM Model Informative](https://github.com/cdisc-org/DDF-RA/assets/115090009/26075c12-86b7-45ea-8549-5247bc454dec)

**Comment by dih-cdisc** [comment]
> There are 'orphan' relationships that are being renamed as part of this ticket. They are: activityTimeline; bcCategoryChild; scheduledActivityInstanceEncounter; scheduledInstanceTimeline; scheduleTimelineEntry; relativeFromScheduledInstance; relativeToScheduledInstance.
> 
> Logically, shouldn't these be represented as attributes or entities somewhere in the model so that they can be defined?

We have not in the past, see current set for StudyDesign, we have just marked as "relationship".  Should we going forward?

![Screenshot 2023-07-10 at 07 11 25](https://github.com/cdisc-org/DDF-RA/assets/115090009/453cda89-b2a0-481b-8277-934ddbe2b2b6)

**Comment by dih-cdisc** [comment]
@cupkes @BSnoeijerCD Some notes on the "link between the logical model and API definitions", the Logical Model to API process. First go an writing down the logic:

Aim is to ensure no duplication in the API JSON format. Steps:

1. Where content is shared (referenced from 2 or more places) identify the "natural parent" relationship, the main use of the content [Example Objective and Endpoint with Endpoint referenced from Estimand. Objective seems the better natural parent]
2. If a natural parent can be identified then include content from the natural parent (attribute name remains unchanged) and cross reference from the other place(s), attribute name modified with suffix "Id" singular or "Ids" (plural)
3. If the natural parent cannot be identifier then form a "collection" from a logical higher level class and add a relationship. Cross reference from all places in the logical model (means an additional relationship in the API for the collection). Example is the BCs in the current API with the collection placed in StudyDesign.

Think that is about it but see what you think.

**Comment by BSnoeijerCD** [comment]
In addition: as discussed during todays daily scrum: 
in case of zero to multiple options the attributes will be referred to as plural. So biomedicalConcepts, codes etc.
We also agreed that this should be written down in a naming conventions piece of the IG.

**Comment by BSnoeijerCD** [comment]
> > There are 'orphan' relationships that are being renamed as part of this ticket. They are: activityTimeline; bcCategoryChild; scheduledActivityInstanceEncounter; scheduledInstanceTimeline; scheduleTimelineEntry; relativeFromScheduledInstance; relativeToScheduledInstance.
> > Logically, shouldn't these be represented as attributes or entities somewhere in the model so that they can be defined?
> 
> We have not in the past, see current set for StudyDesign, we have just marked as "relationship". Should we going forward?
> 
> ![Screenshot 2023-07-10 at 07 11 25](https://user-images.githubusercontent.com/115090009/252229622-453cda89-b2a0-481b-8277-934ddbe2b2b6.png)

Can we discuss in the scrum meeting? I know there was some confusion by users trying to understand the model in that this naming used in the API was not found in the CT/IG. Otherwise, we at least should describe this in the conventions or description of logical model to API.

**Comment by dih-cdisc** [comment]
Diagram looked at during the daily scrum

![2023 06 09 DDF Model Update 1](https://github.com/cdisc-org/DDF-RA/assets/115090009/c6d9182e-b45b-43b4-b46d-8377dbc79449)

**Comment by MarkPAndrews** [comment]
@dih-cdisc In the process of updating String Id fields to Objects, I noticed that StudyEpoch has 2 String for Previous and Next Epoch Id.  Can I assume that those will become self-referencing relationships in your Diagram?
![image](https://github.com/cdisc-org/DDF-RA/assets/8182469/5674863d-78df-4906-9994-0c116fc000ac)

**Comment by a3informatics** [comment]
> @dih-cdisc In the process of updating String Id fields to Objects, I noticed that StudyEpoch has 2 String for Previous and Next Epoch Id. Can I assume that those will become self-referencing relationships in your Diagram? ![image](https://user-images.githubusercontent.com/8182469/252714004-5674863d-78df-4906-9994-0c116fc000ac.png)

@MarkPAndrews Yes, they should be self-referencing relationships, classic doubly-linked list, can be  Null/None for the start and end of the list

**Comment by dih-cdisc** [comment]
> @dih-cdisc In the process of updating String Id fields to Objects, I noticed that StudyEpoch has 2 String for Previous and Next Epoch Id. Can I assume that those will become self-referencing relationships in your Diagram? ![image](https://user-images.githubusercontent.com/8182469/252714004-5674863d-78df-4906-9994-0c116fc000ac.png)

@MarkPAndrews Yes, they should be self-referencing relationships, classic doubly-linked list, can be Null/None for the start and end of the list

**Comment by dih-cdisc** [comment]
@EMuhlbradt @cupkes @MarkPAndrews @czwickl @BSnoeijerCD  

The two estimand relationship errors in the UML, treatment and variableOfInterest we we have a UML, CT, API mismatch, lets make sure we have that aligned as part of this ticket / work

Current API, the names should be suffixed with "Id" in the API but match what should appear in the UML (now we are changing it)

so "treatment" in UML and CT but "treatmentId" in API (because it will be a xref in the API). It should have been "treatmentId" in the UML & CT prior to this change but we got it wrong :)

```
class Estimand(ApiBaseModel):
  estimandId: str
  summaryMeasure: str
  analysisPopulation: AnalysisPopulation
  treatment: Union[str, None] = None
  variableOfInterest: Union[str, None] = None
  intercurrentEvents: List[IntercurrentEvent] = []

```

**Comment by dih-cdisc** [comment]
> > > There are 'orphan' relationships that are being renamed as part of this ticket. They are: activityTimeline; bcCategoryChild; scheduledActivityInstanceEncounter; scheduledInstanceTimeline; scheduleTimelineEntry; relativeFromScheduledInstance; relativeToScheduledInstance.
> > > Logically, shouldn't these be represented as attributes or entities somewhere in the model so that they can be defined?
> > 
> > 
> > We have not in the past, see current set for StudyDesign, we have just marked as "relationship". Should we going forward?
> > ![Screenshot 2023-07-10 at 07 11 25](https://user-images.githubusercontent.com/115090009/252229622-453cda89-b2a0-481b-8277-934ddbe2b2b6.png)
> 
> Can we discuss in the scrum meeting? I know there was some confusion from users trying to understand the model in that this naming used in the API was not found in the CT/IG. Otherwise, we at least should describe this in the conventions or description of logical model to API.

The names should align across the CT and UML, if not then that implies an Error/Bug. As for a definition, down to @EMuhlbradt, I think one issue is/was, if they have definitions, the then need C codes and be added to CDISC CT, maybe not something we wanted?

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD : CT Deliverable updated in the Github Repository, branch 3-1

**Comment by BSnoeijerCD** [comment]
@MarkPAndrews @cupkes @dih-cdisc 

Below the split model issues I noted this morning:
- ID in study class should be UUID (all other IDs are strings)
- As discussed in yesterday's scrum meeting and according to CT of Erin and Craig: the following attributes should not have been changed:
    - bcName
    - bcPropertyName
    - OrganizationName
    - TimingDescription
- Please Check Dave's diagram for correct relation of scheduleTImelineEntry
- Relation from studyCell to studyEpoch added but no corresponding record of deletion in the list. Please check with Daves diagram whether relationship is ok?
- new relationship scheduledActivityInstanceEncounter. No corresponding record of deletion in the list. Please check with Daves diagram whether relationship is ok?
- the relation defaultCondition is linking from scheduledInstance to scheduledInstance -> naming and purpose not clear of this relation is not clear.
- Relation from studyDesign to BiomedicalConcepts, bcCategories and bcSurrogates not deleted. See red lines in Dave's diagram for what relationships should be removed (for UML not for API)

Please check all other items and relationships with Dave's diagram as well. I might have missed some in my check this morning. 
Also check the changes to Name and Description based on the CT file of Erin and Craig. It could be that more changes have been done which are not in their list. Not all Descriptions and Names were changed only if they came in pairs as Dave indicated yesterday.

@EMuhlbradt, @czwickl and @jared-schreibman-cdisc  : for your information

**Comment by MarkPAndrews** [comment]
@BSnoeijerCD I found a bug in the Delta Generation code that was causing the missing deletions.  I will be generating a new Delta file with the changes you mentioned after a review of the current spreadsheet as well.

**Comment by MarkPAndrews** [comment]
@BSnoeijerCD The updated file is in the sprint-3-1 branch now.

**Comment by BSnoeijerCD** [comment]
@cupkes @MarkPAndrews @dih-cdisc @EMuhlbradt 
Thank you for all the updates. It looks much better. I reviewed the CT and compared to the UML. I found the following issues:

For UML:
- purposeDescription in class endpoint not changed back to endpointPurposeDescription
- dataOriginDescription in class studyArm not changed back to studyArmDataOriginDescription
- code for scheduleInstanceType now added as a class in the UML model. Please remove scheduleInstance class and refer to code class. The code options do not have to be stored in the model as agreed upon before and corresponding to all the other code lists.

For CT - Id was not removed from the following namings which caused inconsistency with UML:
- in entity studyCell "id" not removed from relationships: studyArmId, studyEpochId and studyElementIds
- in entity studyEpoch "id" not removed from names:  previousStudyEpochId and nextStudyEpochId
- in entity encounter "id" not removed from names: previousEncounterId and nextEncounterId
- in entity biomedicalConceptCategory "id" not removed from bcCategoryMemberIds
- in entity scheduledInstance "id" not removed from defaultConditionId

**Comment by dih-cdisc** [comment]
> @BSnoeijerCD , as I was finishing the task above, I noted the last two instances of the use of 'Id' in a model element name were in the Activity entity: "id" not removed from previousActivityId and nextActivityId. Please confirm whether I should also remove those last two as well?

As discussed on scrum meeting 20 July, should be removed.

**Comment by MarkPAndrews** [comment]
@BSnoeijerCD I have pushed the latest changes to Git and IG has been updated.  Please review them and let me know if anything was missed.

**Comment by jowencdisc** [comment]
@BSnoeijerCD - From the DSU yesterday it looks like he change requested by Dave was made
![image](https://github.com/cdisc-org/DDF-RA/assets/106146515/e96ab180-c30c-45a3-a58f-90fbb9add205)
bcCategoryMembers amended from type BiomedicaConcept to List<BiomedialConcept>.
Also referenced in the Data Diectionary
![image](https://github.com/cdisc-org/DDF-RA/assets/106146515/74e919cb-8e3a-4d82-8c4a-85f537be6d7d)

**Comment by jowencdisc** [comment]
@jared-schreibman-cdisc @BSnoeijerCD @MarkPAndrews - Does the change above have any impact on the API?

**Comment by BSnoeijerCD** [comment]
@jowencdisc @jared-schreibman-cdisc @MarkPAndrews - This change is indeed ok. I don't think this requires a change in the API like for other ID and reference changes. The rules for differences between UML and API should have been noted in IG. I will try to review it today.

**Comment by MarkPAndrews** [comment]
@BSnoeijerCD @jared-schreibman-cdisc That is correct.  This change was to correct a mistake I made when I originally converted the String ids to Objects.  This property was previously `private List<String> bcCategoryMemberIds` so the API should already have it correct.  In my original change I inadvertently dropped the list.

**Comment by BSnoeijerCD** [comment]
> 

@jared-schreibman-cdisc. I see IntercurrentEvents are nested in Estimand. (So no id addition is needed and it is correct how is is. However, Analysispopulation does not seem to be nested. Should id then not be added to the the API spec?

**Comment by BSnoeijerCD** [comment]
@jared-schreibman-cdisc @jowencdisc
I have a few additional comments for the API:.
- Class BiomedicalConceptCategory: bcCategoryCode should be plural
- VariableOfInterest in class Estimand should be VariableOfInterestId. 

Should the id on study level not always be UUID? Now I see that both UUID and string are allowed. I would not change that compared to previous version. That will cause the RI huge problems otherwise.

**Comment by MarkPAndrews** [comment]
@BSnoeijerCD In the UML `bcCategoryCode` refers to a single `AliasCode`  Does this need to be changed to a `List<AliasCode>` along with renaming it to `bcCategoryCodes`?

For the UUID question, I believe the decision was made to keep all ids a String and let the implementation determine if they wanted to use a UUID.  This excludes `Study.id` which has some history around it remaining a UUID.
@jowencdisc  @jared-schreibman-cdisc  @cupkes

**Comment by BSnoeijerCD** [comment]
@MarkPAndrews @jared-schreibman-cdisc @jowencdisc @cupkes 
Thank you Mark for pointing this out and checking my comments. You are right about the bcCategoryCode. So that does not have to be changes.

For the Study.Id I was confused by the "AnyOf" that was introduced (I am not (yet) knowledgeable in JSON/API but learning fast). So it is correct as well. 
The old API was like this:
  "properties": {
          "studyId": {
            "title": "Studyid",
            "type": "string",
            "format": "uuid"
          },

The new API is now like this:
"Study": {
        "properties": {
          "id": {
            "anyOf": [
              {
                "type": "string",
                "format": "uuid"
              },
              {
                "type": "null"
              }
            ],
            "title": "Id"
          },

Also the variableOfInterestId (reference to endpoints) and AnalysisPopulation (nested) are OK. So the API is good to go for 2.1.
