### ISSUE TITLE
Model Naming

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#116]
Desire is to make the model more "implementation" friendly while maintaining the precision of the definitions and preferred terms

See [slide deck](https://app.zenhub.com/files/534339959/75c6cd38-4939-4a6b-a646-1924d17922e7/download) from London scoping F2F meeting

We need to document the naming convention, probably in the IG in an introduction section

**Comment by BSnoeijerCD** [comment]
Suggested split of PBI:
1. Align on and document the standard naming conventions and present in IG
2. Define what attributes in the model need to be changed - change correspondingly in CT and logical model
3. Update attributes in API (1 sprint later)

**Comment by dih-cdisc** [comment]
Spreadsheet with the list of potential attributes. Two sheets

- One with name & description pairs. I think these are the candidates for just being "name" and "description" attributes. Note, they are always in pairs.
- Second sheet with classes with only description fields. These are the "scientific" fields that I don't want to change.

@EMuhlbradt @czwickl Have a think on these, this is your call. This is just an extract from the latest CT spreadsheet as per V2.

[NameAndDescription.xlsx](https://github.com/cdisc-org/DDF-RA/files/11966790/NameAndDescription.xlsx)

**Comment by jowencdisc** [comment]
@EMuhlbradt Move studyArmDataOriginDescription to Caution tab

**Comment by jowencdisc** [comment]
Update needed to https://wiki.cdisc.org/display/USDMIGv1/USDM+Data+Dictionary

**Comment by EMuhlbradt** [comment]
We have discussed all of the proposed changes to UML model names for Name and Description type attributes. Our comments/thougts/recommendation are in the attached.

[NameAndDescription_116_em.xlsx](https://github.com/cdisc-org/DDF-RA/files/11982518/NameAndDescription_116_em.xlsx)

**Comment by dih-cdisc** [comment]
One comment from the spreadsheet

_"General recommendation from Erin/Craig: All entities should be considered to have the following attributes at the very least: Id, Name, Label, Description, Code, and Type. Then it is a logical exercise to determine for each entity, what subset of these are valid/used in practice."_

Label and Description. We have not yet used "Label". What is the logic here? Do we want to distinguish between "Label", just a useful human readable label and description which is something more specific?

**Comment by BSnoeijerCD** [comment]
Attribute Codes links to 'foreign' dictionaries for interventions and Indications. So the indication "Diabetes" can have multiple codes in 1 or more multiple dictionaries. The attribute codes is therefore important for linking to other dictionaries. Also regulatory agencies require those codings. For example CTIS requires a lot of different codings for the Intervention. Adding a Name attribute (and possibly a label) is indeed a good extension for version 3.

**Comment by dih-cdisc** [comment]
> Attribute Codes links to 'foreign' dictionaries for interventions and Indications. So the indication "Diabetes" can have multiple codes in 1 or more multiple dictionaries. The attribute 'codes' is therefore important for linking to other dictionaries. Also regulatory agencies require those codings. For example CTIS requires a lot of different codings for the Intervention. Adding a Name attribute (and possibly a label) is indeed a good extension for version 3. However, it does not add value to nest the codes within names as the codes related to the whole intervention and not only to the name of the intervention.

For multiple alternative codings the AliasCode is used. So where this is needed we can change "Code" -> "AliasCode". AliasCode has one standard code and multiple alternative Codes

**Comment by BSnoeijerCD** [comment]
AliasCode includes the option for 1 standard code and multiple alternative codes. In other cases, the standard code is the CDISC CT. However, for interventions and indications, this does not hold. @dih-cdisc Is it then better to refer to a list of multiple codes like we have now or to the AliasCode class?

**Comment by BSnoeijerCD** [comment]
In the discussion with Diana, Rebecca and Bess on alignment with SDTM Trial summary domains, Diana indicated that Type alone is not specific enough. Type can be anything and we should better indicate what type we mean. So removing the class name is therefore not a good option since there can be many kinds of types for a single entry in a class. So, on the contrary it might even have to be more specific then only adding the class name.

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD : CT Deliverable updated in the Github Repository, branch 3-1

**Comment by dih-cdisc** [comment]
> In the discussion with Diana, Rebecca and Bess on alignment with SDTM Trial summary domains, Diana indicated that Type alone is not specific enough. Type can be anything and we should better indicate what type we mean. So removing the class name is therefore not a good option since there can be many kinds of types for a single entry in a class. So, on the contrary it might even have to be more specific then only adding the class name.

This is not the case. The "type" field refers to , and only refers to , the type of the class/instance. Any other "types" have their names distinguished by some prefix to distinguish them. In addition, the preferred terms and definitions remain. 

As an example, look at the StudyArm  class:

![Screenshot 2023-07-17 at 06 17 06](https://github.com/cdisc-org/DDF-RA/assets/115090009/eabb86f8-f99e-4b82-a2f9-be7d9df03764)

Here we have type (of the study arm) and the dataOriginType ( the origin type of the arm's data) with their associated preferred terms and definitions. Prefixing "studyArm" makes them no more distinguishable. The "type" field always refers to type of the class/instance as the name always refers to the name of the class/instance. Any additional types need to be prefixed with an appropriate preferred term and definition.

![Screenshot 2023-07-17 at 06 23 28](https://github.com/cdisc-org/DDF-RA/assets/115090009/7eb7e8a6-433a-405e-8832-bedd70fe875e)

**Comment by BSnoeijerCD** [comment]
Thank you Dave. Makes sense. This will help in further discussions on naming standards..

**Comment by BSnoeijerCD** [comment]
> branch

Thank you Erin. You probably indicated this in the Excel. But can we discuss today why the following items were not changed? - bcName, bcPropertyName, OrganizationName, TimingDescription. I believe they should fall under the same convention as the ones that are changed now.

**Comment by dih-cdisc** [comment]
> > branch
> 
> Thank you Erin. You probably indicated this in the Excel. But can we discuss today why the following items were not changed? - bcName, bcPropertyName, OrganizationName, TimingDescription. I believe they should fall under the same convention as the ones that are changed now.

As discussed on the scrum call 17th Jul, these should not be changed. See ticket

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @dih-cdisc :
The following changes do not fall under the (only Name, Id, Description rule)
- studyArm part removed from studyArmDataOriginDescription. 
- endpointPurposeDescription changed to PurposeDescription

@MarkPAndrews and @cupkes - please note as well.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD fixes completed in Github Repo for CT deliverables
