### ISSUE TITLE
Extended Syntax Template Proposal

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#120]
SME Meeting will provide details that will change what was originally proposed in #16.

Chris and Mark will attend with Berber and Dave on Monday 24th.

**Comment by drewcdisc** [comment]
Berber will work with Chris and Mark to confirm understanding.

**Comment by MarkPAndrews** [comment]
After reviewing the work done in #16 I believe the proposed model can handle the use cases laid out in #48 .  By having a dictionary element that holds a Map, it would support implementations using JSON to hold String literals in name, value pairs as well as object references to the instances of other elements in the model.
Most of the use cases discussed in the SME meeting on Monday 31st are implementation concerns such as the ability to handle "And or Not" syntax in the template text.  This model can support the use of multiple parameters, but it would be up to the implementation to parse the template text and govern the placement of the parameter values within the output text.
Here is an updated UML diagram for the proposed model changes including the standardized attributes.
![image](https://github.com/cdisc-org/DDF-RA/assets/8182469/b72258e6-a11c-4c06-9a40-a7d204be04df)
Let me know if you have any questions or concerns.

CC: @daveih @jared-schreibman-cdisc @BSnoeijerCD @cupkes

**Comment by BSnoeijerCD** [comment]
@MarkPAndrews Thank you.
I can follow your thinking. However, could you give an example of what information goes where in the above classes ?and how the dictionaryitems are referenced in the templateText?
It now indicates a 1 to 1 relationship while 1 templateText can have multiple references to items elsewhere in the data model.

**Comment by MarkPAndrews** [comment]
@BSnoeijerCD In #16 there is an example of how JSON could be used (https://github.com/cdisc-org/DDF-RA/issues/16#issuecomment-1386505010). The 1 to 1 relationship is to a SyntaxTemplateDictionary with a Map that can contain multiple references in name, value pairs.  The names would be used by template to replace with the values.    Of course, the devil is in the details.  If the Map has a reference named "Activity" that points to an instance, the Template will need to provide details about what value to use in replacement.  i.e. "To compare the effect of [Compound] relative to [Comparator] on [Activity.getBiomedicalConcepts()]".  These are implementation details, but the model supports it.

**Comment by BSnoeijerCD** [comment]
@MarkPAndrews I understand. That is why I was asking for the examples because then we can explain next week how it works and we can discover potential issues.
I saw the Json example. But with the changes, I would like to see what information can go where. The json example now only shows a fixed text and not a reference to another place in the model. Could you prepare a new example where the comparator and the compound refer to a specific investigationalIntervention name or description specified in the corresponding class in the model. And the activityInstance to a specific BC description specified in the BC class? 

So how would activity.getBiomedicalConcepts() work? I assume that is a method and not a direct reference. Do you mean that it would have to be provided by the software and is not specified in the data model which exact biomedicalconcept we are referring to? I would prefer that we can do this reference. So more  a reference like: class.attribute.instance

**Comment by MarkPAndrews** [comment]
@BSnoeijerCD Here is a diagram showing using object references in the `parameterMap` only with a sample `templateText`.  Thoughts?
![image](https://github.com/cdisc-org/DDF-RA/assets/8182469/fb5826be-0d1b-4221-916e-2e8c952c5e50)

**Comment by dih-cdisc** [comment]
@MarkPAndrews @BSnoeijerCD I can see where you are going with this, nice example. The tricky bit is in explaining to the world the parameter map and the three object identifiers for the two interventions and the activity. A small, hand-crafted, JSON API example might be useful.

Also, Activity and biomedicalConcepts is a list, so how do we address the correct BC?

**Comment by BSnoeijerCD** [comment]
@MarkPAndrews @daveih
The ID was indeed something we wanted to include to point to a specific instance in the list.
Could there be a reference like Activity.BiomedicalConcepts.Name (Id=xxx)

**Comment by MarkPAndrews** [comment]
@dih-cdisc  One of the things discussed in the SME meeting was the ability to handle "and" syntax.  So the list of biomedicalConcepts could generate something like "body weight and metabolism" or you could be more specific and use the `(id="BC1")` nomenclature.  These rules and processes would all have to be handled by the implementation code.  We are basically defining a custom query language that someone else will need to implement.

**Comment by BSnoeijerCD** [comment]
[SyntaxTextTemplates_mapped.xlsx](https://github.com/cdisc-org/DDF-RA/files/12359489/SyntaxTextTemplates_mapped.xlsx)
Examples of content for the classes as just discussed during the planning meeting.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD did the team agree that the 'description' attribute is unnecessary for the new SyntaxTemplate entity? We (Erin/Craig) agree it is superfluous and can be not added however we'd like confirmation on that.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt I don't see a need for it. But maybe good to be confirmed by @dih-cdisc .

**Comment by dih-cdisc** [comment]
@BSnoeijerCD @EMuhlbradt @czwickl 

As discussed at scrum meeting 23 Aug 23, no harm in adding description. Label can also be added.

General note / Philosophy

- Any new class should have "name", "description" and "label" "assigned" by default unless good reasons not to. 
- "type" and "code" then added if needed by the nature of the class. 
- "type" would (generally, if it wasn't it would ring bells) be a single Code or AliasCode (e.g. Eligibility Class type = Inclusion or Exclusion)
- "code" might be one or a list of Code or AliasCode (e.g. Procedure code LOINC or Snomed code(s) for the procedure). If "code" is a list rename to "codes"?

Need to be aware of "category" as Craig has already noted versus "type", a different beast. "category" might be one worth adding to our standard list in the future when we first encounter it. I think we may have one lurking already in Procedure (e.g. Labs, Chemistry, Physical Exam ....). A category might need the ability to have a code or free text (ie a new generic class like AliasCode)
