### ISSUE TITLE
Additional Standard Class Attributes [CT/Model]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#125]
Additional, standard new ones:
- label
- type
- code

**Comment by BSnoeijerCD** [comment]
As discussed during scrum 08/08: Change TimingDescription to Description and add Name and Label to Timing class

**Comment by jowencdisc** [comment]
Two parts to this work
1) Name changes to existing classes that contain type and code elements (CT and MODEL DONE) - API to be done
2) Identifying additional classes that need any of the default elements (name description label code and type)

**Comment by EMuhlbradt** [comment]
[DDF Sprint 4_Addition of Label Attribute.xlsx](https://github.com/cdisc-org/DDF-RA/files/12428887/DDF.Sprint.4_Addition.of.Label.Attribute.xlsx)

Please see the attached spreadsheet containing the list of potential attribute additions for 'label' to various entities.

**Comment by dih-cdisc** [comment]
> [DDF Sprint 4_Addition of Label Attribute.xlsx](https://github.com/cdisc-org/DDF-RA/files/12428887/DDF.Sprint.4_Addition.of.Label.Attribute.xlsx)
> 
> Please see the attached spreadsheet containing the list of potential attribute additions for 'label' to various entities.

Erin

Two comments:

1. Timing class, "label" attribute already added in previous sprint?
2. Content class, not sure "label" is useful here. We have unstructured text which is, in some way, the label, the human readable form. That is in the "text" attribute so tempted not to add here.

**Comment by BSnoeijerCD** [comment]
Label for syntaxTemplate and SyntaxTemplateDictionary in USDM_CT.xls. I thought we agreed not to include label for syntaxTextTemplates?

**Comment by EMuhlbradt** [comment]
I have it in my notes that the 'label' attribute is unnecessary for Content entity, but nothing in my notes from yesterday to remove 'label' attribute from SyntaxtTemplate class. Does anyone else remember that discussion?

**Comment by dih-cdisc** [comment]
@EMuhlbradt @czwickl @BSnoeijerCD Cannot think of any reason not to include "label" as per discussion on scrum call of 29th Aug 2023

**Comment by jowencdisc** [comment]
@jared-schreibman-cdisc to refer to the CT changes XL file in the release 2-3 branch where a list of labels has been inserted into various classes.
