### ISSUE TITLE
Inclusion/Exclusion [CT]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#129]
Linked to parent ticket #100

**Comment by EMuhlbradt** [comment]
Erin/Craig question about one of the attributes of the EligibilityCriteria class: 

Currently 'identifier' is one of the attributes for this class, however we think this is really describing the order of each criterion within the category (Inclusion or Exclusion). Therefore we think the attribute name should be something like: orderNumber (instead of 'identifier). Thoughts?

**Comment by dih-cdisc** [comment]
@EMuhlbradt @czwickl @BSnoeijerCD 

Have a look at the diagram and notes. I think we need identifier but I think the ordering is distinct, hence I have put prev and next relationships in. Also added some notes on TI generation and how we might handle IE "versions".

![2023 09 06 InclusionExclusion](https://github.com/cdisc-org/DDF-RA/assets/115090009/54dfee75-46c4-4e93-9167-0a6d4cf339aa)

**Comment by EMuhlbradt** [comment]
Please see the attached spreadsheet containing the terminology for inclusion/exclusion criteria.
[CT for Backlog item number 129.xlsx](https://github.com/cdisc-org/DDF-RA/files/12548526/CT.for.Backlog.item.number.129.xlsx)

**Comment by EMuhlbradt** [comment]
[CT for Backlog item number 129.xlsx](https://github.com/cdisc-org/DDF-RA/files/12549295/CT.for.Backlog.item.number.129.xlsx)

Updated CT file

**Comment by drewcdisc** [comment]
Differences from the model image above:

- Change criteria to criterion 
- Leave off previousVersion and nextVersion (for now)

**Comment by BSnoeijerCD** [comment]
Hi @daveih: See mismatch indicated in previous comment. Erin indicates that it should be category in your green blob diagram as well.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl : please add relationship from studyDesign to eligibilityCriteria to CT.
