### ISSUE TITLE
Learn the Diff/Data Dictionary generator

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#131]
- Mark will lead a working session with Jared and Gerry to make sure they understand how to use the tool.  
- Jared and Gerry  will run the tool and confirm their understand and confirm successful results.
- The group will fork the current repo and put it into a GitHub repo.

**Comment by MarkPAndrews** [comment]
@drewcdisc or @dih-cdisc Is there a CDISC Github Repository that can be used for the generator code?  We'll also need one for the DDF-conformance code as well.  That is the Java code used to generate the UML.

**Comment by drewcdisc** [comment]
I will create a repo. Probably ddf-tools. I'll invite you all when it's done.

**Comment by MarkPAndrews** [comment]
I have shared the Git Repo with Jared and updated the readme.MD file.  @jared-schreibman-cdisc once the new repo is available and you have forked the code, can you share a link to it so that it can be reviewed?

**Comment by BSnoeijerCD** [comment]
@jared-schreibman-cdisc : did you share the link for review? Can this ticket be closed?
