### ISSUE TITLE
Documentation for tools that are being handed over

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#132]
The documentation has been written. Mark will review it with Jared and Berber and make any updates if necessary.

**Comment by MarkPAndrews** [comment]
See https://github.com/cdisc-org/DDF-RA/issues/131#issuecomment-1688726902

**Comment by MarkPAndrews** [comment]
@drewcdisc I have invited you to Admin the `neo4j-field/usdm-dictionary-generator` Git repo.  I tried to transfer ownership to `cdisc-org` but I got an error that I don't have permission to create a repo there.

**Comment by BSnoeijerCD** [comment]
I checked the documentation. It is not extensive but I believe enough to work with from a technical perspective.
