### ISSUE TITLE
Content class description/user notes [IG]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#134]
We need a new **Unstructured Text Content** section in the IG. It should be at the same level as **Timing** and others. This should fall into Section 4 of the IG.

**Comment by drewcdisc** [comment]
@daveih ideas:

- We can build a hierarchy due to the recursive nature of content.
- Sections are formatted using HTML.
- They are ordered by Section number.
- Therefore we can build any document structure using the above, e.g. M11, CPT, or Sponsored Template.

**Comment by BSnoeijerCD** [comment]
@czwickl  It would be beneficial to add examples to the IG (like I did for syntax text templates).

**Comment by dih-cdisc** [comment]
@BSnoeijerCD We decided in Phase 2 not to put examples in the IG as we have examples in the examples directory with the Excel / JSON and maintaining examples in the IG becomes time intensive. The syntax template examples will need to move into the excel / json examples when they are handled in the excel tool.
