### ISSUE TITLE
Education on test data

### ISSUE THREAD

**Issue by jowencdisc** [cdisc-org/DDF-RA#138]

**Comment by jowencdisc** [comment]
Handover of test data from @jared-schreibman-cdisc from @dih-cdisc so that Jared can update the master XL file with any new elements from the model. Also to update to the program that converts the XL to JSON.
Note that there will be a v2.0 master XL and program and a version 3.0 master XL and program.
Also note there is test data sub-group being formed who are trying to help update the actual test data in the https://github.com/cdisc-org/DDF-RA/tree/sprint-3-3/Documents/Examples
Also see https://wiki.cdisc.org/display/TEAMDDF/Test+Data+Updates

**Comment by dih-cdisc** [comment]
Updated the title. No "handover", there is a process of education such that @jared-schreibman-cdisc can also work on the test data but it will not be "either" /  "or" situation. This is important to understand.
