### ISSUE TITLE
Potential Issues in CT Definition [CT]

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#144]
Few items to be checked considered. Numbers refer to Column A in the attached spreadsheet.

- 54: Is description right here? I think it is ok but just have a check
- 57: Not sure the Has Value List column entry is correct
- 97: Description is the only attribute and is optional (first with all the other description fields). But we have no required definition of the rule. Add another field? Change the name to "definition" or "rule"? Similar to 135 below
- 135: Description is the only attribute and is optional (first with all the other description fields). But we have no required definition of the population. Add another field? Change the name to "definition" or "population"? Similar to 97 above

[USDM_CT_Required.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBak1yIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8fbbe7a8d818fa8a0605d40627d49bb11eb38cc3/USDM_CT_Required.xlsx)

**Comment by EMuhlbradt** [comment]
54: We recommend leaving 'description' attribute as is but more attributes will need to be added in future (name, label, or fields from M11). Propose slight update to definition.
57: We recommend associating this valid value set description with the 'name' attribute and not the 'description' attribute
97: We think that there is potential for more attributes to be added to this class (names, ids, categories, etc.) however we need example data to understand what is needed IRL.
135: We think that there is potential for more attributes to be added to this class (names, ids, categories, etc.) however we need example data to understand what is needed IRL.

**Comment by dih-cdisc** [comment]
@EMuhlbradt @czwickl Let me have a ponder, second look given your comments. Not our main worry at the moment

**Comment by dih-cdisc** [comment]
@EMuhlbradt @czwickl @BSnoeijerCD 

54: Agreed, we will be adding more attributes here a la IDMP, driven by M11. Revisit then.
57: We need to discuss this one :)
97: Have a look at the SDTM TE domain and the TESTRL and TEENRL variables. Also TV domain and TVSTRL and TVENRL. Currently we are holding the rule that equate to these variables within description. I would content that we might have 'better' attributes
- name: HEALTHY_EXIT
- description: The rule for leaving the healthy element
- label: Healthy Exit Rule
- rule: Subject must be male and suffering from man flu (and thus dying and in need of constant care and attention).
You could name rule "definition". My concern is that our new generic definition of the "description" attribute is not suitable for the actual specification of the rule, it is a description of the rule, not the actual rule.
135: Similar to 97 but this time the specification of the actual population rather than a narrative description. 

Just to add, I see "description" and a useful, free text description (as we say, narrative) of an item, not its definition. Description need not be filled in, the definition must be. Just want the use to be totally consistent across all classes for name, label, description.

**Comment by EMuhlbradt** [comment]
For item 57 above: please expand on your thoughts. Do you agree with our proposal?

For item 97 above: based on the example data provided we would like to propose adding name and label attributes, keep description attribute, AND add a text attribute to hold the actual rule.  We think the use of 'text' here is similar conceptually to the text attribute for SyntaxTemplate and NarrativeContent classes.

For item 135: In this instance we feel that a 'description' field would be enough to describe/characterize the analysis population. At best we think a name attribute may need to be added. If you are thinking that additional information about the analysis population is needed (e.g., rationale/justification for analyzing that population) this would not be appropriate for a description attribute. It may require its own attribute. Otherwise we can't see how the 'description' field could hold anything more/different than the actual text describing the analysis population.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @daveih @czwickl 
Can we have a final agreement on the following?

No **54**: as you agreed upon above leave as is for now. It is not in the scope of this ticket.
No **57**: The description should not have a valid value list as Dave indicates above. The codes attribute does this already and refers to external dictionaries. We don't want to make our own codelists for indications within CDISC (as far as I understood, that huge effort is beyond our scope). The description is just a narrative that might be used in text as a human readable representable form of the official codes that are linked to the indication. 
No **97**: Add name, label and text attributes as Erin indicates above.
No **135**:  Analysis populations can be ITT, PP, SAFETY etc. Example: Name="ITT population", Description="intent to treat population", Label="ITT", Text="All subjects who entered the study and were eligible to start study drug intake". So, as Dave indicates above: adding name, label and text attributes to the AnalysisPopulation class is of value. Therefore, I believe we should add it.

**Comment by EMuhlbradt** [comment]
For item number 57 above, the team agrees to remove the value set pointer from the Indication.description attribute and also agreed that the value set pointer should not be added to the Indication.name attribute. However a separate question came up as to whether the Indication class needs a name or label attribute AT ALL given that a 'decode' may be inherited from the code class. 

So the question is, should we keep the name and label attributes on the Indication class?

**Comment by dih-cdisc** [comment]
@EMuhlbradt @BSnoeijerCD @czwickl 

Item 57, I think we are going a little off the rails here, and I say this in the nicest possible way :)

The problem is the CT spreadsheet:

<img width="1236" alt="Screenshot 2023-09-19 at 11 45 53" src="https://github.com/cdisc-org/DDF-RA/assets/115090009/01023706-e1b1-4d9b-97ef-a25f9a013a73">

Note the definition for "codes" and "description". Both are speciffied as coded. They are not. "codes" is zero, one or more codes references to, probably, external CT. "description" is our new description, plain text, optional

This is Indication from end of Phase 2, justb a set of coded values and a description.

<img width="298" alt="Screenshot 2023-09-19 at 11 46 10" src="https://github.com/cdisc-org/DDF-RA/assets/115090009/6843d4d5-0c1c-4ebb-be07-1d3d77da4bfd">

This is what we have now, description field renamed and name and label added. But these are not coded fields, the "codes" attribute has all the coded CT reference info, 

So 

name: 'IND1'
description: 'Diabetes type 1 and 2'
label: 'Diabletes'
codes: 
- SNOMED code Diabletes type 1, 
- SNOMED code for 'Diabetes type 2', 
- XYZ code for Diabetes type 1 
- .... as many as you want

<img width="321" alt="Screenshot 2023-09-19 at 11 46 01" src="https://github.com/cdisc-org/DDF-RA/assets/115090009/a747806b-7d98-4d99-8a07-76cf3662ae3a">

**Comment by BSnoeijerCD** [comment]
Thank you @daveih. That is in alignment with what we discussed yesterday.
@EMuhlbradt @czwickl  Final decision on changes:
1) remove has valid value list = Y from indication.description
2) add name, label and text attributes to transitionRule class
3) add name, label and text attributes to analysisPopulation class
