### ISSUE TITLE
UML improvements [Model]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#149]

**Comment by dih-cdisc** [comment]
@jared-schreibman-cdisc for the "hide relationships to code and aliascode classes" need. We want a "view" that hides this relationship. 

We do not want to remove Code or AliasCode from the UML. So we need two "images", a) the full thing and b) one with those two classes "hidden" so the diagram is easier to read. b) should be derived from a)
