### ISSUE TITLE
Explain model feature inheritance [IG]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#150]

**Comment by BSnoeijerCD** [comment]
As discussed during Scrum meeting of 06Sep23: 
InstanceType is needed to allow for inheritence of attributes. This InstanceType in not included in CT but is shown in the UML. The different options for this instanceType are not part of a codelist but are presented in the UML as well. To explain this to the users of USDM, we can create a dedicated IG part for it.

**Comment by dih-cdisc** [comment]
IG updated

**Comment by BSnoeijerCD** [comment]
@dih-cdisc explained for API in https://wiki.cdisc.org/display/USDMIGv3/USDM+API
The inheritance for UML should be self-explanatory by the model representation and can be explained further for the corresponding topics in the relevant IG parts. 
The CT now repeats all inherited attributes for the 'child' classes. That should be clear enough in combination with the UML.
So I am good to close this ticket.
