### ISSUE TITLE
Add SDTM TS and M11 parameters to population and indication classes

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#153]
See PBIs:
| Item  | Ticket |
| ------------- | ------------- |
| Model |  #246 |
| CT |  #245 |
| API | #247 |
| IG | #175 |
| Examples | #248  |

Based on SDTM evaluation, a few (FDA required) parameters should be added to the population and indication class. 
In addition related M11 parameters that were suggested for SDTM as well can be considered in this ticket.
Based on the SDTM evaluation, we suggest the following parameters:
**Population:**
- Healthy subject indicator (FDA required TS parameter) / can also be a population type if covered by M11. 
- Population type (M11)
**Indication:**
- Rare disease indicator (FDA required TS parameter)
- Stable disease minimum duration (M11)
- Confirmed response minimum duration (FDA required TS parameter)
- Diagnosis group (FDA required TS parameter) Or does this align with Therapeutic area and should we move therapeutic area from study Design to population?
- Relapse Criteria (FDA required TS parameter)

**Comment by BSnoeijerCD** [comment]
Discussed with Diane, Rebecca and Craig during scrum meeting:
- Confirmed response minimum duration more linked to Endpoint - or more in between indication and endpoint
- Stable disease minimum duration - to be checked with M11 specs - where and how used. If not specific parameter and we are unsure we can leave it out of this phase.

- There should be a reference from population to indication as a population can have zero to many indications.  

-

**Comment by BSnoeijerCD** [comment]
More discussed during SDTM team meeting:
- Stable disease minimum duration is only part of the story. What is the definition of stable disease depends on disease and is also important.

**Comment by BSnoeijerCD** [comment]
@daveih @EMuhlbradt @czwickl 
Given the above, I think we can limit the number of attributes to add to:
**population**.type => covering M11 type. This does include healthy subjects as far as I understood,
**indication**.rareDiseaseIndicator => covering FDA required SDTM parameter. Should contain only Y/N
**indication**.relapsecriteria => can be multiple. Covering FDA required SDTM parameter. Could also link to outcome.

There is one attribute that link both to indication and intervention (to be discussed):
- confirmed response minimum duration is a link between intervention and diagnosis group. I tend to link this more to the intervention then the diagnosis.

Furthermore, I strongly feel that population should have a link to indication as also represented in other models. A population can be described by 0 to many indications. Can we add that as well?
 

I believe the  attributes we need to add based on TS

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD for the population class above, are you talking about the AnalysisPopulation class or StudyDesignPopulation class? We have both in USDM.

**Comment by BSnoeijerCD** [comment]
> @BSnoeijerCD for the population class above, are you talking about the AnalysisPopulation class or StudyDesignPopulation class? We have both in USDM. I would assume StudyDesignPopulation since we are talking about the M11 protocol but want you to confirm either way.

Thank you for brining this up: studyDesignPopulation. I have changed it above.

**Comment by EMuhlbradt** [comment]
[backlog item 153 - CT considerations.xlsx](https://github.com/cdisc-org/DDF-RA/files/12738144/backlog.item.153.-.CT.considerations.xlsx)

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD what do you mean by your statement above:

"There is one attribute that link both to indication and intervention (to be discussed):
confirmed response minimum duration is a link between intervention and diagnosis group. I tend to link this more to the intervention then to the diagnosis."

I'm not sure how to interpret this. Is there a relationship that needs to be added to the Intervention class?

**Comment by BSnoeijerCD** [comment]
> @BSnoeijerCD what do you mean by your statement above:
> 
> "There is one attribute that link both to indication and intervention (to be discussed): confirmed response minimum duration is a link between intervention and diagnosis group. I tend to link this more to the intervention then to the diagnosis."
> 
> I'm not sure how to interpret this. Is there a relationship that needs to be added to the Intervention class?

@EMuhlbradt This is something we need to discuss with the group. "Confirmed minimum Response Duration" is a conditionally FDA required parameter in SDTM TS but is not clearly belong to either intervention or indication. So we need to see where it best fits if we want to add it to the USDM.

**Comment by BSnoeijerCD** [comment]
Based on CT.gov review we need and indication for 
- Healthy volunteers
And for observational studies:
- from which source/population the population is sampled
- sampling method

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @dih-cdisc : See mapping files for  TS domain and CT.gov attached
[TV_TS_studyLevel.xlsx](https://github.com/cdisc-org/DDF-RA/files/13388889/TV_TS_studyLevel.xlsx)
[CT.gov_mapping.xlsx](https://github.com/cdisc-org/DDF-RA/files/13388890/CT.gov_mapping.xlsx)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc final list of proposed new attributes based on latest v2.7 of USDM:

New for PopulationDefinition:
- isHealtySubjects -> boolean
- type -> code -> CT for population type according to M11
- 0..* relationship to indication

New for Indication
- isRareDisease -> boolean
- stableDiseaseMinimumDuration (only if required in M11)
- relapseCriteria -> multiple possible

**Comment by dih-cdisc** [comment]
As discussed on daily call, the boolean flags, what distinguishes these features?

1. isHealtySubjects -> boolean
2. isRareDisease -> boolean

**Comment by BSnoeijerCD** [comment]
What are indications that **healthy** subjects are included?
- No indication stored in USDM (linked to a population)
- Defined as a Phase I study (but not always on healthy subjects)
No other indications in USDM or SDTM terminology found to identify that healthy subjects are included in the study.

**Comment by BSnoeijerCD** [comment]
https://rarediseases.org/rare-diseases/
https://rarediseases.info.nih.gov/diseases?category=&page=1&letter=&search=

**Comment by BSnoeijerCD** [comment]
More info on rare diseases (US flyer Rare Disease Day):
**What is a rare disease?**
In the United States, a disease is considered rare if it is affects fewer than 200,000 Americans. Some countries and the European Union have similar but slightly different definitions.
**How many people have rare diseases?**
According to the National Institutes of Health (NIH), there are approximately 7,000 rare diseases affecting between 25 and 30 million Americans. This equates to 1 in 10 Americans, or one on every elevator and four on every bus.
**What are some examples of rare diseases?**
Rare diseases are present across the medical spectrum. Some are widely recognized by name, such as cystic fibrosis, while others are less known, such as cat eye syndrome. Most cancers (all but a few types) are rare.
There are rare neurological and neuromuscular diseases, metabolic diseases, chromosomal disorders, skin diseases, bone and skeletal disorders, and rare diseases affecting the heart, blood, lungs, kidneys, and other body organs and systems. Many rare diseases are named for the physicians who first identified them. A few are named for patients or even the hospitals where they were first identified.
**How many rare diseases are there?**
There are more than 7,000 rare diseases, according to the National Institutes of Health (NIH).

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl :
Based on the above: As we cannot derive this information from other information stored in the USDM data model, I like to propose to 
or 1) stay with the boolean variables for healthy subjects and rare diseases 
or 2) create a type variable in the PopulationDefinition class that can indicate "Healthy subjects", "Rare disease" and maybe other types that are relevant here.

**Comment by dih-cdisc** [comment]
> @dih-cdisc @EMuhlbradt @czwickl : Based on the above: As we cannot derive this information from other information stored in the USDM data model, I like to propose to or 1) stay with the boolean variables for healthy subjects and rare diseases or 2) create a type variable in the PopulationDefinition class that can indicate "Healthy subjects", "Rare disease" and maybe other types that are relevant here.

Some thoughts

Definition for healthy subjects "Indicate if persons who have not had the condition(s) being studied or otherwise related conditions or symptoms, as specified in the eligibility requirements, may participate in the study." So, the IE determine if healthy subjects are permiited. Lets think further. 

Rare disease might be better as an attribute of disease being studied not of the population. Obviously, if we have an disease code one rules would be disease code NOT IN list of rare disease codes.

**Comment by BSnoeijerCD** [comment]
M11: Subjects with / without disease. Healthiness is subjective...
Use definition of TS - don't define what healthy implies.
- Add flag to PopulationDefinition. This will be inherited by studyCohort and StudyDesignPopulation.
includesHealthySubjects

- Add flag to indication: isRareDisease -> boolean

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @dih-cdisc : see new attributes added to the model:
![Population](https://github.com/cdisc-org/DDF-RA/assets/138679324/dea5cf3a-91df-46b4-96fa-030b3c87991f)

**Comment by dih-cdisc** [comment]
Changes are:

- Class **PopulationDefinition**: Add attribute _'includesHealthySubjects'_ of type Boolean
- Class i**ndication**: Add attribute _'isRareDisease'_ of type Boolean

NOTE: Class PopulationDefinition is inherited by studyCohort and StudyDesignPopulation

**Comment by dih-cdisc** [comment]
Overall changes for release 2.8

![DDF USDM Model Informative](https://github.com/cdisc-org/DDF-RA/assets/115090009/81e804bd-6bde-4841-9ad7-c315f5b2d456)
