### ISSUE TITLE
Protocol Approval Dates [CT]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#158]
Part of Feature #118 

From protocol mapping exercise:

"Approval Date (Comment): Entered as protocol effective date. Actual there are 2 different approval dates on page 1 and 2"

We need to check this through, are there two dates, what are they?

**Comment by jowencdisc** [comment]
@EMuhlbradt @czwickl - I noticed I was assigned to this ticket. Is there anything specific that you need from me?

**Comment by jowencdisc** [comment]
Just noticed that this is a feature ticket so I have assigned @daveih so he gets notifications etc.
