### ISSUE TITLE
Draft Syntax Templates Design

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#16]
A number of issues  that have the same generic requirement

1. Use syntax templates to improve commonality across protocol documents
2. Investigate structure for Objectives and EndPoints  Same as structure text/ syntax templates. 
3. IE Criteria

Have a look at the materials from Phase 1 scoping. Also look at old JIRA tickets:

- [DDF-91](https://jira.cdisc.org/browse/DDF-91)
- [DDF-241](https://jira.cdisc.org/browse/DDF-241)

What we need first is a sketch / draft design before we do anything else.

**Comment by dih-cdisc** [comment]
What we require is 

1. Ability to write structured text, i.e. blah blah blah [parameter] blah blah blah [parameter]. More [parameter]
2. Multi sentence, multi paragraph
3. Do we need bullited?
4. parameters can be of various types, see examples attached
5. Covering Inclusion / Exclusion criteria, objectives, endpoints and may be others, so we need something generic

Rationale
![Screenshot 2022-12-15 at 09 32 24](https://user-images.githubusercontent.com/115090009/207818993-c9daee30-1e67-41c3-aa8c-f35728945ce7.png)

Protocol Example
![Screenshot 2022-12-15 at 09 41 19](https://user-images.githubusercontent.com/115090009/207819026-97e59f0b-7507-4848-99ba-b12678709827.png)

Protoco Example
![Screenshot 2022-12-15 at 09 42 08](https://user-images.githubusercontent.com/115090009/207819104-37c03849-a9a3-4b89-adb4-f46c8322e067.png)

Protocol Example
![Screenshot 2022-12-15 at 09 43 02](https://user-images.githubusercontent.com/115090009/207819148-ae428687-72fa-4b29-adb3-8da9cde9a1fd.png)

**Comment by ggasg** [comment]
@dih-cdisc @cupkes This is what we have so far as proposed design for Syntax Templates:
<img width="595" alt="Screen Shot 2023-01-09 at 23 34 49" src="https://user-images.githubusercontent.com/8659660/211463051-daaaca11-16cd-4294-8f6c-6093b5edd157.png">

Applications will leverage this model by obtaining first a pre-defined **syntaxTemplateText** with markers that denote the usage of model items (e.g. something like _CDM: Endpoint_) that are expected to be loaded dynamically. As the user populates the Template Text with specific terms, the Application prepares a **Dictionary** with all the model types and elements used in the text. This model will then produce a complete "non-template" text by  replacing all markers with meaningful fields for each element (e.g. an _Endpoint Name_ each time the _CDM: Endpoint_ marker is found). From a model point of view this looks simple enough and it supports the workflow of parsing the template, saving it to a repository and de-serializing it, but the mechanics behind it can get very complex if we're looking to build something that can parse any elements from the model.
@dih-cdisc  Please do let us know your comments. This design is still ongoing, Chris and I will continue refining it but I'd like to make sure this is on track per requirements.
A "preview" of what the code would look like can be found [here](https://github.com/cupkes/DDF-conformance/commit/08cf4e69d64107c4f45536d760bb205c4ede6ce1).

**Comment by ggasg** [comment]
See below for a sample scenario using the Syntax Template:

1. The Application (Open Study Builder, for example) defines a string that is a pre-approved template for a description field in the model. Say, for example, the Study Objective field.
2. This string will use a very specific format. All variables must be enclosed in brackets. For example, a Study Objective Template String would be: "_To compare the effect of [Compound] relative to [Comparator] on [ActivityInstance]_"
3. As the End User populates the Study Objective Field, the Application must enforce a mandatory population of the parameters enclosed in brackets with real values from the SDR. In other words, the user must pick real values for a Compound, a Comparator, and one Activity Instance.
4. Once the user finishes picking elements for each bracketed item in the string, the Application adds them to a list maintained by the model (Dictionary)
5. From now on, the Application is open to invoke a helper function (part of the CDISC model here) capable of producing the full text for a Study Objective, which in this case will be: _"To compare the effect of nph insulin relative to metformin on body weight"_ 

The above scenario has been coded and can be executed with [this Unit Test](https://github.com/cupkes/DDF-conformance/blob/gg_sprint6/src/test/java/org/CSDISC/DDF/tools/SyntaxTemplateTest.java).
The model provides with a means to persist the template definition and the elements used to compose a human readable text from a template.

@dih-cdisc @cupkes Let me know if there's any questions or comments.

**Comment by ggasg** [comment]
@dih-cdisc @cupkes here is an overview of the Database model that would be required the proposed Syntax Template Design:
<img width="689" alt="Screen Shot 2023-01-18 at 00 14 40" src="https://user-images.githubusercontent.com/8659660/213090194-17588bf9-9c5d-4c01-8f6a-7223513a4ff4.png">
Here JSON is proposed for the Dictionary Map but this is not a requirement. Applications are free to store the Map in their most convenient format.
Also, see below just for more information about the sample input and output we've been working with. This is the result of our unit test:
<img width="789" alt="Screen Shot 2023-01-18 at 00 15 28" src="https://user-images.githubusercontent.com/8659660/213090487-2f751cec-c0ec-43e9-99ac-9834cda17643.png">

**Comment by drewcdisc** [comment]
@dih-cdisc asked this question in an earlier comment:

Why do we need this (we should think about this)

    Reuse
    Search
    Impose style?


Is there more we need to know? Or did we get all these questions answered?
