### ISSUE TITLE
Add Exploratory to CT objectiveLevel [CT ONLY]

### ISSUE THREAD

**Issue by jowencdisc** [cdisc-org/DDF-RA#163]
Per ich-m11-technical-specification-step-2b_en.pdf (Section 3.1) there should be the ability to have an exploratory objective, this value is currently missing from the objectiveLevel ValueDomain (C188725)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @daveih: 
The exploratory objectivelevel is added. However, the synonyms and CDISC definition are considerably different from those of the primary level and secondary. See picture.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakhpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--73a4ff1ecb5873510b5c439a2f8569d80a8f7340/image.png)
I would keep it aligned. So add corresponding synonyms: Trial Exploratory Objective / Study Exploratory Objective
and change CDISC definition to: "An exploratory objective of the study"

The current CDISC definition that you added now is suggesting that the exploratory objective is the reason for performing the study. While in most cases it is just in addition to the reason to do it.

**Comment by EMuhlbradt** [comment]
Definition and synonyms updated in 2-4 branch
