### ISSUE TITLE
Add TS and M11 parameters to Study/StudyDesign classes

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#165]
See PBIs:
| Item  | Ticket |
| ------------- | ------------- |
| Model |  #250 |
| CT |  #249 |
| API | #251 |
| IG | #175  |
| Examples | #252  |

Add Study level TS parameters to USDM to inform SDTM TS creation.
The following FDA required TS Parameters are not yet covered:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGIxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2faf5b854362249339e0fd391066ae51446c45f4/image.png)

In addition, the following parameters will be suggested to add to TS based on M11 and are not yet covered either:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGoxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d88faac8cd17b3bf04cf5992b3b6d477222aac9e/image.png)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc : final proposed list based on current USDM version 2.7
For Study class
   - isExtentionTrial -> boolean
   - stopRules -> multiple possible
For StudyDesign class
   - isAdaptive -> Boolean
   - isRandomized -> Boolean
   - plannedTrialDuration => quantity
  
Others listed above are more or less covered by other classes and/or new attributes.

**Comment by dih-cdisc** [comment]
As discussed on daily call, the boolean flags, what distinguishes these features

1. isExtentionTrial -> boolean
2. isAdaptive -> Boolean
3. isRandomized -> Boolean

**Comment by BSnoeijerCD** [comment]
As discussed during todays scrum:
Instead of **isExtentiontial** add attributes for **extendedBy** and **extentionOf** with relationship to studyIdentifier class. 
Should this always be a sponsor ID? Or at least?

**Comment by dih-cdisc** [comment]
@BSnoeijerCD @czwickl @EMuhlbradt 

Radical thought re extension studies :)

A study and an extension study. Is that two study designs within a single study? If so, then a relationship "extends" from one design to the other?

**Comment by drewcdisc** [comment]
During a discussion: We want to propose to add an attribute to the studyDesign class. The name of the attribute is type, and possible example values are: "randomized", "extension", "adaptive"

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @gerrycampion @dih-cdisc 
As discussed during the Scrum today added attribute (relationship to code class) to data model called 'characteristics'. See UML below:
![StudyVersions](https://github.com/cdisc-org/DDF-RA/assets/138679324/062c7793-0004-4565-a047-8d7e7167625e)
