### ISSUE TITLE
Remove Class names from attributes

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#166]
During the first sprints we have removed class names from a number of standard attributes. This ticket is added to check all the remaining attributes that still include class names. For each of them we need to check whether the class name part can be removed while still keeping the right context. 

Child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #180 |
| CT |  #179 |
| API | #180 |
| IG | ??? |
| Examples | ??? |

**Comment by BSnoeijerCD** [comment]
During the first sprints we have removed class names from a number of standard attributes. This ticket is added to check all the remaining attributes that still include class names. For each of them we need to check whether the class name part can be removed while still keeping the right context.

**Comment by dih-cdisc** [comment]
A starting list, there may be more :) In <class name>: <attributes> form

IntercurrentEvent: intercurrentEventStrategy

Procedure: procedureType 
*** Note that the type might be better as 'category' ***

BiomedicalConceptSurrogate, bcSurrogateReference

BiomedicalConcept: bcSynonyms and bcReference

BiomedicalConceptProperty: bcPropertyRequired, bcPropertyEnabled, bcPropertyDataType

ResponseCode: responseCodeEnabled

Study: studyTitle, studyVersion, studyPhase, studyRationale, studyAcronym
*** We may wish to leave some or all of these, Study being a little more 'specific' ***

Encounter: encounterEnvironmentalSetting, encounterContactModes

Organization: organizationScheme, organizationIdentifier

StudyArm: studyArmDataOriginDescription

StudyDesign: studyDesignBliningScheme

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD Yes it should be corresponding. We'll need to fix that. Shall we do it with 2-5 branch?

**Comment by glow-mdsol** [comment]
think `studyType` needs to be added to this list to be updated in the CT (w.r.t. the value sets)

**Comment by czwickl** [comment]
The Excel file attached contains evaluation results for identifying possible name changes and current alignment between USDM_CT_2.5 and the latest UML model:

[DDF-RA 166_USDM_CT_2.5_Potential Name Changes and Alignment Check_2023-10-17.xlsx](https://github.com/cdisc-org/DDF-RA/files/12929872/DDF-RA.166_USDM_CT_2.5_Potential.Name.Changes.and.Alignment.Check_2023-10-17.xlsx)

**Comment by dih-cdisc** [comment]
@czwickl @EMuhlbradt @BSnoeijerCD 

Spreadsheet with my thoughts inserted. Note the comment column. I noted all "previousCLASSNAME" and "nextCLASSNAME" relationships are changed to "previous" and "next"

[DDF-RA.166_USDM_CT_2.5_Potential.Name.Changes.and.Alignment.Check_DIH.xlsx](https://github.com/cdisc-org/DDF-RA/files/13110824/DDF-RA.166_USDM_CT_2.5_Potential.Name.Changes.and.Alignment.Check_DIH.xlsx)

**Comment by BSnoeijerCD** [comment]
@daveih @czwickl @EMuhlbradt 
I added my comments: also suggested to remove class names from relationships to children
[DDF-RA.166_USDM_CT_2.5_Potential.Name.Changes.and.Alignment.Check_DIH_BS.xlsx](https://github.com/cdisc-org/DDF-RA/files/13112103/DDF-RA.166_USDM_CT_2.5_Potential.Name.Changes.and.Alignment.Check_DIH_BS.xlsx)

**Comment by dih-cdisc** [comment]
Looks good to go

**Comment by dih-cdisc** [comment]
Overview of name changes. Also includes the Intervention Dose and Administration changes
![DDF USDM Model Informative](https://github.com/cdisc-org/DDF-RA/assets/115090009/d86b00a5-180d-42e2-a925-ab4980f6c036)
