### ISSUE TITLE
Check Cardinality [Model]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#168]
Set of model cardinality settings that need checking and changes made if found to be wrong. Item numbers refer to the row numbers in column A of the attached spreadsheet.

See rows 74, 101, 106, 107,  129, 200
Final decisions: 
74: endpoint.endpointlevel: change cardinality to 1
101: encounter.encounterScheduledAtTiming: keep cardinality at 0..1 => No change
106: encounter.encounterType: change cardinality to 1
107: encounter.encounterEnvironmentalSetting: keep cardinality at 0..1 => No change
129: 
estimand.treatment: change cardinality to 1
estimand.variableofinterest: change cardinality to 1
200: scheduleTimeline.scheduleTimelineEntry: change cardinality to 1

[USDM_CT_Required.xlsx](https://github.com/cdisc-org/DDF-RA/files/12415471/USDM_CT_Required.xlsx)

**Comment by BSnoeijerCD** [comment]
OK. Last correction for EncounterEnvironmentalSetting made in UML
