### ISSUE TITLE
Remove Class names from attributes [Model + API]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#180]
See ticket #166

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @daveih 
I have posted the new UML and xmi files to the 2.6 branch. 
Three additional comments:
- The new name for  studyDesignBlindingScheme was indicated as blindingSchema. I kept the e. So blindingScheme
- I did not change studyTitle. As indicated by Dave this will be handled in a next ticket.
- I did not change procedureType as this was subject to discussion of a name change

![USDM_UML](https://github.com/cdisc-org/DDF-RA/assets/138679324/eb9d4d52-65e0-4e60-aace-3936b7f3a1b4)

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc @czwickl : 
For the StudyVersion class ->

1. Attribute 'studyVersion' on StudyVersion class should be changed to 'identifier'. Otherwise if we just change it to version, then the semantics would read 'Study Version Version' which doesn't make sense. What is really needed here is the actual version number/ID used to uniquely identify that version of the study. **We propose 'identifier' as the updated attribute name.**
2. Given the decision above to NOT change the attribute from 'studyTitle' to 'title', we'd also like to hold off on changing the attribute 'studyAcronym' to 'acronym'. The logic is the same and if we are going to make the change in future, we'd like to change these together. **We propose to NOT change 'studyAcronym' to 'acronym' in this sprint.**

**Comment by dih-cdisc** [comment]
> * The new name for  studyDesignBlindingScheme was indicated as blindingSchema. I kept the e. So blindingScheme
> * I did not change studyTitle. As indicated by Dave this will be handled in a next ticket.
> * I did not change procedureType as this was subject to discussion of a name change

- The new name for studyDesignBlindingScheme was indicated as blindingSchema. I kept the e. So blindingScheme <<< @EMuhlbradt your call I think :)
- I did not change studyTitle. As indicated by Dave this will be handled in a next ticket. <<< Probably wise for the moment, there is a ticket on this, deal with there?
I did not change procedureType as this was subject to discussion of a name change <<< "category" might be a better choice here. @EMuhlbradt @czwickl to decide

**Comment by dih-cdisc** [comment]
> @BSnoeijerCD @dih-cdisc @czwickl : For the StudyVersion class ->
> 
> 1. Attribute 'studyVersion' on StudyVersion class should be changed to 'identifier'. Otherwise if we just change it to version, then the semantics would read 'Study Version Version' which doesn't make sense. What is really needed here is the actual version number/ID used to uniquely identify that version of the study. **We propose 'identifier' as the updated attribute name.**
> 2. Given the decision above to NOT change the attribute from 'studyTitle' to 'title', we'd also like to hold off on changing the attribute 'studyAcronym' to 'acronym'. The logic is the same and if we are going to make the change in future, we'd like to change these together. **We propose to NOT change 'studyAcronym' to 'acronym' in this sprint.**

1. I get the logic. Identifier is not sitting comfortably with me, too overloaded. Could we go with "versionIdentifier"?
2. OK, good with that

**Comment by BSnoeijerCD** [comment]
> > @BSnoeijerCD @dih-cdisc @czwickl : For the StudyVersion class ->
> > 
> > 1. Attribute 'studyVersion' on StudyVersion class should be changed to 'identifier'. Otherwise if we just change it to version, then the semantics would read 'Study Version Version' which doesn't make sense. What is really needed here is the actual version number/ID used to uniquely identify that version of the study. **We propose 'identifier' as the updated attribute name.**
> > 2. Given the decision above to NOT change the attribute from 'studyTitle' to 'title', we'd also like to hold off on changing the attribute 'studyAcronym' to 'acronym'. The logic is the same and if we are going to make the change in future, we'd like to change these together. **We propose to NOT change 'studyAcronym' to 'acronym' in this sprint.**
> 
> 1. I get the logic. Identifier is not sitting comfortably with me, too overloaded. Could we go with "versionIdentifier"?
> 2. OK, good with that

1. What about Number? It is normally the number of the version? So then you would get: StudyVersion.number 
2. Point taken: I changed acronym back to studyAcronym in the UML. 
 
I will upload the newest clean UML (interim) version to the 2.6 branch now. Also to test the diff process.
