### ISSUE TITLE
Cohorts [CT]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#187]

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD 
[DDF.Terminology_Sprint.10.changes_2023-11-14pm.xlsx](https://github.com/cdisc-org/DDF-RA/files/13357047/DDF.Terminology_Sprint.10.changes_2023-11-14pm.xlsx)

Spreadsheet attached with Draft additions and changes to review for sprint 10 Cohorts issues.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc Specific comments/questions regarding the spreadsheet above:

1. We recommend changing the class name from 'Cohort' to 'StudyCohort'.
2. Consider changing relationship name from 'completionNumberOfParticipants' to 'plannedCompletionNumber' for 3 classes: StudyDesignPopulation; StudyCohort; PopulationDefinition
3. In the StudyArm class, we were asked to think up a better name for the relationship = 'cohorts'. We recommend 'studySubpopulation' instead.
4. We think a set of the relationships on the class PopulationDefinition actually need to be attributes -> plannedCompletionNumber; plannedEnrollmentNumber; plannedMinimumAge; plannedMaximumAge; plannedSex (note also the proposed relationship name updates). Most of these are trial summary parameter so we think they need to be defined as attributes somewhere.

**Comment by dih-cdisc** [comment]
> @BSnoeijerCD @dih-cdisc Specific comments/questions regarding the spreadsheet above:
> 
> 1. We recommend changing the class name from 'Cohort' to 'StudyCohort'.
> 2. Consider changing relationship name from 'completionNumberOfParticipants' to 'plannedCompletionNumber' for 3 classes: StudyDesignPopulation; StudyCohort; PopulationDefinition
> 3. In the StudyArm class, we were asked to think up a better name for the relationship = 'cohorts'. We recommend 'studySubpopulation' instead.
> 4. We think a set of the relationships on the class PopulationDefinition actually need to be attributes -> plannedCompletionNumber; plannedEnrollmentNumber; plannedMinimumAge; plannedMaximumAge; plannedSex (note also the proposed relationship name updates). Most of these are trial summary parameter so we think they need to be defined as attributes somewhere.

1. Agreed
2. Agreed, anything shorter is good :)
3. Happy with name, while thinking "relatedSubpopulation" came into my head??
4. Discuss on scrum call. Name changes are good, the relationship v attribute thing is not a conern but will discuss, the info is in there, it is more a modelling / implementation thing
5.

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD @czwickl - CT updates done on Github and pushed to 2-7-0 release branch. I await your QC.

**Comment by dih-cdisc** [comment]
@EMuhlbradt @czwickl @BSnoeijerCD 

Detected one issue through automated checks

1. IN CT, Row 377, column D "Unit" -> "unit"

Also, one alignment to be discussed

1. UML has "anticipatedValue" in Range class. I think this would be better named "approximation". Erin/Craig to decide. it is "this range is approximate". So we think we need 80-100 people to get our target population of 60. Remember that range is a generic "datatype" class, it is any range, not just population specific.

**Comment by BSnoeijerCD** [comment]
> @EMuhlbradt @czwickl @BSnoeijerCD
> 
> Detected one issue through automated checks
> 
> 1. In the CT, Row 377, column D "Unit" -> "unit"
> 
> Also, one alignment issue to be discussed
> 
> 1. UML has "anticipatedValue" in Range class. I think this would be better named "approximation". Erin/Craig to decide. it is "this range is approximate". So we think we need 80-100 people to get our target population of 60. Remember that range is a generic "datatype" class, it is any range, not just population specific.

@dih-cdisc : I misunderstood indeed. Is a range not in all cases an approximation? Should you not take a wider range if you like to include less or more then min and max?

**Comment by dih-cdisc** [comment]
> > @EMuhlbradt @czwickl @BSnoeijerCD
> > Detected one issue through automated checks
> > 
> > 1. In the CT, Row 377, column D "Unit" -> "unit"
> > 
> > Also, one alignment issue to be discussed
> > 
> > 1. UML has "anticipatedValue" in Range class. I think this would be better named "approximation". Erin/Craig to decide. it is "this range is approximate". So we think we need 80-100 people to get our target population of 60. Remember that range is a generic "datatype" class, it is any range, not just population specific.
> 
> @dih-cdisc : I misunderstood indeed. Is a range not in all cases an approximation? Should you not take a wider range if you like to include less or more then min and max?

I was thinking it is the difference between saying "we will select 60 to 80 people" to "we will select approximately 60-80 people". In the first case you should not select 59 or 81 in the second case you can. A hard or soft range. One is an instruction the other guidance. An age range for inclusion / exclusion would, I would hope, always be a hard range 18-60, no deviation.

**Comment by BSnoeijerCD** [comment]
> > > @EMuhlbradt @czwickl @BSnoeijerCD
> > > Detected one issue through automated checks
> > > 
> > > 1. In the CT, Row 377, column D "Unit" -> "unit"
> > > 
> > > Also, one alignment issue to be discussed
> > > 
> > > 1. UML has "anticipatedValue" in Range class. I think this would be better named "approximation". Erin/Craig to decide. it is "this range is approximate". So we think we need 80-100 people to get our target population of 60. Remember that range is a generic "datatype" class, it is any range, not just population specific.
> > 
> > 
> > @dih-cdisc : I misunderstood indeed. Is a range not in all cases an approximation? Should you not take a wider range if you like to include less or more then min and max?
> 
> I was thinking it is the difference between saying "we will select 60 to 80 people" to "we will select approximately 60-80 people". In the first case you should not select 59 or 81 in the second case you can. A hard or soft range. One is an instruction the other guidance. An age range for inclusion / exclusion would, I would hope, always be a hard range 18-60, no deviation.

ok. let's discuss then. Wondering, should plannedMinumumAge and plannedMaximumAge then not be combined to plannedAge with link to the new Range class instead of including both linking to Quantity class.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc 'Unit' to 'unit' issue fixed in 2-7 branch.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl : 
The indication of inheritance in the role column is in some cases not correct in both Excel files:
For PopulationDefinition: Nothing is inherited. This is the parent.
For StudyDesignPopulation: relationships plannedCompletionNumber and criteria are also inherited from PopulationDefinition

The entity and attribute name for plannedSex are not changed according to the changes in the Entities&Attributes sheet. Please adjust accordingly.

You added the inherited relationships now as well which is fine by me. However, to be consistent the following relationships should be added to other classes as well in the CT:
dictionary to: Objective, Endpoint, EligibilityCriteria

The relationships for ScheduledInstance are already added to ScheduledActivityInstance and ScheduledDecisionInstance. For other intherited items you no included (inherited from ... ) to the role description. Could you add that as well for the following items in ScheduledActivityInstance and ScheduledDecisionInstance:
- timelineExit
- timeline
- defaultCondition
- epoch
- timings
 
Similarly can you add (inherited from GeographicScope) to the attributes type and code in the entity SubjectEnrollment?

No other comments.
