### ISSUE TITLE
Cohorts [IG]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#188]

**Comment by BSnoeijerCD** [comment]
Outline:
-	Population and cohort definition
-	Link to eligibility criteria
-	StudyDesign population vs cohort
-	Additional cohort characteristics
Question: are we adding the picture below? We planned an overview for:	Population / indication / IE?
So I can add indication here. See also ticket #153 where I propose to link indication to population to align with standards.[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG5lQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94bbe0875e4b82c5e95e39d7961ef547ea2c088b/Population_cohort_5.png)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @jowencdisc 
Please review/adjust. See attachment. 
[IG Cohorts and Populations.docx](https://github.com/cdisc-org/DDF-RA/files/13450935/IG.Cohorts.and.Populations.docx)

**Comment by BSnoeijerCD** [comment]
@jowencdisc @dih-cdisc : Updated and added short description of Eligibility criteria as well in IG: https://wiki.cdisc.org/display/USDMIGv3/Populations%2C+Cohorts+and+Eligibility+Criteria
