### ISSUE TITLE
Requirements for USDM conformance

### ISSUE THREAD

**Issue by DianeWold** [cdisc-org/DDF-RA#192]
From the cardinalities in the UML diagram, it would seem that the only required items for a study are an ID and a name.  In developing rules, I would expect that more would be required for a complete, valid representation of a study. For starters, I would expect a Study to have an associated StudyProtocolDocument, at least one StudyProtocolDocumentVersion with an associated StudyVersion and for each StkudyVersion to have at least one StudyDesign.   As we're developing rules, would M11 be a good source for what's required to represent a study?

**Comment by drewcdisc** [comment]
@DianeWold From a discussion with @daveih this morning: Diane herself would probably be a better source of required cardinality for a finished study. The M11 is more document based, it is not providing full coverage.

**Comment by dih-cdisc** [comment]
This is the question, debated quite a few times on the project, about whether we should model the final study situation (must be a t least one arm, one epoch etc etc) or model for the partial build state. We will discuss further as we near the end of Phase 3. Currently the second approach is used.

**Comment by dih-cdisc** [comment]
Going to close this ticket and replace with [DDF-RA 216](https://github.com/cdisc-org/DDF-RA/issues/216) that is more focused on the changes we may need tomake

**Comment by dih-cdisc** [comment]
Going to close this ticket and replace with https://github.com/cdisc-org/DDF-RA/issues/216 that is more focused on the changes we may need tomake
