### ISSUE TITLE
Ordering of attributes in Data Dictionary

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/DDF-RA#193]
The ordering attributes within classes in [dataDictionary.MD](https://github.com/cdisc-org/DDF-RA/blob/main/Deliverables/UML/dataDictionary.MD) seems to be a bit random.  Would it be possible for the attributes to be listed in the same order that they're defined in the USDM model (e.g., usually with `id` as the first attribute)?

**Comment by gerrycampion** [comment]
@ASL-rmarshall mostly answered @dih-cdisc's  question already, but I can give more details:
“Can the Java utility be updated to reflect the UML ordering?”

Yes. Currently the Java generator uses an unordered HashMap to store the class properties. This could be changed to an insertion-order-sorted map implementation.

https://github.com/cdisc-org/usdm-dictionary-generator/blob/9abe7367ac19382e15b741fb5b18ed69fe623f3c/src/main/java/org/cdisc/tools/UsdmParser.java#L84

**Comment by gerrycampion** [comment]
Fixed with this commit:
https://github.com/cdisc-org/usdm-dictionary-generator/commit/9aebd48c231942f3f51ab2d9d5a9fccbd9910a2e
