### ISSUE TITLE
Distinguish definitions from references in the model

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/DDF-RA#194]
We have hit a hurdle when creating test data templates and generating sample data using the model. I don't see a way we can distinguish between definitions and references within the model.

For example, in this screenshot of the model, you can see that both StudyDesign and StudyCell have a list of studyElements.
![image](https://github.com/cdisc-org/DDF-RA/assets/85252124/1763c4ef-c903-41a7-a00a-77af41aa0612)

By the sample json, we can see that `StudyDesign.studyElements` points to a list of definitions, but `StudyCell.studyElement(Id)s` points to a list of references to `StudyDesign`'s definitions. How do we distinguish the two using the model?
![image (2)](https://github.com/cdisc-org/DDF-RA/assets/85252124/380fa4d8-3ad2-40cc-9930-04c23102a7c8) ![image (1)](https://github.com/cdisc-org/DDF-RA/assets/85252124/7f6c0915-b96e-4a60-bbed-8554d4ab5efe)

It would help to either have the "Id" qualifier in the relationship names or have some other indicator to distinguish between definitions and references.

**Comment by ASL-rmarshall** [comment]
One option might be to specify "Containment" for the target in the relationship:
![image](https://github.com/cdisc-org/DDF-RA/assets/113628824/5d823e04-d2c8-4db5-a942-637b0693a593)

**Comment by BSnoeijerCD** [comment]
Hi @ASL-rmarshall ,
Thank you for the comments. I will look into the containment part with the team.
Did you also check out the description in the IG with regards to referencing in the API? See https://wiki.cdisc.org/display/USDMIGv3/USDM+API

**Comment by dih-cdisc** [comment]
Email thread on this issue over the last few days

[API.pdf](https://github.com/cdisc-org/DDF-RA/files/13294606/API.pdf)

Remember, the CORE rules are checking the API JSON, not the model. There is a subtle difference between the two.

**Comment by ASL-rmarshall** [comment]
End (optimistically) of email thread:
[API2.pdf](https://github.com/cdisc-org/DDF-RA/files/13299250/API2.pdf)

It's the differences that make things tricky. We need something machine readable that can be interpreted to replicate (programmatically) what's been done in the API.

**Comment by gerrycampion** [comment]
I just realized that adding containment to the UML EA may not work. I can't find a counterexample in the current API quickly and I'm not sure if one exists right now or may exist in the future, but here is a general example:

Let's say we have:
- 4 classes: A, B, C, D.
- 2 relationships: AtoC, BtoC, CtoD

The relationships are as follow:
A -> AtoC -> C -> CtoD (val) -> D
B -> BtoC -> C -> CtoD (ref) -> D

The problem is with CtoD. Let's say the first CtoD relationship is a value and the second CtoD relationship is a reference. As you can see, class C will only have one relationship in EA, but whether it is value or reference depends on its parent.

**Comment by gerrycampion** [comment]
On second thought, I'm guessing this scenario doesn't happen. Otherwise, I would expect to see multiple instances of the same Class within the API schema.

**Comment by dih-cdisc** [comment]
The API schema defines once and uses cross references of the form ```"$ref": "#/components/schemas/Code"``` everywhere else to refer, this being a Code reference.

**Comment by gerrycampion** [comment]
Yeah, I didn't mean the schema's use of $ref. I meant there might be a scenario where we have ClassA.ClassC1.code and ClassB.ClassC2.codeId. But I don't see cases like this.

**Comment by dih-cdisc** [comment]
Updates to DD and CT should allow for the attribute names to be mapped from the API to the UML model and the use of "Id" and "Ids" suffix
