### ISSUE TITLE
Should study phase connect to StudyDesign rather than StudyVersion?

### ISSUE THREAD

**Issue by DianeWold** [cdisc-org/DDF-RA#197]
Some early phase protocols cover a series of successive study designs.  I believe that the different study designs in a protocol might have different phases, e.g., a combination of phases 1, 1/2, and 2.

**Comment by dih-cdisc** [comment]
@DianeWold going to put this in Jira. Will process as a public review comment, see [JIRA DDF-480](https://jira.cdisc.org/browse/DDF-480)
