### ISSUE TITLE
In UML document, why doesn't the StudyAmendmentReason have primaryReason and secondaryReason attributes?  It only has otherReason.

### ISSUE THREAD

**Issue by rbakercdisc1** [cdisc-org/DDF-RA#199]
In UML document, why doesn't the StudyAmendmentReason have primaryReason and secondaryReason attributes?  It only has otherReason.

It seems like it should have all three.

**Comment by dih-cdisc** [comment]
StudyAmendmentReason holds a single "reason". There are two relationships from  StudyAmendments, a 1:1 for the primary reason and a 1:0..M for the secondary reasons. So an amendment can be attached to 1 primary reason and many secondary reasons (can also not have a secondary. reason)

**Comment by BSnoeijerCD** [comment]
@rbakercdisc1 
As Dave indicates: the attributes are represented as relationships to the class. The class StudyAmendmentReason then has an attribute/relationship code that links to the corresponding M11 coding list. You can both include it for primaryReason as well as for secondaryReason. See picture below. In the CT you will also find these defined as relationships and code. 
If at least one reason must be given or if "other" is only possible for primary or secondary reason, then we probably need a rule for that in CORE.
<img width="251" alt="AmendmentReason_v2 6" src="https://github.com/cdisc-org/DDF-RA/assets/138679324/8326fe60-905d-453c-af16-fac8824d3439">
