### ISSUE TITLE
Therapeutic Areas

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#2]
Add the ability to associate a study with one or more Therapeutic Areas.  This will require updates to:

1. USDM
2. Model
3. API

**Comment by dih-cdisc** [comment]
This is a comment on an item

**Comment by dih-cdisc** [comment]
SME discussion 11th October 2022
[2022 10 11 Meeting.pptx](https://github.com/cdisc-org/DDF-RA/files/9806712/2022.10.11.Meeting.pptx)
[DDF_Therapeutic Area.docx](https://github.com/cdisc-org/DDF-RA/files/9806715/DDF_Therapeutic.Area.docx)
[Veronica_Vu_email.pdf](https://github.com/cdisc-org/DDF-RA/files/9806716/Veronica_Vu_email.pdf)

**Comment by dih-cdisc** [comment]
Model sketch with TA added

![2022 10 12 DDF model notes](https://user-images.githubusercontent.com/115090009/196342570-2c059061-5013-40cf-9651-0db419439161.png)

**Comment by dih-cdisc** [comment]
Updated sketch with the Business Therapeutic attribute rename "businessArea" -> "businessTherapeuticArea"
![2022 10 18 DDF model notes](https://user-images.githubusercontent.com/115090009/196428190-26912c3f-d8d7-4a0e-85b5-0123dd99ecbd.png)

**Comment by dih-cdisc** [comment]
therapeuticArea and businessTherapeuticArea need to be List<Code> not just a single <Code>

Please make sure that the UML is on a white background

**Comment by dih-cdisc** [comment]
Discussed with Chris and following the convention employed to date, update names to be therapeuticArea**s** and businessTherapeuticArea**s**

**Comment by jowencdisc** [comment]
@EMuhlbradt please see comment above
