### ISSUE TITLE
In the UML diagram, in the EligibilityCriteria, why is there an "identifier" and "id" attribute. Are they different?

### ISSUE THREAD

**Issue by rbakercdisc1** [cdisc-org/DDF-RA#200]
In the UML diagram, in the EligibilityCriteria, why is there an "identifier" and "id" attribute. Are they different?

**Comment by dih-cdisc** [comment]
Every class has an 'id' attribute to allow for an class instance to be identified. This is necessary for the API among other reasons. 

EligibilityCritieria needs an 'identifier' for the Inclusion or Exclusion statement. This will, typically, be the number you see in the protocol document when the IE are listed.
