### ISSUE TITLE
Model Name Changes

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#202]
After the name changes applied in 2.6 there are a few which now look out of place. Suggest the following changes

1. StudyDesign class, studyInterventions relationship -> interventions
2. StudyElement class, studyInterventions relationship -> interventions
3. Procedure class, studyInterventions relationship -> interventions
4. Encounter, encounterScheduledAtTiming realtionship -> scheduledAt

**Comment by EMuhlbradt** [comment]
My thoughts:
Items 1-3: I'd like for us to be careful about the distinction between Intervention and Study Intervention. If the relationship is conveying the generic meaning of intervention, then I am okay with the name change. But if the relationship is really about those interventions specifically used within the study, I'd like to keep the language as is.
Item 4: I like the proposed change.

@czwickl thoughts?

**Comment by czwickl** [comment]
I agree with you on both. We had an in-depth discussion of Intervention vs Study Intervention and determined that based on existing definitions, we are really talking about a study intervention, which is defined more specifically as one of the 'things' being studied and which you would normally see represented in a study arm.

**Comment by dih-cdisc** [comment]
@czwickl @EMuhlbradt @BSnoeijerCD Lets just go with change 4 then. 

API, CT, UML: Encounter, encounterScheduledAtTiming realtionship -> scheduledAt

**Comment by BSnoeijerCD** [comment]
@czwickl @EMuhlbradt @dih-cdisc : Updated UML, xmi and EA accordingly in 2.6 branch

**Comment by EMuhlbradt** [comment]
@dih-cdisc CT fix completed in github repo 2-6 branch
