### ISSUE TITLE
Deliverables Misalignment

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#203]
Automated cross checking of the UML, CT and API has thrown up some differences. They are detailed in the attached spread sheet with manual comments

[cross_check_errors.xlsx](https://github.com/cdisc-org/DDF-RA/files/13306638/cross_check_errors.xlsx)

**Comment by dih-cdisc** [comment]
Updated sheet with one error resolved

[cross_check_errors.xlsx](https://github.com/cdisc-org/DDF-RA/files/13306727/cross_check_errors.xlsx)

**Comment by BSnoeijerCD** [comment]
@czwickl @EMuhlbradt @dih-cdisc : Updated UML, xmi and EA accordingly in 2.6 branch

**Comment by EMuhlbradt** [comment]
@dih-cdisc CT fixes completed in github repo 2-6 branch

**Comment by dih-cdisc** [comment]
@EMuhlbradt @czwickl @BSnoeijerCD 

We caught all the fixes except one. Error in CT file

UML: Note the duration and dose relatinships from AgentAdministration

![Screenshot 2023-11-10 at 06 27 24](https://github.com/cdisc-org/DDF-RA/assets/115090009/53a7995f-077e-48d3-9d39-68885a5bcb49)

CT:

![Screenshot 2023-11-10 at 06 27 32](https://github.com/cdisc-org/DDF-RA/assets/115090009/b857ae01-01c2-406c-8c75-4d2ff4f3b258)

Rows 332 and 333 need to move to AgentAdministration

Error file extract

![Screenshot 2023-11-10 at 06 28 03](https://github.com/cdisc-org/DDF-RA/assets/115090009/70f6e1c5-0576-4d1a-96a2-ca6dc139f066)

**Comment by BSnoeijerCD** [comment]
It is correct in the USDM_CT_Changes.xlsx file. Only need to be changed in USDM_CT.xlsx
@EMuhlbradt and @czwickl: Could you also check the DDF valid value set tab in the USDM_CT.xlsx file? Name changes are not promoted there. Like encounterEnvironmentalSetting should have been changed.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc Final updates pushed to 2-6 branch as per comments above.
