### ISSUE TITLE
Timings for encounters

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/DDF-RA#204]
The M11 guidelines state that "Allowable windows should be stated for all visits".  We have interpreted this to indicate 3 conformance rules (2 that are visit-specific and 1 that is generic):
1. All visits must have associated timing (initially taken to mean "all instances of the `Encounter` class must have a `encounterScheduledAtTiming` relationship to an instance of the `Timing` class").
2. All visit timings must have a timing window (initially taken to mean "in all instances of the `Timing` class that are linked to an instance of an `Encounter` class via an `encounterScheduledAtTiming` relationship, `timingWindow` must be populated").
3. Timing windows must be fully defined (i.e., if any of `timingWindow`, `timingWindowLower` or `timingWindowUpper` is populated, then all three must be populated).
 
These rules seem to make sense looking at the model, but don't seem to align with either the API spec or the available test data:
- In the API spec, the link from `Encounter` to `Timing` is by identifier only (via `encounterScheduledAtTimingId`), which implies that encounters/visits can only use timings that have been defined for some sort of `ScheduledInstance` (the class that has been identified as the "natural parent" for timings in the API spec).
- In the available test data, `encounterScheduledAtTimingId` is never used. Again, this implies that encounter's don't have their own independent timings (i.e., you have to figure out encounter timings by following all the `scheduledActivityInstanceEncounter` relationships backwards from the encounter and looking at the timing associated with each of the instances of `ScheduledActivityInstance` that are associated with the encounter).

This is what I was expecting: encounters have their own timings defined via `encounterScheduledAtTiming` - because visits are scheduled. Timings for scheduled activities are then defined in one of two ways:
1. Scheduled activities that just "inherit" their timing from the visit/encounter ("this activity will take place at some point during the visit, but it doesn't matter when") do not have their own defined timing (the `scheduleInstanceTimings` relationship is not used). Instead, the `scheduledActivityInstanceEncounter` relationship is used to link the scheduled activity to an encounter that has timing defined.
2. Scheduled activities that have explicitly defined timing (e.g. "1 hour after dosing"), do have timing defined via `scheduleInstanceTimings`.  They may optionally also be associated with an encounter that has it's own timing defined ("this activity happened 1 hour after dosing, but it's also part of the visit that happened 14 days after randomization").
 
Is this right?  If not:
- How are encounters (meant to be) linked into a timeline?
- How can you determine a visit schedule (e.g., how would you use this information to populate VISITDY in the TV SDTM domain)?
- How would you apply conformance rule(s) for M11's "Allowable windows should be stated for all visits"?

**Comment by ASL-rmarshall** [comment]
Is an `Encounter` just a special kind (specialization) of `ScheduledActivityInstance`?

If it were:
- It could be included directly in a timeline
- It would be a `ScheduledActivityInstance` so the `encounter` relationship would be unnecessary.
- It would inherit the `activities` relationship from `ScheduledActivityInstance` so the link between activities and encounters would be more direct.
- It would inherit its relationship with `Timing`, so the `scheduledAt` relationship would be unnecessary.

I think an encounter is represented as a `PlannedActivity` in BRIDG.

**Comment by dih-cdisc** [comment]
Closing this issue after discussion on various scrum calls.
