### ISSUE TITLE
Possible name changes in model/API

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/DDF-RA#206]
See child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #277 |
| CT | #278 |
| API |  #279 |
| IG |  #280 |
| Examples |  #281 |

There are a couple of name changes that would making naming more consistent throughout the model and API spec:
- Change the entity/class name `EligibilityCriteria` to `EligibilityCriterion` in the model and API spec. Each instance of this class represents a single criterion, so giving it a name in the singular form would be consistent with naming of other classes (e.g., `StudyArm`, not `StudyArms`).
- Change the attribute name `childrenIds` to `childIds` in `StudyProtocolDocumentVersion-Input` and `StudyProtocolDocumentVersion-Output` in the API spec only.  This would align better with what seems to be the convention for assigning Id attribute names:
    - If the maximum cardinality is 1 (and the linking word is singular), just append "Id"
    - If the maximum cardinality is more than 1 (and the linking word is plural), change the linking word to singular and append "Ids"

    It would also be consistent with the current use of:
    - `bcCategoryChildIds` and not `bcCategoryChildrenIds` in `BiomedicalConceptCategory-Input` and `BiomedicalConceptCategory-Output`
    - `contentChildIds` and not `contentChildrenIds` in `NarrativeContent`

**Comment by ASL-rmarshall** [comment]
Looking in 2.6, I can see that `childrenIds` is now used consistently in:
- `BiomedicalConceptCategory-Input` / `BiomedicalConceptCategory-Output`
- `NarrativeContent`
- `StudyProtocolDocumentVersion-Input` / `StudyProtocolDocumentVersion-Output`

However, I still think `childIds` aligns better with the convention for assigning id link names.

**Comment by BSnoeijerCD** [comment]
Another possible name change: 
change treatment relationship in Estimand class to intervention

**Comment by BSnoeijerCD** [comment]
Changes;
EligibilityCriteria to EligibilityCriterion (model, API, CT, IG, Test data)
childrenIds to ChildIds in API
Estimand - Treatment relationship to Intervention relationship (model, API, CT, IG and Test data)

**Comment by BSnoeijerCD** [comment]
Uploaded changes in UML model in 2.9 branch
