### ISSUE TITLE
Terminology / Model naming discrepancies

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/DDF-RA#207]
The following table shows discrepancies in attribute/relationship names between the USDM_CT.xlsx file and the model (as represented in USDM_UML.xmi):

| Entity | CT Role | CT Name | UML Name | Action |
| ----- | ----- | ----- | ----- | ----- |
| ScheduledDecisionInstance | Entity | conditionAssignments | | Change CT Role to Attribute or Relationship |
| AliasCode | Relationship | standardCode | StandardCode | Change S to lower case in UML |
| AliasCode | Relationship | standardCodeAliases | StandardCodeAliases | Change first S to lower case in UML |
| BiomedicalConceptCategory | Relationship | bcCategoryMembers | bcCategoryMember | Add an s to the end in UML |
| ScheduledInstance | Relationship | scheduledInstanceTimeline | scheduleInstanceTimeline | Add a 'd' to 'schedule' in UML |
| ScheduledInstance | Relationship | scheduledInstanceTimings | scheduleInstanceTimings | Add a 'd' to 'schedule' in UML |
| ScheduledInstance | Relationship | scheduleTimelineExits | ScheduleTimelineExits | Change first S to lower case in UML |
| Timing | Attribute | timingRelativeToFrom | timimgRelativeToFrom | Change second 'm' to 'n' in UML |

**Comment by dih-cdisc** [comment]
See release 2.6. Note that some of these observations are now redundant due to name changes made in release 2.6

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : I have checked all names for 2.6 in UML. Names were corrected or changed according to CT name changes ticket. Please use that version to check the consistency now.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD Thanks. I've switched over to 2.6 now and have confirmed that I'm no longer seeing these (or any other) discrepancies.
