### ISSUE TITLE
Properties present in API, but not Model

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/DDF-RA#208]
There are a few properties that exist in the 2.6 API but do not exist in the model. I would like to get a better understanding of these properties, their relationships, and why they aren't modeled:
- `*.instanceType`
- `StudyDesign.biomedicalConcepts`
- `StudyDesign.bcCategories`
- `StudyDesign.bcSurrogates`
- `StudyDesign.dictionaries`

**Comment by BSnoeijerCD** [comment]
@gerrycampion, we have set some rules for the API in case the same instances of a class can be reused across the data model. 
See https://wiki.cdisc.org/display/USDMIGv3/USDM+API
Hope this helps.
