### ISSUE TITLE
Simple CPT Updates

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#21]
Assemble and make the updates based on the simple changes from the CPT top 100

**Comment by jowencdisc** [comment]
Erin and Craig to evaluate the list of 100 variables to determine what elements can be added in for this sprint

**Comment by EMuhlbradt** [comment]
Comment from Erin and Craig: We met yesterday and put together a short list of items from the eCPT that were not yet mapped to USDM model elements (as per Herve), had CDISC semantics already established in NCIt, and could be considered as attributes to existing classes. We have a few more rows to review but attached is the starter list of 10.
[eCPT low hanging fruit for sprint 4.xlsx](https://github.com/cdisc-org/DDF-RA/files/10113477/eCPT.low.hanging.fruit.for.sprint.4.xlsx)

**Comment by dih-cdisc** [comment]
@EMuhlbradt @czwickl  I suggest we share the list with Berber to get feedback. List looks good to start with. 

The one I have slight concerns about is the DMC. Would, in the long term, the USDM have details re the DMC and thus the existence, or lack thereof, those details be the "boolean" flag? ... and thus should we do this properly and do the DMC details????

**Comment by dih-cdisc** [comment]
Responses to Erin's spreadsheet

[eCPT.low.hanging.fruit.for.sprint.4_v2 + DIH.xlsx](https://github.com/cdisc-org/DDF-RA/files/10153422/eCPT.low.hanging.fruit.for.sprint.4_v2.%2B.DIH.xlsx)

**Comment by jowencdisc** [comment]
Identification done - will discuss at the SME meeting 6 Dec - these will then be split into 2-3 tickets for sprint 5.
