### ISSUE TITLE
Inconsistent capitalization of Boolean/boolean types

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/DDF-RA#212]
Lowercase example:
https://github.com/cdisc-org/DDF-RA/blob/0f93c12bcc16564939eb57b57d4b67d641caecc1/Deliverables/UML/dataDictionary.MD?plain=1#L8

Uppercase example:
https://github.com/cdisc-org/DDF-RA/blob/0f93c12bcc16564939eb57b57d4b67d641caecc1/Deliverables/UML/dataDictionary.MD?plain=1#L71

This can probably be fixed in the xmi

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD Here's the updated summary for 2.8:
|Data Type|Count|
|-----|-----|
|Boolean|17|
|Date|1|
|Float|26|
|Map|2|
|String|742|

No issues remaining. Thanks.
