### ISSUE TITLE
Quantity and Range consistency [Model, CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#213]
The following attributes are suggested for type/relationship quantity or range:
population.plannedMinimumAge + plannedMaximumAge => Range for plannedAge
subjectEnrollment.quantity => Quantity

**Comment by dih-cdisc** [comment]
@BSnoeijerCD Agree

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl : see proposed changes for the UML below:
plannedAge:
![Population_cohort](https://github.com/cdisc-org/DDF-RA/assets/138679324/05d1734b-a7c0-471b-8878-4083c0a78d17)
SubjectEnrollment.quantity:
![StudyVersions](https://github.com/cdisc-org/DDF-RA/assets/138679324/d031369f-0548-40dc-9aa2-65a3e8dec18a)

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD we need more specifics on what exactly should be changed or added to fulfill this ticket? Can the diagram be updated to show clearly all needed attributes and relationships for Quantity and Range classes? OR are there other changes needed on other classes? Help!

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @dih-cdisc 
- please add plannedAge to the class populationDefinition (as a relationship to Range class) and add it to StudyCohort and StudyDesignPopulation as well indicating that it is inherited from populationDefinition

- More general: with changing the quantity attribute to a relationship, the CDISC definition is removed. However, like code and aliasCode, quantity and Range are more data type kind of classes and thus this definition is of added value to the users as the class itself does not provide any information. As such it is defendable to keep/add the definitions in case of relationships to the classes: code, aliascode, quantity and range. This would affect only the descriptions of the following:
    - In class PopulationDefinition: plannedAge, plannedEnrollmentNumber, plannedCompletionNumber 
    - In class AdministrationDuration: quantity
    - In class AgentAdministration: dose
    - In class studyIntervention: minimumResponseDuration
    - In class subjectEnrollment: quantity

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc We have significant concerns over defining relationships:

1. There is the issue of granularity - do we define just the relationship 'quantity' or the combination of the Class and Relationship (e.g., AdministrationDuration.quantity)? If the latter this isn't that useful because we are missing the other end of the relationship (class A is being related to class B through a relationship -> E and F in the spreadsheet do not convey this fully because you are missing the other class on teh other side of the relationship). Craig does not feel that defining the relationship (i.e., 'quantity) by itself is useful but Erin disagrees.
2. Are relationships conveying values? Craig seems to think so but Erin is not so sure in all cases.
3. Why do we need define relationships at all? Shouldn't the UML diagram inherently do this? The CT deliverable as it stands right now doesn't fully convey the relationship anyway. This is going to be very confusing.

**Comment by EMuhlbradt** [comment]
[DDF.Terminology_Sprint.11.changes_2023-11-28.xlsx](https://github.com/cdisc-org/DDF-RA/files/13493162/DDF.Terminology_Sprint.11.changes_2023-11-28.xlsx)

**Comment by BSnoeijerCD** [comment]
> @BSnoeijerCD @dih-cdisc We have significant concerns over defining relationships:
> 
> 1. There is the issue of granularity - do we define just the relationship 'quantity' or the combination of the Class and Relationship (e.g., AdministrationDuration.quantity)? If the latter this isn't that useful because we are missing the other end of the relationship (class A is being related to class B through a relationship -> E and F in the spreadsheet do not convey this fully because you are missing the other class on teh other side of the relationship). Craig does not feel that defining the relationship (i.e., 'quantity) by itself is useful but Erin disagrees.
> 2. Are relationships conveying values? Craig seems to think so but Erin is not so sure in all cases.
> 3. Why do we need define relationships at all? Shouldn't the UML diagram inherently do this? The CT deliverable as it stands right now doesn't fully convey the relationship anyway. This is going to be very confusing.
> 4. There is also the issue that we have not really been refining relationship names so we have no idea if the given name of a relationship means, at face value, what the word means or is there additional meaning in the relationship name that just hasn't been refined.

The basic principle behind this, that for quantity and range "relationships" it should not be viewed as a relationship. But rather as an attribute with a specific data type. Like you already do for code and aliasCode types. Does that help?
Therefore we want the descriptions because those data type classes (code, aliasCode, quantity and range) are not specific in this.

**Comment by dih-cdisc** [comment]
@BSnoeijerCD @EMuhlbradt  Did we resolve this in our discussion at the daily call 29th November?
