### ISSUE TITLE
Study Intervention, 'codes' Attribute

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#215]
Check UML to see if the "codes" attribute in StudyIntervention should be 1:0..* or 1:1..*. Then align in API (currently 1:1). Align in "green blob" diagram

See [JIRA 481](https://jira.cdisc.org/browse/DDF-481)

**Comment by dih-cdisc** [comment]
- API updated to align with UML 1:0..*
- Green blob updated to 0..*

@BSnoeijerCD just need to consider if we should have at least one code or not

**Comment by BSnoeijerCD** [comment]
@dih-cdisc from experience, in case of a new drugs being tested, there are no or not many codes known and/or added in the design phase. 
Also, for future use, interventions could also be non-drug interventions which might not have a code at all.
So I would leave it to 0..* for now.

**Comment by dih-cdisc** [comment]
> @dih-cdisc from experience, in case of a new drugs being tested, there are no or not many codes known and/or added in the design phase. Also, for future use, interventions could also be non-drug interventions which might not have a code at all. So I would leave it to 0..* for now.

Good by me. API has been updated to align with UML, no other changes needed. Can be closed

**Comment by BSnoeijerCD** [comment]
Checked: included in 7.1 API.
Closed ticket.
