### ISSUE TITLE
Review and move study Titles [CT]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#217]
As the titles are more related to the whole study and not only to the document: consider moving them to Study or StudyVersion class.

Currently we have 4 different study titles in the StudyProtocolDocumentVersion class:
- briefTitle
- officialTitle
- publicTitle*
- scientificTitle**

It is not clear which title is the main one to use and it does not align with other standards.
CT.gov has the following titles:
- brief title
- official title
- acronym*

M11 knows the following titles:
- Protocol Full Title
- Title Acronym*

* Acronyms are often used for big studies as a short ref. Do we want to include? Maybe that is what the public title was referring to. 
** Scientific title was added in phase I to allow for additional titles to be specified in case a scientific publication was based on the study. However, that is done after the study is conducted and might not be in the scope of the study design/USDM.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl : See ticket #170 for the UML. The following changes are necessary from CT perspective:
- Remove following attributes from StudyProtocolDocumentVersion class:
    - briefTitle
    - officialTitle
    - publicTitle
    - scientificTitle
- Remove following attributes from studyVersion class:
    - studyTitle
    - studyAcronym
 - **add** new class called title with following attributes/relationships
    - text (attribute)
    - type (code)
 - **add** relationship to StudyVersion called: titles
 - create controlled terminology for title.type. Following suggested based on the above:
     - brief (ct.gov)
     - official (ct.gov)
     - public
     - scientific
     - study (or is this overlap with official?)
     - acronym
     - _check name alignment with M11_

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD two comments to the above:
1. @czwickl  and I think StudyTitle is a better choice for this class than simply  'Title'.
2. @czwickl and I think 'study' in the title type value set above is superfluous and unnecessary.

Otherwise we agree with the updates above and these are reflected in the attached spreadsheet.
[DDF.Terminology_Sprint.10.changes_2023-11-24.xlsx](https://github.com/cdisc-org/DDF-RA/files/13459884/DDF.Terminology_Sprint.10.changes_2023-11-24.xlsx)

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD The spreadsheet attached above also has proposed changes reflected from tickets 213, 214, and 114.

**Comment by dih-cdisc** [comment]
@EMuhlbradt @BSnoeijerCD 

In the above "add relationship to StudyVersion called: titles" ... should that be "add relationship **from** StudyVersion **to Title class** called: titles"

**Comment by BSnoeijerCD** [comment]
> @EMuhlbradt @BSnoeijerCD
> 
> In the above "add relationship to StudyVersion called: titles" ... should that be "add relationship **from** StudyVersion **to Title class** called: titles"?

Yes correct. I was describing it from the perspective of what information to add to what classes in the CT Excel. Could have been more clear on that indeed.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl : titles are not referred to as "descriptive name" in de CDISC definition. I fear that might be confusing. Can we just say "description" or maybe even just "title" ?
@dih-cdisc : Any thoughts?

**Comment by EMuhlbradt** [comment]
> > @EMuhlbradt @BSnoeijerCD
> > In the above "add relationship to StudyVersion called: titles" ... should that be "add relationship **from** StudyVersion **to Title class** called: titles"?
> 
> This is correctly represented in the Sprint10. changes excel file. I will update class name and relationship name in the UML to StudyTitle and studytitles respectively to align with that. @EMuhlbradt, @czwickl: does that mean you will not have a title type called Study? Before we had a separate studyTitle attribute next to all the other ones.

@BSnoeijerCD correct, Study Title is a not a type of a title since all of the titles in the list are in fact types of Study Titles. Its superfluous. The class attribute combination of StudyVersion.title conveys the old attribute studyTitle.
