### ISSUE TITLE
UML Cardinality Updates

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#219]
Resulting from test tool implementation the following changes are suggested:

1. SyntaxTemplate --[:dictionary]--> Dictionary 1:0..1 (May not need a dictionary)
1. Range--[:unit]-->Code 1:0..1 (May not need a unit, e.g. person count)
1. Quantity--[:unit]-->Code 1:0..1 (May not need a unit, e.g. person count)
1. PopulationDefinition--[plannedEnrollmentNumber]-->Range 1:0..1 (May not be needed in both StudyPopulation and Cohort classes, only one needs defining)
1. PopulationDefinition--[plannedCompletionNumber]-->Range 1:0..1 (May not be needed in both StudyPopulation and Cohort classes, only one needs defining)
1. PopulationDefinition--[plannedMaximumAge]-->Quantity 1:0..1 (May not be needed in both StudyPopulation and Cohort classes, only one needs defining)
1. PopulationDefinition--[plannedMinimumAge]-->Quantity 1:0..1 (May not be needed in both StudyPopulation and Cohort classes, only one needs defining)
2. GeographicScope--[code]-->AliasCode (not needed if type is Global)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc:
Changed and uploaded for 2.7.1
Changed in 2.8: will upload today after review CT and updates of potential changes.
