### ISSUE TITLE
Activity/Procedure/BC Conditional [CT]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#220]
See feature #105

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl: 1 minor review comment for the CT:
Relationship dictionary in the new Condition class is also inherited from SyntaxTemplate

**Comment by EMuhlbradt** [comment]
> @EMuhlbradt @czwickl: 1 minor review comment for the CT: Relationship dictionary in the new Condition class is also inherited from SyntaxTemplate

@BSnoeijerCD fixed
