### ISSUE TITLE
Align Model, API, CT

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/DDF-RA#225]
alignment file should show any discrepancies between Classes and Attributes within the 3 locations

**Comment by gerrycampion** [comment]
@daveih @EMuhlbradt @czwickl 

Check out generated file: https://github.com/cdisc-org/DDF-RA/blob/release-2-8-0/Deliverables/UML/alignment.csv

Looks like it still needs some tweaking for things like inheritance.

**Comment by BSnoeijerCD** [comment]
> @daveih @EMuhlbradt @czwickl
> 
> Check out generated file: https://github.com/cdisc-org/DDF-RA/blob/release-2-8-0/Deliverables/UML/alignment.csv
> 
> Looks like it still needs some tweaking for things like inheritance.

Apart from that the UML, CT and API are in different stages of development which caused some issues, I think that the inherited classes are not shown as separate entities in the API but only by the classes inheriting the items. @dih-cdisc: am I right that you do not show them separately in the API in those cases?
