### ISSUE TITLE
Review And Move Study Title

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#229]
Currently we have 4 different study titles in the StudyProtocolDocumentVersion class:

briefTitle
officialTitle
publicTitle
scientificTitle

Need to rationalise

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #170 |
| CT |  #217 |
| API | #224 |
| IG |   |
| Examples |   |

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @gerrycampion @EMuhlbradt @czwickl:  As discussed in todays scrum. Renamed relationship from studeVersion to studyTitle class to "titles":
![Identifiers](https://github.com/cdisc-org/DDF-RA/assets/138679324/6ae93481-434b-46bf-9d0a-443c00cf56f2)
