### ISSUE TITLE
Change trial Phase to Alias Code

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#23]
Change trial phase from Code to AliasCode and assemble examples of other CTs (e.g. M11)

**Comment by ggasg** [comment]
Hi @dih-cdisc @cupkes, this ticket states a "trial Phase" attribute that is changing from "Code" to "Alias Code". I could not find a "trial Phase" attribute as such anywhere in the model but I did find "studyPhase" in "Study". Is that the one we're changing here? If so, are we keeping the original name or also renaming it to something like "trialPhase"?

**Comment by jowencdisc** [comment]
@daveih - there was also another question raised during the daily call from @czwickl 
Would the reference be changed from
![image](https://user-images.githubusercontent.com/106146515/204542535-4417ad3e-7a00-44b8-859e-5c13c4c56f3a.png)
to 
studyPhase (C48281): **aliasCode** (C66737, TPHASE)
