### ISSUE TITLE
Single & Multi Center Studies [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#233]
See feature ticket #39

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt and @czwickl : 
There are two corrections needed for this in the CT:
 - The type attribute in ResearchOrganization is a Complex Datatype Relationship
 - The relationship "manages" should have been added to ResearchOrganization, not to StudySite

**Comment by EMuhlbradt** [comment]
> @EMuhlbradt and @czwickl : There are two corrections needed for this in the CT:
> 
> * The type attribute in ResearchOrganization is a Complex Datatype Relationship
> * The relationship "manages" should have been added to ResearchOrganization, not to StudySite

@BSnoeijerCD fixed

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl :
I missed this one before: as we removed the OversightComittee for now. The relationship oversees should also be removed from StudySite.
Other two issues are resolved.

**Comment by EMuhlbradt** [comment]
> @EMuhlbradt @czwickl : I missed this one before: as we removed the OversightComittee for now. The relationship oversees should also be removed from StudySite class. Other two issues are resolved.

@BSnoeijerCD fixed
