### ISSUE TITLE
Single & Multi Center Studies [API]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#235]
See ticket #39

**Comment by dih-cdisc** [comment]
Read https://wiki.cdisc.org/display/USDMIGv3/USDM+API and note the API notations on the changes diagram

![DDF USDM Model Informative](https://github.com/cdisc-org/DDF-RA/assets/115090009/9c7ceeb6-b3e2-43c2-90d9-57ba6e86cefc)
