### ISSUE TITLE
Handling of 'Other' in USDM

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#243]
M11 allows for the 'Other' option in multiple occasions.
In the USDM data model we want to handle this 'Other' option in a flexible and consistent way. 

This ticket includes the review of the USDM data model in the light of the latest M11 version and making necessary changes to align with that and to consistently handle it within the data model.

**Comment by BSnoeijerCD** [comment]
Identify where M11 allows for Other. Define how to handle this in USDM and use this consistently for future cases.
What are the options of handling this?

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl: please review and correct if necessary
As discussed during todays scrum we like to propose the following to the PO:
Other should be handled by allowing extensible codelists. In case of 'other', the vendor system can facilitate this option and the specific entry can then be handled as an extension to the standard codelist. 

M11 codelists are mirrored by USDM. That means they do not have to be exactly equal. In case Other exists in the M11 codelist then we make the USDM codelist extensible allowing the user to add their own 'other' reasons. 

In a future update of the CT we can indicate for each referenced codelist, whether it is extensible or not.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc [USDM use of Other.docx](https://github.com/cdisc-org/DDF-RA/files/13920065/USDM.use.of.Other.docx)

**Comment by EMuhlbradt** [comment]
Codelist Extensibility was added to all DDF codelists, especially for the M11 harmonized codelists that contain 'other'. These codelists will remain extensible so that the user can use additional values not found in the codelist. This information is included in release 3-5-0 and will be published in the 2024-09-27 DDF publication from the NCI Thesaurus.
