### ISSUE TITLE
Add SDTM TS and M11 parameters to population and indication classes [API]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#247]
See feature ticket #153:
Add flag to PopulationDefinition. This will be inherited by studyCohort and StudyDesignPopulation.
includesHealthySubjects

Add flag to indication: isRareDisease -> boolean

**Comment by dih-cdisc** [comment]
It took me a few minutes to work out what was being asked for. Just for clarity @BSnoeijerCD @EMuhlbradt @czwickl I think the changes are:

- Class **PopulationDefinition**: Add attribute _'includesHealthySubjects'_ of type Boolean
- Class i**ndication**: Add attribute _'isRareDisease'_ of type Boolean

NOTE: Class PopulationDefinition is inherited by studyCohort and StudyDesignPopulation
