### ISSUE TITLE
Add SDTM TS and M11 parameters to population and indication classes [Test Data]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#248]
See feature ticket #153:
Add flag to PopulationDefinition. This will be inherited by studyCohort and StudyDesignPopulation.
includesHealthySubjects

Add flag to indication: isRareDisease -> boolean

**Comment by dih-cdisc** [comment]
Changes are:

- Class **PopulationDefinition**: Add attribute _'includesHealthySubjects'_ of type Boolean
- Class i**ndication**: Add attribute _'isRareDisease'_ of type Boolean

NOTE: Class PopulationDefinition is inherited by studyCohort and StudyDesignPopulation
