### ISSUE TITLE
Add Oversight committee

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#253]
Ad discussed during the meetings. Oversight committee is not by definition an organization.
Can we align with M11 terminology?

Data monitoring committee Yes/No is an item in the CPT. Do we want to add something like this?

**Comment by BSnoeijerCD** [comment]
Ad discussed during the meetings. Oversight committee is not by definition an organization.
Can we align with M11 terminology?

**Comment by dih-cdisc** [comment]
See #293

**Comment by BSnoeijerCD** [comment]
This ticket is currently handled in #293. So can be closed.
