### ISSUE TITLE
Update CT codelists [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#254]
Update CT codelists:
- Remove copies of SDTM terminology
- Add codelists aligning with M11

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc [M11 Codelists in DDF USDM.xlsx](https://github.com/cdisc-org/DDF-RA/files/13652652/M11.Codelists.in.DDF.USDM.xlsx)

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc @czwickl Four new codelists that mimic M11 codelists added to the CT deliverables in Github. FYI I also changed the information in the codelist reference column to reflect the fact that there will be four new DDF codelists.

CT Deliverables in github are ready for QC.

**Comment by BSnoeijerCD** [comment]
Checked, definitions correspond to codes and all 4 codelists are added,
