### ISSUE TITLE
StudyType attribute name

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#257]
StudyType attribute name was changed to type when it was in the Study class. The addition 'Study' was not needed.
As the class name is changed to StudyVersion the context is changed and it looks now like the study Version type.
Therefore, to avoid confusion, it is proposed to move the attribute name back to StudyType.

See child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #282 |
| CT | #283 |
| API |  #284 |
| IG |  NA |
| Examples |  #285 |

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt and @czwickl : Do you agree to change the attribute name back to StudyType to avoid confusion. Does this align with SDTM terminology?
If you agree I will split the ticket for the CT, API and Model

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc Based on the model, we think that the 'type' attribute hanging off of StudyVersion class should be renamed to 'studyType'.

**Comment by BSnoeijerCD** [comment]
> @BSnoeijerCD @dih-cdisc Based on the model, we think that the 'type' attribute hanging off of StudyVersion class should be renamed to 'studyType'.

Perfect. I will make the tickets for it and put it in the sprint backlog.
