### ISSUE TITLE
Additional elements to add

### ISSUE THREAD

**Issue by jowencdisc** [cdisc-org/DDF-RA#26]
TransCelerate have been reviuewing various protocols against the USDM model and have documented some missing elements that need to be added.

Refer to the following [XL sheet](https://transceleratebiopharma.sharepoint.com/:x:/r/harmonization/Digital%20Data%20Flow/Delivery%20Team/PUBLIC%20COLLABORATION/Collaborative%20Planning/R2%20Planning/Sprint%20Planning.xlsx?d=wc33832b8030a4a46a2c8b81406a14814&csf=1&web=1&e=976eGs) - refer to New Issue tab

This will need reviewing as some of the elements may already be in the model from previous sprints

**Comment by dih-cdisc** [comment]
NOT a backlog item, closed.
