### ISSUE TITLE
Specification of Syntax for Dictionaries

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#260]
The square bracket notation will cause issues as characters will need escaping. FHIR uses XHTML to store free text allows for the embedding of tags. This approach has been used within NarrativeContent. We need to updgrade the dictionairies to align with NarrativeContent and specify the tags used.

**Comment by BSnoeijerCD** [comment]
Check https://wiki.cdisc.org/display/USDMIGv3/Syntax+Templates
and align with test data

**Comment by dih-cdisc** [comment]
The updated syntax is detailed within the attached powerpoint. This needs to be reflected in the IG.

[2024 02 15 Syntax Templates.pptx](https://github.com/cdisc-org/DDF-RA/files/14508610/2024.02.15.Syntax.Templates.pptx)
