### ISSUE TITLE
Definition of Maps

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#261]
Maps are used in two places within the model.  We need to specify exactly what these are. This could be achieved by using a complex data type (as per Range, Quantity)
See jira ticket [508](https://jira.cdisc.org/projects/DDF/issues/DDF-508) for ParameterMap

- ScheduledDecisionInstance
- SyntaxTemplateDictionary

Child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #327 |
| CT |  #328 |
| API | #329 |
| IG | #339 |
| Examples | #344 |

**Comment by dih-cdisc** [comment]
Diagrams as shown at daily scrum 12th March
[2024 03 12 Maps.pptx](https://github.com/cdisc-org/DDF-RA/files/14572366/2024.03.12.Maps.pptx)

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD : Craig and I are considering whether the 'target' relationship name should be something like 'conditionalTarget' instead. Target could be used/misused multiple ways so adding an adjective to it makes it more concise. It also fits in with the names of some of the new class elements. Thoughts?

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD : Are the ParameterMap.tag ParameterMap.reference attributes always related to HTML? Asked another way, are the semantics for those two attributes specifically for 'HTML tag' and 'HTML tag reference'?

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc : See proposed CT changes to support this ticket:
[DDF 261.xlsx](https://github.com/cdisc-org/DDF-RA/files/14617301/DDF.261.xlsx)

**Comment by dih-cdisc** [comment]
> @dih-cdisc @BSnoeijerCD : Are the ParameterMap.tag ParameterMap.reference attributes always related to HTML? Asked another way, are the semantics for those two attributes specifically for 'HTML tag' and 'HTML tag reference'?

- tag is just a string name/identifier
- reference is XHTML formatted

**Comment by dih-cdisc** [comment]
> @dih-cdisc @BSnoeijerCD : Craig and I are considering whether the 'target' relationship name should be something like 'conditionalTarget' instead. Target could be used/misused multiple ways so adding an adjective to it makes it more concise. It also fits in with the names of some of the new class elements. Thoughts?

The two attributes are bound within the class of ConditionAssignment so they have context. They are a "name/value" pair, a key and value. This condition, go here ... so [condition, target] or [condition, conditionTarget] or [condition, destination] or [condition, assignment] .. don't make it too complicated

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @dih-cdisc 
Summarizing the above and for maintaining the consistency with the rest of the model, it is better to keep it to condition and target.
They are both within the ConditionAssignment context. So that means they are the condition of the ConditionAssignment and the target of the ConditionAssignment. 
If target is too vague then conditionTarget is the most clear term as it directly indicates what the target is when the condition is met. ConditionalTarget is less clear.
