### ISSUE TITLE
Site Relationship

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#262]
Remove relationship from StudyDesign to Site. Make the relationship go from StudyDesign to ResearchOrganization.

Child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #268 |
| CT | #267  |
| API |  #269 |
| IG |  #270 |
| Examples |  #271 |

**Comment by gerrycampion** [comment]
@BSnoeijerCD @dih-cdisc,
Where should the StudySite definitions go instead? Now we will have Research Organization with manageIds references that are missing definitions.

**Comment by BSnoeijerCD** [comment]
@gerrycampion 
StudySites can be directly go under ResearchOrganization. So you do not need a cross reference anymore and manageIds should be changed to manages like in the UML.

**Comment by gerrycampion** [comment]
Updated
