### ISSUE TITLE
Timing Relationship

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#263]
Move relationship "timings" from ScheduledInstance to ScheduleTimeline. This will make a collection of Timing instances for each timeline, more logical.

See child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #272 |
| CT | #273 |
| API |  #274 |
| IG |  #275 |
| Examples |  #276 |

**Comment by BSnoeijerCD** [comment]
@daveih Agree. Potentially this increases flexibility and it is only a small change in the model.
For example: If an encounter has a more general timing "Day 1" compared to the scheduledInstance timings that could be "Day 1, before dosing", "Day 1 dosing" and "Day 1 after dosing". Then it can be covered with the change. Also the timings of the subtimelines can be put in the right order.

**Comment by BSnoeijerCD** [comment]
See changes in UML below. 
<img width="886" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHVXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b1a148c7de59a356cb00ceea75e499ded9632a4/Timeline.png" alt="Timeline.png" />
