### ISSUE TITLE
Sites & Organizations [CT]

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#264]
Observation from building test data

Original comment: 
May be better to make sites Organizations and allow Organizations to have "children" / "subsidiaries". That way Sites can have addresses and thus a geographic presence separate from the enrollment.

This ticket is now aiming at reviewing CT for organization type vs role type and to make it consistent and usable in relation to each other.
Using the types in relation to each other can then be explained in the IG.

See related ticket #492 for IG.

**Comment by BSnoeijerCD** [comment]
Additional actions for this ticket based on review of #293:
Review organization type versus study role.

Consider following organization types:
- Health care institute
- Laboratory
 
make clear distinction between organization types and roles:
- Role: contract Research organization  => contract research
- Organization type: Clinical Study Sponsor => Pharmaceutical company , .... , .... (all the organizations that can have the sponsor role)
- Is clinical Study Registry not part of Regulatory Agency?
@ASL-rmarshall : better to wait with organization.type vs studyRole.code rules until we discussed this for the next version.

**Comment by EMuhlbradt** [comment]
@dih-cdisc I can confirm that CT related content for this ticket was completed in sprint 8. This can be moved to done.

**Comment by EMuhlbradt** [comment]
@dih-cdisc Craig and I agree that this ticket can be closed.

**Comment by BSnoeijerCD** [comment]
@czwickl @EMuhlbradt :
Maybe the definition should also indicate plural for study definition document**s**. Note that we do not want duplicate versions of the same document referred. So that can remain singular.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt and @czwickl 
for some reason my first comment was not included above:
- Should clinical Study Sponsor still be an organization type? It is now covered by studyrole.code and we now also have a list of organization types that can have this role. Therefore I think the organization.type "Clinical Study Sponsor" should be removed.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt and @czwickl 
In addition to the previous comment: we both have a role and organization type with content 'Contract Research Organization'. Should the role not be 'Contract Research' instead?

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD @EMuhlbradt @czwickl 
I still see "Clinical Study Sponsor" in the Organization type terminology - shouldn't this be removed now that we're using StudyRole to identify the organization that's playing the role of sponsor?

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @ASL-rmarshall updates made in 3-8-0 as discussed on yesterday's scrum.

**Comment by BSnoeijerCD** [comment]
reviewed and moved to Done
