### ISSUE TITLE
CPT Updates for Study Class

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#27]
Add new attributes for:

CPT:StudyRationale  
USDM Attribute name: studyRationale
CPT:Acronym
USDM Attribute name: studyAcronym

For details see:
[Changes spreadsheet](https://github.com/cdisc-org/DDF-RA/files/10153422/eCPT.low.hanging.fruit.for.sprint.4_v2.%2B.DIH.xlsx)
Pay attention to the chosen attribute name in column 'S'

**Comment by jowencdisc** [comment]
**Erin/Craig** - Semantics done in sprint 4 - CT spreadsheet need updating
**Gaston** - what are the types
CPT:StudyRationale String?
CPT:Acronym - String?
Gaston to discuss with Chris about how the branches for sprint 5 are going to work.
**Jared**
Update API with new attribute

**Comment by EMuhlbradt** [comment]
CT development complete
