### ISSUE TITLE
CPT Updates for Organization Class

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#28]
Add attributes for:

- CPT:SponsorLegalAddress
- USDM Attribute Name: organizationLegalAddress

For details see:
[Changes spreadsheet](https://github.com/cdisc-org/DDF-RA/files/10153422/eCPT.low.hanging.fruit.for.sprint.4_v2.%2B.DIH.xlsx)
Pay attention to the chosen attribute name in column 'S'

**Comment by jowencdisc** [comment]
**Erin/Craig** - Need to work on Definition - CT spreadsheet need updating
Gaston - what are the types
organizationLegalAddress String - Dave asked to think about data type - 
**Gaston** to discuss with Chris about how the branches for sprint 5 are going to work.
**Jared**
Update API with new attribute

**Comment by ggasg** [comment]
This item is now in progress. organizationLegalAddress remains a single String until I hear otherwise. Unfortunately I could not find any usage of this kind of field anywhere in Novo Nordisk's code base.

**Comment by dih-cdisc** [comment]
For an address type/class this may provide guidance [FHIR address datatype](https://build.fhir.org/datatypes.html#Address)

**Comment by ggasg** [comment]
Ok @dih-cdisc thank you for the reference. If I understand correctly and we're looking to follow the FHIR address model, we'd have to implement the entities Address/Address Use/Address Type/Period. I'm not sure what kind of impact a change like this may have on the api and its consumers. I'll bring up this topic during standup tomorrow.
