### ISSUE TITLE
CPT Updates for Study Design Class

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#29]
Add attributes for:

- CPT:ScientificRationaleforStudyDesign
- USDM Attribute name: studyDesignRationale

For details see:
[Changes spreadsheet](https://github.com/cdisc-org/DDF-RA/files/10153422/eCPT.low.hanging.fruit.for.sprint.4_v2.%2B.DIH.xlsx)
Pay attention to the chosen attribute name in column 'S'

**Comment by jowencdisc** [comment]
**Erin/Craig** - compare glossary and CT definitions and  decide which one - CT spreadsheet need updating
**Gaston** - what are the types
CPT:ScientificRationaleforStudyDesign Srting
Gaston to discuss with Chris about how the branches for sprint 5 are going to work.
**Jared**
Update API with new attribute

**Comment by EMuhlbradt** [comment]
CT development complete
