### ISSUE TITLE
Allow for multiple options for environmental setting [API]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#291]
See master ticket #244
Based on footnote examples: alternative environmental settings might be allowed for a study. Like clinic and home (by telephone inquiry). The current USDM only allows for 1 environmental setting. Can we change that to 0..*?
This will also be helpful for decentralized trials.

**Comment by BSnoeijerCD** [comment]
@gerrycampion : With this change environmentalSetting has become required which was not intended. Could you change this to optional? 
(I see the ticket description was confusing regarding that - changed it there as well to 0..*.)

**Comment by gerrycampion** [comment]
@BSnoeijerCD  Updated
