### ISSUE TITLE
Reconsider/generalize USDM structure for organizations

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#293]
Organizations are now nested in identifier or inherited by ResearchOrganization. 
See also tickets #258 and #264

**Comment by BSnoeijerCD** [comment]
We now have the following issues:
- Based on #258 - organizationType is inherited from organization class. This is not research organization type. Despite the name change it still can be regarded as such if in the researchOrganization class. Also, this might overlap with an instance type.
- Sponsor organizations are defined in the protocol with corresponding contact details. This information is now nested in the identifier class (in case of a sponsor organization).
- In case we have multiple identifiers from the same organization, we will have a repeat of organization information (can happen but not often)
- An organization can be of multiple types. Or is the type then more a role?

Therefore I would propose the following:
- Link organizations directly to StudyVersion class with all the corresponding details. So it can be reused accross study designs
- Inherit or refer to an organization when and where needed elsewhere in the model.

**Comment by dih-cdisc** [comment]
Also want to link this with TMF needs. Organizations:
- data monitoring committees
- others?

**Comment by dih-cdisc** [comment]
See #253

**Comment by BSnoeijerCD** [comment]
Reviewed latest M11 draft with following informational organization options
Sponsor, Co-sponsor, Local Sponsor, Manufacturer, intervention sourcing, randomization sourcing, 
committees like independent data monitoring, dose escalation committee, data safety monitoring board.

I reviewed 5 different protocols with final dates between 2017 and 2023 with the following observations:
- committee naming varies
- investigators are directly identified in the protocol in investigator initiated studies and phase I/II studies 
Medical expert Contacts with 
- CROs and corresponding roles are mentioned
- Central Labs are mentioned in phase I/II studies
- Many different roles and names mentioned once like project manager, study drug manager, advisor, protocol chair, protocol approver
- Different contact points for sponsor with corresponding difference in address details like sponsor pharmacovigilence and customer service.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @dih-cdisc 
Please see below an overview of the proposed changes:
- Nest all organizations at the StudyVersion level with relationship organizations and delete corresponding organizations relationship from the studyDesign class.
- Add new studyPersonal class (or better name) to store information of study involved personal relevant in the study design phase.
- Move manages relationship from ResearchOrganizations class to Organizations class and delete the ResearchOrganization class. This allows a sponsor to also refer to its own clinics as sites (for example phase 1 units).
- delete the currentEnrollment relationship from the StudySite class and add a relationship location to the SubjectEnrollment class instead which points to the StudySite class.
- add more CT to the organizationType class to cover most of the organizations mentioned (see previous comment).
- discuss if we want to add notes attributes to the Organization, address and/or the new StudyPersonal class.
![Organizations_Ideation_v3](https://github.com/user-attachments/assets/6630e0f7-d9cd-4607-8ee0-f2d5832dc330)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl 
Please find below the updated picture based on our discussions today. I added the masking in the picture to see whether this might need to be linked.
![Organizations_Ideation_v4](https://github.com/user-attachments/assets/d70b4221-504e-4615-89c5-015ef4b05e8b)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @dih-cdisc @czwickl 
New update. I recreated the UML with changes discussed in the previous days. See below. To discuss tomorrow. Especially the naming of classes and relationships.
![Organizations - Annot2](https://github.com/user-attachments/assets/943d1a90-b2ed-45a4-84d6-773ac8bd64dd)

**Comment by dih-cdisc** [comment]
Responses

1. 'organizationType' -> 'type' relationship name agreed
2. Organization - manages -> StudySite, relationship name, 'manages' is good
3. Organization -> StudySite cardinality 0..* is good
4. SubjectEnrollment - location -> StudySite, 'location' relationship needs a better name, 'forSite' might be better. Erin & Craig can think about it
5. NamedIndividual, Erin & Craig to ponder

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD @dih-cdisc @EMuhlbradt @czwickl 
Minor comment: I'm not hugely keen on `manages` as the name for the 0..* relationship between `Organization` and `StudySite`. Our usual convention is to name relationships with a singular or plural noun that describes the target(s) for the relationship, but "manages" is a verb. In this case the "s" at the end of "manages" does not indicate multiple sites (if sites are referenced by id, this relationships would become `manageIds` in the API according to the usual convention).

I think something like `managedSites` would be better.

**Comment by BSnoeijerCD** [comment]
As discussed during scrum today:
- changed relationship from SubjectEnrollment to StudySite 'location' to **appliesTo** because based on M11 we anticipate the cohorts might be another item to which an enrollment can apply. We anticipate to make this update in the follow-up sprint with alignment to M11.
- changed relationship from Organization to StudySite from 'manages' to **managedSites** to be more specific and to include the indication that it is plural.
- Changed the class name "NamedIndividual" to **AssignedPerson** as it is an individual who is assigned for the specific study role. the corresponding relationship from StudyRole to AssignedPerson class is also changed to: **assignedPersons** which is plural because it can be more than 1.
See diagram below. To discuss for tomorrow: should we add more attributes to the AssignedPerson class? 
![Organizations - Annot3](https://github.com/user-attachments/assets/e1865883-b574-4758-9b96-111b9400beac)

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD @dih-cdisc The discussions at yesterday's (2024-09-04) scrum prompted some thoughts about the definition of `StudyEnrollment`.  Now that we've added the `appliesTo` relationship to `StudyEnrollment`, we've talked about adding something like "Site" (or maybe "Local"?) to the terminology for `GeograpicScope.type`. However, we chose "appliesTo" as the name of the new relationship in anticipation of the M11 need to define enrollments for cohorts (so that we can, in future, define an enrollment as applying to either a site or a cohort), and I was wondering what the `GeographicScope.type` value should be for a cohort-based enrollment.

At the moment, the model indicates that "`StudyEnrollment` **is a type of** `GeographicScope`" (because the relationship is a generalization relationship). However, it appears it might be more accurate to say that a study enrollment "has a scope" that can be defined geographically, according to site, or according to cohort.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc @ASL-rmarshall : Proposed new and changes for ticket 293 in teh attached: 
[DDF_293.xlsx](https://github.com/user-attachments/files/16895280/DDF_293.xlsx)

See row 17 in the 'new' tab for a question we had about an item name and whether we need to build a codelist
@czwickl

**Comment by dih-cdisc** [comment]
> @BSnoeijerCD @dih-cdisc The discussions at yesterday's (2024-09-04) scrum prompted some thoughts about the definition of `StudyEnrollment`. Now that we've added the `appliesTo` relationship to `StudyEnrollment`, we've talked about adding something like "Site" (or maybe "Local"?) to the terminology for `GeograpicScope.type`. However, we chose "appliesTo" as the name of the new relationship in anticipation of the M11 need to define enrollments for cohorts (so that we can, in future, define an enrollment as applying to either a site or a cohort), and I was wondering what the `GeographicScope.type` value should be for a cohort-based enrollment.
> 
> At the moment, the model indicates that "`StudyEnrollment` **is a type of** `GeographicScope`" (because the relationship is a generalization relationship). However, it appears it might be more accurate to say that a study enrollment "has a scope" that can be defined geographically, according to site, or according to cohort.

As discussed on scrum call of 5th Sept '24, adjust when we align with M11. probably "appliedTo" a site, some geographic scope or a cohort

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl 
As indicated in the Excel attached above we need the following roles
For M11: 
- Sponsor   (- do we need a separate one for Co-sponsor?)
- Manufacturer
- Local Sponsor
- Regulatory Agency (for the identifiers)
- Medical Expert
- Independent data monitoring committee
- Dose escalation committee
- Data safety Monitoring board

Other use cases from differential search:
- (principal) investigator
- Study Drug Manager
- Clinical trial Physician
- Project Manager
- CRO/ Sites
- CRO / data scientist/analysis
- Laboratory
- Pharmacovigilence

**Comment by ASL-rmarshall** [comment]
@dih-cdisc @BSnoeijerCD @EMuhlbradt @czwickl As agreed (see [comment](https://github.com/cdisc-org/DDF-RA/issues/293#issuecomment-2333207914) above), we're deferring reorganization of study enrollment scopes until M11 alignment. In the meantime, what should the `GeographicScope` `type` be for a `StudyEnrollment` that `appliesTo` a `StudySite`? A type is required and at the moment it can only be "Global", "Region", or "Country".

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : The coming release 3.6 is not a final version and this issue will be handled for the next release 3.7. So we do not have to define that specifically now. If someone want to test the interim model for now then we can leave it up to the user to decide. We should not make rules for this.
