### ISSUE TITLE
Objective level - should it be required instead of optional?

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#294]
Objective level is now optional. Should it not be required? - that is also consistent with endpoints which have a required level.

Child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #321 |
| CT |  Not required |
| API | #322 |
| IG | Not required |
| Examples | #323  |

**Comment by dih-cdisc** [comment]
Agree, we should do this change for v3
