### ISSUE TITLE
Phase 1 Bug Fixes

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#3]
A set of simple bug fixes noted after the conclusion of Phase 1

1. **StudyEpoch Class**: Add encounters relationship, 1 -> 0..*
2. **IntercurrentEvent Class**: strategy attribute rename to "intercurrentEventStrategy" and is of type String
3. **PointInTime Class:** remove from the model
4. **Encounter Class** Attributes "startRule" and "endRule" should be renames and prefixed with "transition", so "transitionStartRule", "transitionEndRule"
5. **Workflow Class**  Attribute "workflowId" renamed to "uuid"
6. **Estimand Class**  Attribute "variableOfInterest" type shoudl be Endpoint not Encounter

**Comment by dih-cdisc** [comment]
[A test file.docx](https://github.com/cdisc-org/DDF-RA/files/9800509/A.test.file.docx)

**Comment by dih-cdisc** [comment]
The USDM should align with the sketch model

![2022 09 10 DDF model notes](https://user-images.githubusercontent.com/115090009/196343604-2a0882fa-6322-4a8e-9b40-a955da4b7a6e.png)
