### ISSUE TITLE
CPT Updates for StudyDesignPopulation Class

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#30]
Add sttributes for:

- CPT:NumberofParticipants
- USDM Attribute Name: plannedNumberOfParticipants
- CPT:PlannedMaximumAgeofSubjects
- USDM Attribute Name: plannedMaximumAgeOfParticipants
- CPT:PlannedMinimumAgeofSubjects
- USDM Attribute Name: plannedMinimumAgeOfParticipants
- CPT:Sexofparticipants
- USDM Attribute Name: sexOfParticipants

For details see:
[Changes spreadsheet](https://github.com/cdisc-org/DDF-RA/files/10153422/eCPT.low.hanging.fruit.for.sprint.4_v2.%2B.DIH.xlsx)
Pay attention to the chosen attribute name in column 'S'

**Comment by jowencdisc** [comment]
**Erin/Craig** - Semantics done in sprint 4 apart from number of participants - CT spreadsheet need updating
**Gaston** - what are the types
CPT:NumberofParticipants - number??
CPT:PlannedMaximumAgeofSubjects - lump unit or split unit into separate attribute?  @dih-cdisc thoughts
CPT:PlannedMinimumAgeofSubjects- lump unit or split unit into separate attribute?  @dih-cdisc thoughts
CPT:Sexofparticipants cdisc codelist = C66732 SEXPOP
Gaston to discuss with Chris about how the branches for sprint 5 are going to work.
**Jared**
Update API with new attribute

**Comment by ggasg** [comment]
This ticket is now in progress but I'd need further clarification before I can close it. @daveih see John's message above where you're tagged. Also, I'm assuming sexOfParticipants is List<Code> @cupkes please correct me if necessary.

**Comment by dih-cdisc** [comment]
Age of Participants - use a quantity type, ie.e value and unit with a datatype / class approach. This is a good resource re datatypes and fields [FHIR datatypes](https://build.fhir.org/datatypes.html )
Sex of Participants - List of Code makes sense

**Comment by jowencdisc** [comment]
@daveih - I have added the comment from Berber below. Please confirm if this should be actioned.

**Comment from Berber 09DEC2022** - Can you make it PlannedNumberOfParticipants? The planning will in most cases be different from actual numbers. So it is good to make a clear distinction between the design (planned) and the actual data like you already do with min and max age. And to be consistent you might also want to consider PlannedSexOfParticipants.

@EMuhlbradt and @czwickl - Just tagging you so you are aware of this comment. Will await reply from Dave IF.

**Comment by EMuhlbradt** [comment]
CT development complete
