### ISSUE TITLE
Suggested semantic changes [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#302]
A number of Public review JIRA issues are related to semantic changes only. 
This PBI is to review the JIRA tickets and adjust CT accordingly.

- Switch of EligibilityCriterion.name and description: Ticket DDF-489: https://jira.cdisc.org/projects/DDF/issues/DDF-489
 - Different pattern for Organization.name: Ticket DDF-490: https://jira.cdisc.org/projects/DDF/issues/DDF-490
 - Different pattern for SyntaxTemplate.name: Ticket DDF-491: https://jira.cdisc.org/projects/DDF/issues/DDF-491
 - Definition of Disease/Condition Indication: Ticket DDF-501: https://jira.cdisc.org/projects/DDF/issues/DDF-501
 - Clarification of Sex of Participants: Ticket DDF-502: https://jira.cdisc.org/projects/DDF/issues/DDF-502
 - Narrative content Definition: Ticket DDF-505: https://jira.cdisc.org/projects/DDF/issues/DDF-505
 - Administration Duration Quantity: Ticket DDF-506: https://jira.cdisc.org/projects/DDF/issues/DDF-506

**Comment by EMuhlbradt** [comment]
All JIRAs dispositioned and set to Team Review.

**Comment by EMuhlbradt** [comment]
See attached file for proposed changes to the model attribute:

[DDF Sprint 14_302_JIRA ticket resolutions.xlsx](https://github.com/cdisc-org/DDF-RA/files/14524816/DDF.Sprint.14_302_JIRA.ticket.resolutions.xlsx)

**Comment by dih-cdisc** [comment]
I had a look through, looks good

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt and @czwickl 
Can we change 'product' in the indication entity definition to 'intervention' to make it more generalistic to non product interventions?

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD 
Agree to both updates above.

**Comment by BSnoeijerCD** [comment]
Checked all items in final CT spreadsheet. All aligned with previous proposals and/or other tickets.
