### ISSUE TITLE
Abbreviations, should these be handled

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#308]
Do we need to handle abbreviations. Currently we can place these in NarrativeContent without issue but we see repeated definitions. A lot of them will be common across protocols.

Child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #422 |
| CT |  #424 |
| API | #423 |
| Rules | #426 |
| IG | #425 |
| Test Data | #424 |

**Comment by dih-cdisc** [comment]
Some examples, all from the same protocol
- ![Screenshot 2024-04-30 at 06 19 31](https://github.com/cdisc-org/DDF-RA/assets/115090009/77493816-e92f-4f55-97de-3529e9f4d059)
- 
![Screenshot 2024-04-30 at 06 19 43](https://github.com/cdisc-org/DDF-RA/assets/115090009/ea26ae22-f2b5-4376-a2d2-74fd0c8052fb)
-
![Screenshot 2024-04-30 at 06 20 00](https://github.com/cdisc-org/DDF-RA/assets/115090009/bdb9cb3f-b05f-4eb3-88ad-59d15325f62e)
-
![Screenshot 2024-04-30 at 06 20 06](https://github.com/cdisc-org/DDF-RA/assets/115090009/34a05467-d0dd-4526-ba66-f955e46c5003)
-
![Screenshot 2024-04-30 at 06 20 27](https://github.com/cdisc-org/DDF-RA/assets/115090009/d25d68c3-18a9-40e7-8eb0-8b866f0c2c49)

**Comment by dih-cdisc** [comment]
They are name, label pairs, so like dictionary entries. Here the "tag" is visible whereas the tag is "hidden" in dictionaries.

**Comment by BSnoeijerCD** [comment]
As discussed with @dih-cdisc  last Monday: the first iteration of how abbreviations could be stored:
use cases:
- abbreviation tags can be reused throughout the document
- making sure all abbreviations tagged are included in the full list of abbreviations 
- an interactive implementation can show the description when a user hoovers over the abbreviation 
- shortlists of abbreviations can be shown below an (SoA) table automatically for all abbreviations used in this table.

UML proposal:
![Documents_Abbr](https://github.com/cdisc-org/DDF-RA/assets/138679324/40692c6b-fb76-4de0-ba64-b5c6e8f7c4da)

To discuss:
- link from studyDefinitionDocumentVersion? -> should be separate from the documentVersion as they can be reused across different documents. => so link to StudyVersion is more appropriate.
- is tag needed? -> We want to include it in NarrativeContentItem.text. HTML narrative content text includes actual variable references. No tags.
- attribute and reference names OK?

**Comment by BSnoeijerCD** [comment]
As discussed during scrum today
- classname = abbreviation
- attributes:
     - abbreviation
     - longName
     - notes (to allow for grouping and reference to codes etc) 
- relate class to StudyVersion; Abbreviations can also be tagged and used in for example eligibility criteria, conditions, objectives and endpoint.
     - note that the abbreviation and corresponding long name will then be a specific reference in the parameterMap class related to a specific syntaxTemplateDictionary. 
- reference to CDISC glossary will be added. though the model will not be limited to abbreviations in this glossary.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl 
Please see the model updates based on our discussions below for your review: 
![StudyVersions_ann](https://github.com/cdisc-org/DDF-RA/assets/138679324/abb8cd2b-35dd-41aa-a2d2-55a4869698ad)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl : model updates for abbreviations are now in the 4_5 branch.

For the IG we can show how this works in practice for narrative content text as well as syntax templates.
