### ISSUE TITLE
Ability to group activities

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#309]
Ability to group activities into higher level groupings, e.g. Chemistry, Urinalysis into Labs

Child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #360 |
| CT |  #361 |
| API | #357 |
| Rules | #402 |
| IG | #400 |
| Test Data | #401 |

**Comment by dih-cdisc** [comment]
Example of grouping within an SoA. Worth thinking about whether this is a "presentation" issue

![Screenshot 2024-04-29 at 14 46 34](https://github.com/cdisc-org/DDF-RA/assets/115090009/5a49890e-11b2-4f7c-bc74-250677461752)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @dih-cdisc @ASL-rmarshall 
Discussed during Scrum today: Add Children relationship to Activity class for this purpose.

**Comment by BSnoeijerCD** [comment]
See annotated change with new children relationship in UML below.<img width="813" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWxyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a12446dcbbdd9a410f484187f6e31f04e51862b/Activities_annotated.png" alt="Activities_annotated.png" />
