### ISSUE TITLE
CT needs exploratory objective

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#310]
Found an exploratory objective in a protocol, could not setup in USDM

See [JIRA 520](https://jira.cdisc.org/browse/DDF-520)

**Comment by EMuhlbradt** [comment]
We have confirmed that exploratory objective is in the DDF CT deliverable. However we will make some minor semantic tweaks to the 3 values in the Object Level response codelist for consistency.

1. Change PT of Study Primary Objective to Primary Objective and update definition to: The main scientific question(s) the study is designed to answer. [After ICH E8; ICH E6 6.3]
2. Change PT of Study Secondary Objective to Secondary Objective and update definition to: The supportive or ancillary scientific question(s) the study is designed to answer. [After ICH E8]
3. Change definition of Exploratory Objective to: Additional scientific question(s) within the study that enable further discovery research, beyond the primary and secondary objectives.

**Comment by BSnoeijerCD** [comment]
Looks good and is reflected in the Excel change overview of ticket #302

**Comment by BSnoeijerCD** [comment]
Checked final CT spreadsheet. Preferred terms are now consistent including exploratory Objective.
