### ISSUE TITLE
Minimum content in API

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#315]
Couple of tickets referring to content within the API and the minimum content and clarifying partcular entries. See 
- [JIRA 520](https://jira.cdisc.org/browse/DDF-520)
- [JIRA-499](https://jira.cdisc.org/browse/DDF-499)
- [JIRA-500](https://jira.cdisc.org/browse/DDF-500)

**Comment by dih-cdisc** [comment]
IG updated to include definition of minimum content

**Comment by BSnoeijerCD** [comment]
Reviewed. All of the mentioned items in JIRA tickets included in corresponding IG chapters.
