### ISSUE TITLE
Timing Value Label

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#330]
Add a human readable label for the value field within the Timing class, see [2024 03 12 Timing.pptx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDNTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d3c59aedee7ad204a0b5c456430bba3ac7a9d7a/2024%2003%2012%20Timing.pptx)

Child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #331 |
| CT |  #332 |
| API |  #333 |
| IG | ? |
| Examples | #343  |

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl 
Based on this, I created a new attribute in the Timing class called valueLabel. In this way it is directly clear that it is linked to the value attribute and cannot be confused with the label attribute.

**Comment by dih-cdisc** [comment]
@EMuhlbradt @czwickl @BSnoeijerCD  I would like to rename the attribute 'window' to 'windowLabel'. This is for consistency reasonsas we end up with two logical groupings

- 'value' for the timing value and 'valueLabel' for the value human readable label
- 'windowLower', 'windowUpper' for the window values and 'windowLabel' for the window human readable label

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc : Proposed CT changes in the excel file here:
[DDF-330.xlsx](https://github.com/cdisc-org/DDF-RA/files/14617266/DDF-330.xlsx)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl:
Can I suggest that we combine the old and new text for windowLabel. I think it should reflect that it is a label and on the other hand keep the information that we already had. So then it would be:
"The short descriptive designation for a time period, or other type of interval, during which a temporal event may be achieved, obtained, or observed."

I was also wondering where we should indicate that we expect an ISO formatted value for the value, windowLower and windowUpper attributes?
