### ISSUE TITLE
NarrativeContent Previous & Next

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#334]
Add previous and next attributes to allow ordering of NarrativeContent

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #335 |
| CT |  #336 |
| API |  #337 |
| IG | Not required |
| Examples | #345  |

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc please see attached the proposed changes to the CT deliverable for this ticket: 
[DDF 334.xlsx](https://github.com/cdisc-org/DDF-RA/files/14617399/DDF.334.xlsx)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl : looks good. No comments.
