### ISSUE TITLE
Check if IMP and NIMP semantics are switched [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#338]

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc : I have just confirmed that the IMP and NIMP definitions in the valid value sets tab of the 2-9 release CT deliverable are NOT switched around. However, we will be updating the semantics for IMP, specifically the NCI c-code will change from CNEW to C202579.
