### ISSUE TITLE
Definition of Maps [IG]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#339]
Maps are used in two places within the model.  We need to specify exactly what these are. This could be achieved by using a complex data type (as per Range, Quantity)

- ScheduledDecisionInstance
- SyntaxTemplateDictionary

See master ticket #261

**Comment by BSnoeijerCD** [comment]
@dih-cdisc: for conditionAssignment class. I only had to make slight modifications. See below altered text:
Descriptions of the decision and pointer are defined using the conditionAssignment class. This class includes 2 attributes: a description of a condition and the reference to the target instance of the scheduledActivityInstance class that it points to once this condition is met, for example: "not reached cycle 12 and fulfilling eligibility to enter next cycle","ScheduledActivityInstance_2".

**Comment by BSnoeijerCD** [comment]
@dih-cdisc : also updated syntax template IG accordingly: https://wiki.cdisc.org/display/USDMIGv3/Syntax+Templates

**Comment by EMuhlbradt** [comment]
> This class includes 2 attributes: a description of a condition and the reference to the target instance of the scheduledActivityInstance class that it points to once this condition is met, for example: "not reached cycle 12 and fulfilling eligibility to enter next cycle","ScheduledActivityInstance_2".

@BSnoeijerCD @dih-cdisc : Based on Berber's comments above, consider whether the 'target' relationship should be renamed to one of the following:
conditionalTarget
conditionalInstance
conditionalinstanceTarget
conditionaltargetInstance

**Comment by dih-cdisc** [comment]
> > This class includes 2 attributes: a description of a condition and the reference to the target instance of the scheduledActivityInstance class that it points to once this condition is met, for example: "not reached cycle 12 and fulfilling eligibility to enter next cycle","ScheduledActivityInstance_2".
> 
> @BSnoeijerCD @dih-cdisc : Based on Berber's comments above, consider whether the 'target' relationship should be renamed to one of the following: conditionalTarget conditionalInstance conditionalinstanceTarget conditionaltargetInstance

Lets not over think this, see https://github.com/cdisc-org/DDF-RA/issues/261#issuecomment-2002966743
