### ISSUE TITLE
Conditional v Optional

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#34]
We have used the word "optional" in a few places. Question was raised as to whether or not "conditional" is a better term. Revisit and check what is the best one to use.

**Comment by EMuhlbradt** [comment]
Craig/Erin: Optional and Conditional are distinct concepts and as such should not be used interchangeably. Conditional is rules based; if a condition is or is not met, that determines whether the action is done. Optional is more of a decision/judgement based action, which carries more subjectivity as to whether the action is done or not. A conditional scenario would require additional model elements to identify the conditions/rules under which a particular action is done. Another point to note is that within the context of a protocol, there would be more conditional activities vs optional. Our recommendation is that activities may be either conditional or optional and that, for completeness, both of these would be required to be in the model. But we shouldn't necessarily replace what has already been added. Consider the additional of model elements associated with 'Conditional' activities. Also confirm with the SMEs whether they actually intended for these model elements to be the conditional ones all along? We suspect that there are way less 'optional' activities than 'conditional' activities in the context of clinical research activities and as such the conditional activities are more important to model at this point.

We do consider that both are useful so think it is okay to keep both in the model.

**Comment by dih-cdisc** [comment]
Review with team. I think we may want to review changes made to Activity and Procedure

**Comment by cupkes** [comment]
So, then...are procedures and activities both optional and conditional or just ... conditional?
