### ISSUE TITLE
Change code to AliasCode for Route, Frequency and Unit [Examples]

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#346]

**Comment by daveih** [comment]
There are no enrollments in the two examples taken from protocols as those protocols dont contain the necessary source information. The example below is from one of the test tool test files and output showing a percentage enrollment figure

![Screenshot 2024-03-29 at 08 00 49](https://github.com/cdisc-org/DDF-RA/assets/7643649/9dc7b2e4-343f-4cd7-89d9-12d4ba93d4c1)
