### ISSUE TITLE
Change required Intervention Details [Examples]

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#347]
See JIRA ticket DDF-519: https://jira.cdisc.org/projects/DDF/issues/DDF-519
Change relationship from Intervention to AgentAdministration to 0..*
Change relationship from AgentAdministration to Quantity to 0..1

**Comment by dih-cdisc** [comment]
Some confusion. Description above not consistent with UML

![Screenshot 2024-03-13 at 15 22 05](https://github.com/cdisc-org/DDF-RA/assets/115090009/85522bf7-a6d8-4727-bee6-08ba9b3198f3)

**Comment by daveih** [comment]
Model ticket pdted to 

See JIRA ticket DDF-519: https://jira.cdisc.org/projects/DDF/issues/DDF-519
Change relationship from Intervention to AgentAdministration to 0..*
Change relationship from AdministrationDuration to Quantity to 0..1
