### ISSUE TITLE
Add definitions to Relationships (part 1) [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#352]
Add definitions to relationships and discuss whether C-codes are necessary for it.

This first section will complete the first 50 rows in the CT spreadsheet held by Erin & Craig.

**Comment by drewcdisc** [comment]
- How does Bridg do this? We should consider following their example.
-

**Comment by czwickl** [comment]
[DDF.Terminology_Sprint.1.changes_2024-05-09_cz.xlsx](https://github.com/cdisc-org/DDF-RA/files/15294272/DDF.Terminology_Sprint.1.changes_2024-05-09_cz.xlsx)

The first 50 terms (or those that say "ok" in column N) are ready for review.

**Comment by EMuhlbradt** [comment]
@daveih @BSnoeijerCD there was only one question within the first 50 rows of the spreadsheet that Craig will post. 
For the relationship 'studyIdentifierScope' that sits between the 'StudyIdentifier' class and the 'Organization' class, we have written the following definition: **A USDM data model relationship between the StudyIdentifier and Organization classes which provides the details associated with each organization that has assigned a study identifier.**

We think we have the definition correct however it makes us think that the relationship name is wrong, or at least not as clearly named as it should be. Should the relationship name be something more clear like studyIdentifierOrganizationInfo or studyIdOrganizationInfo?

**Comment by czwickl** [comment]
Revised definitions for the plural relationships (blue fill) - yellow fill have not been vetted with Erin yet, pink fill indicates some uncertainty.

[DDF.Terminology_Sprint.1.changes_2024-05-15_cz.xlsx](https://github.com/cdisc-org/DDF-RA/files/15334705/DDF.Terminology_Sprint.1.changes_2024-05-15_cz.xlsx)

**Comment by EMuhlbradt** [comment]
@daveih @BSnoeijerCD see ticket 356 for spreadsheet for review.
