### ISSUE TITLE
Estimands

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#355]
From an @BSnoeijerCD email (related to PHSE estimand paper)

Although we already cover the basics of the estimands we could consider how to further improve it in phase IV by for example:
- Making the analysis populations a sub of the study and/or cohort populations
- Allow reference to intercurrent event variables (either by syntax text templates or other references)  
- Allowing a link to a reference treatment (not in the paper or ICH E9R1 – but proposed by Diane as a logic -> a treatment of interest is often compared to a reference in the analysis)
 
| Item  | Ticket |
| ------------- | ------------- |
| Model |  #485 |
| CT |  #486 |
| API | #487 |
| Rules | #490 |
| IG | #489 |
| Test Data | #491  |

**Comment by BSnoeijerCD** [comment]
See link for overview article: https://onlinelibrary.wiley.com/doi/full/10.1002/pst.2395
This one also indicates the alternative treatment (reference). So a second relationship to intervention class for the reference is potentially needed.

**Comment by dih-cdisc** [comment]
Taken from #397  (now closed)

Based on the PHUSE CSS estimand meeting:

- There can be multiple estimands defined for a study
- An analysisPopulation can be reused for multiple estimands
- An IntercurrentEvent can be reused for multiple estimands. However, the way they are nested in the API means that they have to be repeated.

**Comment by dih-cdisc** [comment]
Link with #288

**Comment by BSnoeijerCD** [comment]
Estimand requirements the protocol template:
-	Describe any associated estimands => suggests more than 1 is allowed
-	precisely define each trial objective and refine each trial objective into a precise clinical question of interest by defining the associated estimand. For considerations on estimands, refer to ICH E9(R1). Ensure alignment with every other section of the protocol.
-	For trials intended to estimate a treatment effect or test a hypothesis related to a treatment effect, use the table to precisely describe the associated estimand(s).
o	Not required for other trials!!!
-	This includes specification of the population targeted by the clinical question, the treatment condition(s), the endpoint (or variable), the population-level summary, and each intercurrent event and the associated strategy for handling it.
-	Table of Estimand characteristics
o	Population
	Key characteristics such as demographic – age/sex and 
	Clinical characteristics like prior therapies, symptoms, severity, biomarker status etc.
o	Treatment
o	Endpoint
o	Population level summary
o	Intercurrent event, 
	description and 
	corresponding Strategy

**Comment by BSnoeijerCD** [comment]
Based on the above, I would like to consider the following changes:
- add referenceIntervention relationship
- add reference to StudyPopulation or Cohort class as it will be a subset of pts included in there
- consider renaming summaryMeasure to populationSummary or as an alternative allow for more summaryMeasures to be defined for an Estimand.
For the rest, I believe the model already suits the current needs quite well for documenting the estimand information needed as described above.
![Objectives_suggest](https://github.com/user-attachments/assets/5cd62b3f-f7c9-429d-9173-833a105b88a0)

**Comment by BSnoeijerCD** [comment]
Some examples of analysis population descriptions in a protocol: 
<img width="476" alt="Estimands_1" src="https://github.com/user-attachments/assets/16af9aaa-4ad6-499b-972f-b80044db56f2">
<img width="478" alt="Estimands_2" src="https://github.com/user-attachments/assets/afc1386b-8d7d-44df-bfd5-33b82bbb7b08">

Note that in this example study they do not directly refer to the different cohorts which were included in the study. However, for a specific estimand this would be needed. Also although the primary endpoint indicates the analysis should be done per cohort it is indicated as 1 endpoint although it includes multiple analyses (per cohort).

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD @dih-cdisc 
I've looked through the modelling and information about estimands (including the M11 Template/Tech Spec) and have the following thoughts:

- Given that estimands appear to be defined to describe how study objectives will be met/implemented, it seems strange that there is not a direct relationship from `Objective` to `Estimand`. Estimands seem to be more-or-less equivalent to endpoints - it's just that they include additional information to describe more precisely the handling of the endpoints. 
- I wonder if it would be better to use `SyntaxTemplate` for strategies:
    - I have seen examples that say "use strategy x for all intercurrent events", which implies that strategies may be defined/chosen outside the context of individual intercurrent events, and are then applied to the appropriate intercurrent event(s).
    - In the M11 template/tech spec, the description for "<Enter Intercurrent Event 1 Strategy>" includes this: "cross reference the justification in Section 4 Trial Design". This implies that there might be a need to include links/references in the strategy definition, which would be easier using `SyntaxTemplate`.
- I think the intervention/treatment relationship(s) from `Estimand` might need to be tweaked:
    - At the moment, `intervention` and `referenceIntervention` link to `StudyIntervention`, but the M11 template says "including at least investigational agents, dosage, and administration route", and dosage and route are only available for `Administration`.  The cardinality for the `administrations` relationship between `StudyIntervention` and `Administration` implies that, if you have multiple dose levels for a study drug, you'd have a single `StudyIntervention` for the study drug and an `Administration` for each dose level.  Is that what's intended?  If so, it might be better for `Estimand` to link to `Administration` (instead of `StudyIntervention`) so that you can reference different dose levels. However, if you would define a different `StudyIntervention` for each dose level, then I think linking to `StudyIntervention` is OK. (The same question/thought would apply for the 'studyInterverntions` relationship between `StudyElement` and `StudyAdministration` because you'd want to be able to specify a dose level for a study element).
    - It might be better just to have a single 1..* `interventions` relationship from `Estimand` (or `treatments` - which aligns better with the term used for estimand definitions and, possibly, in relation to the question above about `StudyIntervention` vs `Administration`).
        - Although comparisons are made between treatments, neither the description of estimands nor the M11 template indicate that a particular treatment would be identified as the "reference treatment" - if you're evaluating a treatment effect, you just reference all the treatments being evaluated.
        - The cardinalities current indicate that you must have one intervention and may have up to two interventions (if you have a reference intervention). However, I think there can be more than 2 treatments referenced by an estimand   (e.g., if you have placebo and more than one dose level).

If any of these is too big a change, it could be considered for a future update.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall @dih-cdisc 
Please see my reply below

1. See [ICH E9R2](https://www.ema.europa.eu/en/documents/scientific-guideline/ich-e9-r1-addendum-estimands-and-sensitivity-analysis-clinical-trials-guideline-statistical-principles-clinical-trials-step-5_en.pdf) Estimands are a combination of endpoint, intervention, analysis population, intercurrent event and population summary. Therefore having them directly connected to the endpoint works and via that it is also connected to the corresponding objective.
2. Strategies are statistical strategies which are not likely to be covered elsewhere in the model. As such, I do not expect that syntax template is very much needed for that. However, if there is a need. We can always adapt in the future. The same holds for the reuse of strategies. We can discuss to make it a separate class though to reduce redundancy.
3. Reference intervention was indeed not mentioned in M11 but mentioned as a v3.0 review comment. As a statistician I would like to make the difference between what is the intervention of interest and what do I want to compare it with. So I would like to make the distinction between the main intervention of interest (meant by M11) and the reference. The reference could be more than 1 indeed if you have a statistical model including all options. So we can make that relationship plural. I kept it singular since there would be always 1 comparison of interest. However, it could be that you want to test the interventional treatment against the pooled group of other treatments.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall @EMuhlbradt @czwickl @dih-cdisc 
Please see updated model based on discussions during scrum today
-> Note that relationship referenceInterventions is removed again and intervention is changed to interventions
-> Please **add following studyIntervention.role :  "Active Comparator"**
<img width="658" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnBFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--baceb32c733647a4af485c1d89e13be34c7a6fc4/Objectives_Ann2.png" alt="Objectives_Ann2.png" />

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD, @ASL-rmarshall, @dih-cdisc:
@czwickl and I had a question about the relationship "subsetOf" coming off of the "AnalysisPopulation" class. We aren't sure exactly what was meant logically by this and came up with two possible definitions for the relationship:

Definition 1: A USDM relationship between the AnalysisPopulation and PopulationDefinition classes which identifies the subset of population definitions associated with the analysis population.

Definition 2: A USDM relationship between the AnalysisPopulation and PopulationDefinition classes which identifies the population definition associated with a subset of an analysis population.

Further explanation is needed and thoughts on which of the above definitions fits this best (or maybe a definition option 3 we hadn't thought of).

**Comment by EMuhlbradt** [comment]
slight update to definition 1: A USDM relationship between the AnalysisPopulation and PopulationDefinition classes which identifies the subset of a population definition associated with the analysis population.

**Comment by ASL-rmarshall** [comment]
A USDM relationship between the AnalysisPopulation and PopulationDefinition classes which identifies the population definition of which the analysis population is a subset.

**Comment by EMuhlbradt** [comment]
Like this? A USDM relationship between the AnalysisPopulation and PopulationDefinition classes which identifies the population definition for which the analysis population is a subset.
