### ISSUE TITLE
Add definitions to Relationships

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#356]
Add definitions to relationships and discuss whether C-codes are necessary for it.

**Comment by EMuhlbradt** [comment]
@daveih @BSnoeijerCD see the attached spreadsheet for review. All relationship definitions (drafts) have been created. 3 questions for you to address directly in column N.

[DDF.Terminology_Sprint.1.changes_2024-05-16.xlsx](https://github.com/cdisc-org/DDF-RA/files/15336180/DDF.Terminology_Sprint.1.changes_2024-05-16.xlsx)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl 
I started with the review today. Some questions:
- You indicate in the notes that 'provides' is a better choice for the blue terms. Yet you use 'identifies'. Did you decide differently then indicated in the notes? I also have a little trouble in understanding the provides term in the orange terms: for example 'an relationship that provides an address of an organization'. 
- Not sure whether you would say 'a set of narrative content' is correct. maybe 'narrative content items'?
- Relationship from studyProtocolDocumentVersion to datevalues is not accurately described. It can be a date of any type including the approval date.
- relationships studyIdentfierScope: this is the specific organization that is linked to the specific identifier. So the scope of the identifier is within that organization. Therefore it is scope in the name and not info. Can we express that specificity in the relationship definition as well? like: "which provides the details associated with **the** organization that has assigned **the** study identifier" 
 
I just made a start. But hope this already provides you some input. I will continue next week after Monday on the latest version available then.

**Comment by dih-cdisc** [comment]
@EMuhlbradt  @czwickl Comments in column added
[DDF.Terminology_Sprint.1.changes_2024-05-23 DIH.xlsx](https://github.com/cdisc-org/DDF-RA/files/15411899/DDF.Terminology_Sprint.1.changes_2024-05-23.DIH.xlsx)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl 

I reviewed your reactions. Here are my comments on the red ones:
- When you use the wording preceeds/follows for activities then it is perceived as an ordering in time. For activities it is not an ordering in time but an ordering in rows in the schedule of activities (what is presented in the row before/next). I also noticed in the past that this is not clear to users. Therefore it is important to be very precise here and mention this ordering of rows in the SoA table. 
- For eligibility criteria it is also not an ordering in time but a presentation ordering. This is implicitly more clear to users but I agree with Dave that it is clear to make a distinction between this presentation ordering (nr 1, 2, 3) and an ordering in time.
- scheduledActivityInstance and scheduledDecisionInstance inherit all attributes **and** relationships from scheduledInstance. ScheduledInstance itself is not used in the api (it is only the parent defining the other classes). So if there is a relationship to ScheduledInstance in the scheme then it is in fact a relationship to scheduledActivityInstance or scheduledDecisionInstance.

The yellow ones are to be aligned with @dih-cdisc

**Comment by dih-cdisc** [comment]
Comments resulting from discussion on scrum TC

[DDF.Terminology_Sprint.1.changes_2024-05-24_DIH.xlsx](https://github.com/cdisc-org/DDF-RA/files/15470112/DDF.Terminology_Sprint.1.changes_2024-05-24_DIH.xlsx)

**Comment by dih-cdisc** [comment]
@czwickl @EMuhlbradt All looks good, lets go with this version of the definitions. Lets get the CT spreadsheet updated and put into Github

 I will create a PBI to review the relationship in row 7 "studyIdentifierScope". the "manages" one I am happy with.
