### ISSUE TITLE
Address and Country

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#36]
Should we use a code list for country as per SDTM?

**Comment by dih-cdisc** [comment]
Agree, we should implement this

**Comment by dih-cdisc** [comment]
Test comment

**Comment by cupkes** [comment]
Ok. so for the Address class, we are now saying that there is only data entry management for the country property, which will be a Code?

**Comment by dih-cdisc** [comment]
Country will be of datatype Code, i.e. a code from the ISO 3166-1 code list
