### ISSUE TITLE
Safety Objective & Endpoint [CT]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#371]
Do we need safety objective/endpoint in CT. MIght be needed to support old studies?
See feature ticket #353

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD , Craig and I have completed drafting what we think are the proposed changes for this ticket. Please see the attached: 
[DDF.Terminology_Sprint.3.changes_2024-06-10.xlsx](https://github.com/user-attachments/files/15766467/DDF.Terminology_Sprint.3.changes_2024-06-10.xlsx)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl :
please also add the notes attribute to:
- IntercurrentEvent 
- AnalysisPopulation

Also change CommentAnnotation attribute code to code**s**

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD done. See the attached spreadsheet: 
[DDF.Terminology_Sprint.3.changes_2024-06-11.xlsx](https://github.com/user-attachments/files/15787314/DDF.Terminology_Sprint.3.changes_2024-06-11.xlsx)

@czwickl
