### ISSUE TITLE
Safety Objective & Endpoint [Model]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#372]
Do we need safety objective/endpoint in CT. MIght be needed to support old studies?

**Comment by dih-cdisc** [comment]
Couple of things on the UML

- In class CommentAnnotation attribute "Text" should be "text", lower case "t"
- Relationship from CommentAnnotation to Code, name should be "codes" not "code", 0..* relationship
- Already noted, relationship to CommentAnnotation "note" should be "notes"
