### ISSUE TITLE
Baseline USDM Version 3 Rules

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#376]
We need an initial set of rules specifications for version 3 of the USDM.

The Information required for each rule is:

- Identifier (single identifier)
- Textual statement of rule
- Class(es) to which the rule applies
- Attribute(s) within the class(es) to which the rule applies
- Warning or Error

Delivery should be via an Excel workbook (single sheet for the rules, maybe a second sheet for a readme / column explanation) placed into a new directory "RULES" within the "Deliverables" directory of the DDF-RA github repo.

May wish to consider the form of the rules text statements such that similar rules have a similar text structure/syntax.

**Comment by BSnoeijerCD** [comment]
I made corresponding columns green in our working spreadsheet RulwRequirements_v4.xlsm
To discuss: 
- Will the identifier be the final core rule ID as is expected in the Harmonized Rules Catalog?
