### ISSUE TITLE
Remove deprecated CORE rules

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#377]
CORE rules that were developed in Phase 3a were based on version 2.6 and not approved by PO. 
The rules that are not intended to be included in the official version 3.0 CORE set are to be deleted from the rules engine. 
The list is available in  the rule_requirements_v4 excel : RemoveFromCore spreadsheet: https://cdisc.sharepoint.com/:x:/r/sites/ddf/Shared%20Documents/DDF3a/RuleDevelopment/RuleRequirements_v4.xlsm?d=w30bfb19071dc48509751b4ec5eeaaffd&csf=1&web=1&e=VjKVib

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I have deleted rules in the list that did exist in the CORE Rules Editor (I added a column to the right to show which have been deleted). I deleted all except the first one. Before I delete this final rule, please confirm that we do not want to change it to a check for non-unique references to `protocolVersion` instead of `id` (i.e., is it OK for more than one instance of the `StudyProtocolDocumentVersion` class to reference the same `protocolVersion` value?)

**Comment by dih-cdisc** [comment]
@ASL-rmarshall @BSnoeijerCD  If you are unsure leave it in. Our first list of rules needs to be a "this is the set of rules we think we need, some need to be discussed". We can then refine, add or remove as we move through the next few sprints. The list does not need to be perfect, but it will give us a good feel for the problem space and its size.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : I indicated that this rule can be deleted because it is not matching the USDM design for three reasons:
- via the API you can only submit 1 version of the study. So you cannot check whether there are multiple versions represented. The document information that is exchanged via the API will always represent the study version that is exchanged.
- the reason that there could be multiple studyProtocolDocumentVersions is that they may represent different variations of that study version like in different languages or as child protocol documents.  
- The corresponding PBI that was specified indicates that the corresponding check will be for unique ids for a studyProtocolDocument are all distinct but there will be a general check to check whether in the total USDM are all distinct.

We could replace this rule by stating that the references studyProtocolDocumentVersion from the studyProtocolDocument are all distinct. But this is implicit to the model checks as the versions are nested in the studyProtocolDocument. So also not needed. 

Given the above I think we can remove this rule.
