### ISSUE TITLE
Version 3 rules - Definitions

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#378]
For the Version 3 rules complete the definitions.  See Feature #376 for details.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc 
@ASL-rmarshall noted the following regarding 1..* cardinalities:
"The cardinality for "criteria" is not fully included in the API spec. The API spec says that the "criteria" attribute must be included, that it must be an array, and that any items in the array must be an EligibilityCriterion, but it does not specify the minimum number of items in the array. An empty array (i.e., no specified eligibility criteria) is therefore not reported as an error by schema-based validation. The same is true for all 1..* cardinalities defined in the UML - the requirement for at least one related instance is not defined in the API spec."

Can update the API specs in phase 4 to account for this? Or should we specify CORE rules for all 1..* relationships. I would prefer the first.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc 
Smaller question based on some contradictions in rule specs:
- is a TimelineExit permitted for a scheduledDecisionInstance?

@ASL-rmarshall

**Comment by BSnoeijerCD** [comment]
@drewcdisc : can you make a rules  directory in the Github deliverable directory for version 3-1-0? Then I will add the final Excel there.

**Comment by BSnoeijerCD** [comment]
@daveih @ASL-rmarshall Uploaded first set of USDM rules to Github.
