### ISSUE TITLE
StudyAmendmentReason other is not possible

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#382]
for StudyAmendmentReason 'Other' is not a value in the code list. 
That is ok as long as we have the option to leave the code empty. However, a code is required for each studyAmendmentReason given the referential integrity. 

Core check (CHK0028) ´If studyAmendementReason Other then reasonOther specified and vice versa` does not add value for USDM v3.0 based on this.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD  I think this relates to #243

**Comment by dih-cdisc** [comment]
We need to leave this until wee see M11 and their updates. We put these reasons in based on the previous m11 work

**Comment by ASL-rmarshall** [comment]
There seem to be several options to deal with "other" reasons for amendments:
1. Make the codelist extensible and always expect a coded response (current proposal "for PO" according to [comment](https://github.com/cdisc-org/DDF-RA/issues/243#issuecomment-1883064542) in #243). In this case, `otherReason` seems to be redundant and should probably be removed.
2. Make the codelist non-extensible *without* a code for "Other". In this case, the cardinality for `code` would need to be changed to 0..1 to make it optional. A rule would then be needed to ensure that either `code` or `otherReason` is provided (but not both).
3. Make the codelist non-extensible *with* a code for "Other", with a couple of options for dealing with "Other":
    1. Keep `otherReason` (allowing only free-text - not coded - other reasons to be given) with a rule to ensure that if code is "Other" then `otherReason` is populated.
    2. Use `AliasCode` instead of `Code` for `StudyAmendmentReason.code`, allowing sponsor terminology to be mapped to the standard codelist, with non-matching codes mapping to the "Other" standard code.  In this case, `otherReason` would probably be redundant.

I'm not sure if any combination of these options (to allow flexibility) would be feasible.

**Comment by dih-cdisc** [comment]
Richard, this is an M11 "feature", we dont have a lot of scope. From the M11 template

![Screenshot 2024-06-18 at 06 42 10](https://github.com/cdisc-org/DDF-RA/assets/115090009/35ebe18e-aec3-43db-b932-88a1f3416678)

and from the draft CT

![Screenshot 2024-06-18 at 06 42 59](https://github.com/cdisc-org/DDF-RA/assets/115090009/0cff56f7-7e1d-4892-8f54-4bb7538cd04c)

This is one where we can proceed "slowly" as it is best to work with a definitive statement from ICH and M11

**Comment by ASL-rmarshall** [comment]
@dih-cdisc Yes, agreed - I was looking at the proposed rule and reviewing all the comments (including yours about waiting for M11) and thought it was worth jotting down what I was thinking to save having to rethink it again later. I should have preceded my comment with "Just some thoughts while we're waiting for the M11 outcome...".  I guess the some of the options at least will have to be considered at that stage, though - whatever the outcome.

I was wondering about "Original" and guessed that's what it meant (unfortunately). Does this get represented in USDM in any way other than just not having a StudyAmendment (let alone a reason)?

**Comment by dih-cdisc** [comment]
From a rule perspective I think we have

- Version = 1 AND No amendments => Original
- Version > 1 AND No Amendmenrs => Mmmmmm, something odd going on
- Version > 1 AND Amendments => Not original

Assumes Versions run from 1..N and are integer. 

We need some flexibility if an org finds themselves in some sort of transition from paper to electronic and dont have a full history ... so warnings rather than errors?

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall @dih-cdisc 
As promised during the scum today. To summarize and conclude:
- Other is not an option in the AmendmentReason CT list for version 3 and the corresponding CT list is also indicated as not extensible. This is a problem since the code for AmendmentReason is required based on referential integrity and a specification of OtherReason can be given based on the attribute reasonOther. Rule CHK0028 can therefore not be executed and needs to be removed from the list for version 3. 
- Other is likely to be included in the CT for version 4 so therefore, once this part is updated CHK0028 can be adapted to version 4. For now the rule will be set to N for version 3 and to ? for version 4.
 
- Based on the last comment from Dave: we could check that in case of version specified for a studyDefinitionDocument there is an amendment or not and whether that is in alignment with version = 1 and version >1. However, the way a comapnies identify versions can differ considerably and may include both numeric and alphanumeric characters. We do not want to set constraints regarding this. Therefore, a CORE check with regards to versioning is not feasible.
- In general we could state that if no amendments are specified it is considered version 1 (e.g. the original).

**Comment by dih-cdisc** [comment]
No action / updates needed
