### ISSUE TITLE
Remove timeline for ScheduledDecisionInstance

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/DDF-RA#383]
The `timeline` relationship between `ScheduledInstance` and `ScheduleTimeline` is used to specify a "sub-timeline" of things that are scheduled to occur within the context of another thing.  The example given in the IG is a "sub-timeline" of timepoints within a visit activity.

As the relationship is from `ScheduledInstance`, this implies that there could be a "sub-timeline" for either a `ScheduledActivityInstance` or a `ScheduledDecisionInstance`, but I can't figure out what would be involved in a "sub-timeline" for a `ScheduledDecisionInstance`.  Would this be a sequence of activities/decisions that need to be performed in order to figure out which condition (if any) is met for the "parent" decision?

If it's never valid to have a "sub-timeline" for a `ScheduledDecisionInstance`, then the relationship should probably be moved to be between `ScheduledActivityInstance` and `ScheduleTimeline`.

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD @ASL-rmarshall: Craig and I had comments about this one. Please see the attached spreadsheet in the 'sprint 3 - chg' tab rows 3 and 4 with a question about whether the timeline relationship will need to be removed from ScheduledInstance since ScheduledDecisionInstance is no longer inheriting that relationship.
[DDF.Terminology_Sprint.3.changes_2024-05-31.xlsx](https://github.com/user-attachments/files/15514098/DDF.Terminology_Sprint.3.changes_2024-05-31.xlsx)

**Comment by czwickl** [comment]
Update was made in CT. Since timeline is inherited by both ScheduledDecisionInstance and ScheduledDecisionInstance from the ScheduledInstance class, removing it from the ScheduledDecisionInstance may necessitate a change to the model as well.

**Comment by BSnoeijerCD** [comment]
Update made to UML. See timeline view in Github 3.1.

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD updates made in 3-2-0 release branch in github to CT deliverables. Ready for review.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl - correctly removed timeline and timeline exit from scheduledInstance and scheduledDecisionInstance in CT spreadsheet. 
Correctly removed 'Inherited from ..' for these attributes in ScheduledActivityInstance. I was wondering whether you should note the removal of 'inherited from ... ' for timeline and timelineexit of ScheduledActivityInstance in the CT_Changes spreadsheet.
@dih-cdisc - corresponding change for API needed
@ASL-rmarshall - set Core rules CHK0100 and CHK0113 to N for version 4.0 and defined corresponding changed rules for 4.0 as CHK0168 and CHK0169. Please review.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I've reviewed checks CHK0100, CHK0113, CHK0168 and CHK0169, and they look good.

**Comment by dih-cdisc** [comment]
See UML in #383

**Comment by dih-cdisc** [comment]
API change made

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD 
Based on the discussion in #384, it might be better for the rules to prevent the use of the `timeline` relationship with `ScheduledDecisionInstance` in v3.0. The v3.0 IG only mentions use of the `timeline` relationship with `ScheduledActivityInstance`: 
> The timeline can also be attached to a ScheduledActivityInstance from another timeline using the timeline reference

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : changed rule CHK0100 and Chk0113 to only refer to scheduledActivity instance. Then they still are applicable to both v3 and v4. 
Changed CHK0168 to give a warning that timeline should not be used in for scheduledDecisionInsance and removed CHK0169.
