### ISSUE TITLE
Timeline exit directly from ScheduledDecisionInstance not possible according to IG

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/DDF-RA#384]
In the UML, the `timelineExit` relationship can be used to indicate the `TimelineExit` associated with a `ScheduledInstance`. This implies that it is possible to exit a timeline directly from either a `ScheduledActivityInstance` or a `ScheduledDecisionInstance`. However, in the "Decisions and Branching" subsection of the "Study Timing" section of the IG, is says:
> For switches, there should be a "default" condition specified for the case when none of the other conditions are satisfied.

- If it is possible to exit a timeline directly from a `ScheduledDecisionInstance`, please update the IG indicate that either a "default" condition *or a timeline exit* should be specified for the case when none of the other conditions is satisfied.
- If it is never possible exit a timeline directly from a `ScheduledDecisionInstance`, please move the `timelineExit` relationship to be between `ScheduledActivityInstance` and `TimelineExit`.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl :
See picture - the timeline relationship is moved from the scheduledInstance class to the scheduledActivityInstance class. That implies that in the CT you only have to remove it from the scheduledInstance and scheduledDecisionInstance class.

**Comment by BSnoeijerCD** [comment]
<img width="887" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW9yQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--740fb4365712b6b4c3a96cd6c9ede1979de2f2d4/Timeline_annotated.png" alt="Timeline_annotated.png" />

**Comment by BSnoeijerCD** [comment]
as discussed with @dih-cdisc - moved timelineExit to scheduledActivityInstance instead of scheduledInstance class.
@EMuhlbradt, @czwickl: For the CT this also implies that like the timeline attribute, the timelineExit attribute should be removed from scheduledDecisionInstance and scheduledInstance classes.
<img width="887" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXdyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de07c3c22a3b6f551860fb745b35cac4c622946e/Timeline_annotated.png" alt="Timeline_annotated.png" />

**Comment by BSnoeijerCD** [comment]
@czwickl @EMuhlbradt : change reviewed in CT and OK. please consider presenting the changed inheritance in the CT_change spreadsheet like for #383.
@ASL-rmarshall : I set CHK0024 and CHK0103 to N for v4.0 and defined new corresponding checks CHK0166 and CHK0172. I removed the 'or decisionInstance' requirement for CHK0034 so it still can be used for v3.0 and v4.0. Please review.
@dih-cdisc : only API change needed for this one.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD 
I've reviewed the rule changes, but I'm not 100% sure what the underlying rationale is.  The decision has been made to prevent the use of `timelineExit` with `ScheduledDecisionInstance` in USDM v4.0, but it's not clear whether/how `timelineExit` is allowed to be used with `ScheduledDecisionInstance` in USDM v3.0 because some of the rule changes appear to be inconsistent. CHK0024 and CHK0103 imply that it's (still) OK to use the `timelineExit` relationship in `ScheduledDecisionInstance` in USDM v3.0. However, the change to CHK0034 (which now indicates that there must be a `ScheduledActivityInstance` with a `timelineExit` in every timeline) implies that a `ScheduledDecisionInstance` with a `timelineExit` relationship may be included in a USDM v3.0 timeline as long as there's also a `ScheduledActivityInstance` with a `timelineExit` relationship in the same timeline.  Is that intentional?

If it's OK for a `ScheduledDecisionInstance` to have a `timelineExit` relationship in USDM V3.0, why is it not OK for this `timelineExit` relationship to be the only exit defined for a timeline in USDM V3.0?

If we think it doesn't make sense to use the `timelineExit` relationship with `ScheduledDecisionInstance` at all (in either USDM v3.0 or v4.0), then I think it would be clearer/simpler to have a USDM v3.0 rule that reports use of `timelineExit` with `ScheduledDecisionInstance` as an error. In this case:
- CHK0167 (must have `defaultCondition` for `ScheduledDecisionInstance`) would then apply for both v3.0 and v4.0.
- All rules relating to the use of `timelineExit` would then only need to apply to `ScheduledActivityInstance` for both v3.0 and v4.0:
    - CHK0103 and CHK0172 (can only reference a timeline exit defined for the same timeline) would then be duplicates so one would need to be removed.
    - CHK0024 and CHK0166 (either `timelineExit` or `defaultCondition` needed not both) would then be duplicates so one would need to be removed.

**Comment by dih-cdisc** [comment]
API update done

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD 
Hmm - for both the `timelineExit` and `timeline` relationships, I think maybe it would be better to use the rules to prevent what we've identified to be invalid use of the v3.0 model (which we're preventing by a model change in v4.0).  The v3.0 IG already says:
> - Decisions and branching are handled using instances of the ScheduledDecisionInstance class ... For switches, there should be a "default" condition
> - The timeline can also be attached to a ScheduledActivityInstance from another timeline using the timeline reference

So - to me anyway - it makes sense to define rules to align with the IG guidance. There are lots of places where the model (and CT) allows something that we prevent through the application of rules.

**Comment by BSnoeijerCD** [comment]
Based on the discussion today I changed CHK0024, CHK0034 and CHk0103 to only refer to scheduledActivityInstance. Then they apply to both v3 and v4. 
I changed CHK0166 to give a warning when timelineExit is specified for scheduledDecisionInstance and removed CHK0172.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD 
I looked through all the checks relating to `timelineExit` and `defaultCondition` and realised that there were still a couple of gaps, so I've made some suggested modifications, including (re)adding:
- CHK0169 to report an error if both `timelineExit` and `defaultCondition` are used with `ScheduledDecisionInstance` in USDM v3.0
- CHK0172 to report a warning if `defaultCondition` is not used with `ScheduledDecisionInstance` in USDM v3.0
- CHK0175 to report an error is a `ScheduledDecisionInstance` refers to a `timelineExit` that is not defined in the same timeline in USDM v3.0.

| Check_ID | Suggested Updated Textual Statement of Rule                                                                                                                            | Classe(s) to which the rule applies                                  | Attributes within the class(es) to which the rule applies | Warning/Error | Version 3.0 | Version 4.0 |
| -------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------- | --------------------------------------------------------- | ------------- | ----------- | ----------- |
| CHK0024  | A scheduled **activity** instance must refer to either a default condition or a timeline exit, but not both.                                                       | Scheduled**Activity**Instance                                    | timelineExit, defaultCondition                            | ERROR         | Y           | Y           |
| CHK0169  | A scheduled **decision** instance must refer to either a default condition or a timeline exit, but not both.                                                       | Scheduled**Decision**Instance                                    | timelineExit, defaultCondition                            | ERROR         | Y           | N           |
| CHK0172  | A scheduled **decision** instance is expected to refer to a default condition.                                                                                     | Scheduled**Decision**Instance                                    | defaultCondition                                          | WARNING       | Y           | N           |
| CHK0166  | A scheduled **decision** instance is not expected to refer to a timeline exit.                                                                                     | Scheduled**Decision**Instance                                    | timelineExit                                              | WARNING       | Y           | N           |
| CHK0167  | A scheduled **decision** instance must refer to a default condition.                                                                                               | Scheduled**Decision**Instance                                    | defaultCondition                                          | ERROR         | N           | Y           |
| CHK0034  | At least one scheduled **activity** instance within a timeline must point to a timeline exit.                                                                      | Scheduled**Activity**Instance                                    | timelineExit                                              | ERROR         | Y           | Y           |
| CHK0142  | A scheduled **activity**/**decision** instance must not refer to itself as its default condition.                                                              | Scheduled**Activity**Instance, Scheduled**Decision**Instance | defaultCondition                                          | ERROR         | Y           | Y           |
| CHK0103  | A scheduled **activity** instance may only reference a timeline exit that is defined within the same schedule timeline as the scheduled **activity** instance. | Scheduled**Activity**Instance                                    | timelineExit                                              | ERROR         | Y           | Y           |
| CHK0175  | A scheduled **decision** instance may only reference a timeline exit that is defined within the same schedule timeline as the scheduled **decision** instance. | Scheduled**Decision**Instance                                    | timelineExit                                              | ERROR         | Y           | N           |

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall :  I understand where the gaps came from. I realized that we did not include the rules for scheduledDecisionInstance v3 timeline and timelineExit. But we deliberately left them out and instead created a warning when timeline or timelineExit or timeline was used in v3.0 indicating that they were not supposed to.
 
Theoretically you are right that this could cause an issue that they are not used correctly but based on risk assessment and implications of showing the rule it is better not to include them e.g.
 - given that it is phase 3, the limited usage of the core checks at the moment and that the attributes will be removed in the next versions it is not efficient to create them for 3.0 
 - if we create the rules separately for v3.0 that would suggest that it is ok to use timeline or timelineExit attributes for scheduledDecision instance in v3.0 and we do not want to encourage that. So therefore we like to express the rules only for scheduledActivityInstance. 

This means that CHK0169 and CHK0175 should not be included in the set.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall: apart form the comments above, I accepted the additions and suggested texts for the rules other then CHK0169 and CHK0175.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I originally had similar thoughts about not encouraging people to use `timelineExit` with `ScheduledDecisionInstance` in v3.0.  However, I then though that, if someone decides to use `timelineExit` (despite the warning), it is still important to make sure that the model is used correctly - while using `timelineExit` is (only) not recommended, the following would definitely be wrong and each should probably be reported as an error:
- Using both `timelineExit` and `defaultCondition` on the same `ScheduledDecisionInstance`
- Not specifying either `timelineExit` or `defaultCondition` on a `ScheduledDecisionInstance`
- Using a `timelineExit` from a different `ScheduleTimeline` on a `ScheduleDecisionInstance`

If we do not have rules these scenarios, they would either generate just an ignorable warning, or no error/warning at all.

I think some of the problem might be the wording of the check specifications and trying to combine "either but not both". If the checks were specified as follows, I think there's less of a suggestion that using `timelineExit` with `ScheduledDecisionInstance` is OK:
- A scheduled decision instance must not reference both a default condition and a timeline exit.
- Default condition and timeline exit must not both be missing for a scheduled decision instance.
- A scheduled decision instance must not reference a timeline exit that is defined in a different timeline.

However, it sounds like the risk of (mis)use in v3.0 may not to be high enough to justify creation of the rules.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall totally see where you come from. But indeed as risk is low and we are already giving a warning when timeline or timelineExit is used for defaultCondition it is ok for now and we do not have to create these rules.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl indicated changes to CT regarding this ticket reviewed in Excel and OK. Please include in CT spreadsheet.
