### ISSUE TITLE
encounter environmental settings attribute name should be plural

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#385]
At the end of phase 3 the model was updated to allow for multiple environmental settings for an encounter. However, the attribute name still indicates a singular relationship instead of a multiple relationship. Attribute name should now be environmentalSetting**s**

**Comment by czwickl** [comment]
Update was made in CT. The only change was to add the "s" to environmentalSetting". This had no impact on the definition.

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD update made in 3-2-0 release branch in github to CT deliverables. Ready for review.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl - change reviewed and ok.
@ASL-rmarshall - I set corresponding Core rules CHK0119 and CHK0164 to N for v4.0 and created new rules with changed variable names for v4.0 as CHK0170 and CHK0171. Please review.
@dih-cdisc - only API change still needed for this one.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I've reviewed checks CHK0119, CHK0164, CHK0170 and CHK0171, and they look good.

**Comment by dih-cdisc** [comment]
API updated

**Comment by BSnoeijerCD** [comment]
Change in CT correctly identified, change in API implemented and according to UML. IG UML view updated. So all good for this ticket.
