### ISSUE TITLE
UML cardinality indicates that at least one eligibility criterion is required for every StudyDesignPopulation and every StudyCohort

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/DDF-RA#387]
The 1..* cardinality on the `criteria` relationship between `PopulationDefinition` and `EligibilityCriterion` indicates that at least one eligibility criterion is required for every instance of classes that inherit the relationship from `PopulationDefinition` (i.e., `StudyDesignPopulation` and `StudyCohort`). Is this correct or are any of the following scenarios possible?:
- The same eligibility criteria apply to all cohorts in a study population, so the criteria are only defined at the study population level.
- Each cohort has a unique set of eligibility criteria, so the criteria are only defined at the cohort level.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc : changed in UML and uloaded new population view to Github. 
No CT changes necessary. Only corresponding changes to API, Rule (v4.0) and probably IG needed.

**Comment by BSnoeijerCD** [comment]
IG => UML update + specification that criteria should be either defined at study population level or at study cohort level.

**Comment by dih-cdisc** [comment]
API updated

**Comment by BSnoeijerCD** [comment]
@dih-cdisc : should it not be criterionIds instead of criteriaIds in the API?
