### ISSUE TITLE
Update first set of CORE rules for v 3.0 in rule editor.

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#391]

**Comment by ASL-rmarshall** [comment]
First set of rules:
| Check_ID | Textual statement of rule                                                                                                                                         | Final CORE Rule ID | JIRA Issue ID                                                  |
| -------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------ | -------------------------------------------------------------- |
| CHK0017  | Timing windows must be fully defined, if one of the window attributes (i.e., window label, window lower, and window upper) is defined then all must be specified. | DDF00006           | [CORERULES-9361](https://jira.cdisc.org/browse/CORERULES-9361) |
| CHK0024  | A scheduled activity instance must refer to either a default condition or a timeline exit, but not both.                                                          | DDF00008           | [CORERULES-9358](https://jira.cdisc.org/browse/CORERULES-9358) |
| CHK0034  | At least one scheduled activity instance within a timeline must point to a timeline exit.                                                                         | DDF00037           | [CORERULES-9359](https://jira.cdisc.org/browse/CORERULES-9359) |
| CHK0038  | Each study element must be referenced by at least one study cell within the same study design.                                                                    | DDF00040           | [CORERULES-9360](https://jira.cdisc.org/browse/CORERULES-9360) |
