### ISSUE TITLE
Improve Estimand relationship to IntercurrentEvent and AnalysisPopulation

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#397]
Based on the PHUSE CSS estimand meeting:
- There can be multiple estimands defined for a study 
- an analysisPopulation can be reused for multiple estimands
- an IntercurrentEvent can be reused for multiple estimands
However, the way they are nested in the API means that they have to be repeated.

**Comment by dih-cdisc** [comment]
Merged into #355 and closed
