### ISSUE TITLE
CT C-Code "Early" Allocation 

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#399]
Is it possible to allow for the early allocatiion of C-Codes to DDF CT items now that the release cycel for CT is every six months

**Comment by drewcdisc** [comment]
This PBI refers only to the process.  The allocation will happen later in other PBIs

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc NCI C-codes added to CT deliverable in 3-4-0 to support Phase 3 DDF concepts

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl 
The entity Encounter does not yet have a c-code while it was already a 2.0 item.
The entity CommentAnnotation already has a c-code while it is new after version 4.0
Do you want to correct that?
