### ISSUE TITLE
Intervention Dose and Adminstration

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#40]
Intervention, dose, administration route etc

- Actually kind of a biomedical drug concept: as it is a new drug this information cannot be retrieved as a concept code from existing dictionaries
- Also for the reference drug, the dose and route cannot be specified. Dictionaries covering this will often also cover market information which can vary from country to country so we cannot specify in that detail. In the study design phase

Child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #172 |
| CT |  #171 |
| API | #173 |
| IG | Done, no ticket |
| Examples | #210  |

**Comment by EMuhlbradt** [comment]
Erin/Craig: The eCPT contains a large table with multiple attributes associated with an administered interventions (see section 6.1., table 1 in eCPT (attached). Previous discussions with Chris/Gaston/Jarod indicated that these should really be modeled as attributes of a separate/new class of something like 'Administered Investigational Intervention' and not added as attributes to the existing class.
The table contains things like:
1. Route of Administration
2. Dosage Level
3. Dose Formulation
4. Dose Strength
5. Name/Description
6. etc.
Consider using that table as a guide to create a new class and attributes?
Also consider that there may be more than one compound within the study, and/or each attribute of each intervention (even if only one compound is used in the study) may have more than one response (e.g., different arms with different routes of administration for the same compound). The model must be flexible enough to accommodate this.

**Comment by EMuhlbradt** [comment]
[CPT_CoreBWE-v009.docx](https://github.com/cdisc-org/DDF-RA/files/10260129/CPT_CoreBWE-v009.docx)

**Comment by dih-cdisc** [comment]
Seems like a large task so we can defer this for a while but now we have a framework to work from.

**Comment by BSnoeijerCD** [comment]
Hi team,
I compared M11 variables from Daves diagram, SDTM TS, CT.gov, CTIS/IDMP in attached spreadsheet. A good basis for adding it to the model.
(https://app.zenhub.com/files/534339959/d151b479-13e4-483a-9954-7965ff9e101a/download).

As discussed with Dave last Tuesday:
- If in M11 or SDTM TS - please add to model / rest can be deferred to later phase but maybe added if univocal and complementary.
- See  picture for proposed model logic. I will explain the potential issues during the meeting

![image.png](https://images.zenhubusercontent.com/64a55ab2667288627de4e279/dea419ba-bea3-4e8a-bb87-bd827df04f69)

**Comment by BSnoeijerCD** [comment]
Comment from Mikkel at the SME meeting of 01/08 based on the above diagram: The study builder links to elements instead of arms. This is more precise. The relationship would be the same (many-many). I agree that it is more precise. Other data models (like ct.gov) refer to arms but the arms can be indirectly linked via the elements as well.

**Comment by BSnoeijerCD** [comment]
Good comment from Diana Wold: duration of treatment can be added as well with standard coding.

**Comment by dih-cdisc** [comment]
Initial sketch design @BSnoeijerCD 

![2023 10 09 Interventions](https://github.com/cdisc-org/DDF-RA/assets/115090009/4c4a1d28-4dff-46ac-a18c-e0857ceb1c0d)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc 
To allow for the automated calculation of InterventionDuration I suggested a link to Procedure as an administration will be often recorded as an activity-procedure in the SoA as well. This might be complex and we can also consider this for the next phase. 
We need a use parameter to indicate what TS parameter should be mapped to the treatment. We have the following TS parameters: TRT/CMPTRT/PLACEBO/TCNTRL. I thought this roughly aligned with the M11 Use parameter and thus can be added for both purposes.

**Comment by BSnoeijerCD** [comment]
Based on the Ct.gov review: the following Intervention Types are included in their list:
- Drug: Including placebo
- Device: Including sham
- Biological/Vaccine
- Procedure/Surgery
- Radiation
- Behavioral: For example, psychotherapy, lifestyle counseling
- Genetic: Including gene transfer, stem cell and recombinant DNA
- Dietary Supplement: For example, vitamins, minerals
- Combination Product: Combining a drug and device, a biological product and device; a drug and biological product; or a drug, biological product, and device
- Diagnostic Test: For example, imaging, in vitro
- Other
This is different from investigational/non-investigational product etc.

**Comment by BSnoeijerCD** [comment]
> @dih-cdisc To allow for the automated calculation of InterventionDuration I suggested a link to Procedure as an administration will be often recorded as an activity-procedure in the SoA as well. This might be complex and we can also consider this for the next phase.
> 
> We need a use parameter to indicate what TS parameter should be mapped to the treatment. We have the following TS parameters: TRT/CMPTRT/PLACEBO/TCNTRL. I thought this roughly aligned with the M11 Use parameter and thus can be added for both purposes.

@dih-cdisc: Can we combine Role and Use with regard to the above? So add the Treatment, comparator treatment, placebo to the role list? Control type (TCNRL) can then be directly derived from that.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl 
First step: changing names and adding attributes to StudyIntervention Class. I made some notes with questions. Note: Two additional changes from Daves diagram:
- I also changed the relationship name from out of studyDesign class. in alignment with the change in class name.
- I change minimumresponseduration from string to quantity. Is that ok? 

<img width="294" alt="StudyIntervention Class" src="https://github.com/cdisc-org/DDF-RA/assets/138679324/1119f4b6-232f-42b9-a6ba-db8407f22198">

I will remove the notes in the final 2.6 version again.

**Comment by BSnoeijerCD** [comment]
Another version with added arrows from source to destination relationship. This might be more clear to Erin and Craig:
<img width="299" alt="StudyIntervention Class" src="https://github.com/cdisc-org/DDF-RA/assets/138679324/0b30e4ed-2163-43f1-a0cd-3d62094ec045">
And we can evaluate whether this would be good to do for the whole diagram.

**Comment by BSnoeijerCD** [comment]
Here is the complete provisional version. I think it is good to go through the questions on our scrum meeting tomorrow.

<img width="401" alt="StudyIntervention Class_v2" src="https://github.com/cdisc-org/DDF-RA/assets/138679324/215cd179-6096-4d3a-bd5d-3ff2ccd31b39">

Additional notes / questions:
- For Role - I would not include a role called intervention as that is the whole class name. Better to use investigational (as compared to rescue, prohibited etc).
- For Role - should we add comparator then?
- For Estimand class: should we change the relationship name treatment to intervention? 
See notes in diagram for additional suggested changes. All is added now provisionally.

**Comment by czwickl** [comment]
@dih-cdisc @BSnoeijerCD @EMuhlbradt 
Notes from scrum meeting discussion on 2023-10-19 (Berber, Erin, Craig):

- we will use Berber's latest diagram above as base UML for CT development

- StudyIntervention class is meant to be very broad and not limited to the investigational treatment. We will let the 'role' and 'type' attributes define an instance of the class

- a codelist needs to be developed for the 'role' attribute in the StudyIntervention class which contains values needed to align with M11 'use'

- codelists for 'role' and 'type' attributes in the StudyIntervention class should be co-developed with the class to ensure everything works together (makes logical sense) for an instance of the class

- we will add 'method' (administration method concept) attribute to the Administration class

- we will remove 'name' and 'label' attributes from the AdministrationDuration class, but leave them in the Administration class (i.e., it is very unlikely that a duration would ever be named)

- the AdministrationDuration class is meant to be across administrations and not within a single instance of an administration.

Please comment if any of these miss-represent our decisions or if anything is missing from the list.
We ask Dave to review for agreement or comment on any items of concern that will need further discussion.

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD @czwickl 

Sprint 8 draft file of changes to review: 
[DDF.Terminology_Sprint.8.changes_2023-10-25pm.xlsx](https://github.com/cdisc-org/DDF-RA/files/13169332/DDF.Terminology_Sprint.8.changes_2023-10-25pm.xlsx)

**Comment by dih-cdisc** [comment]
> @dih-cdisc @BSnoeijerCD @czwickl : for the class StudyIntervention:
> 
> For the propose attribute 'designation': Given the specificity of the intended meaning of the term (whether the study intervention is a IMP or an AxMP, we think the proposed attribute 'designation' is maybe too vague. Berber and Dave to consider an attribute name update should take place. Something like 'medicinalProductDesignation' or 'mpDesignation'?

"productDesignation"? just a bit shorter.

**Comment by dih-cdisc** [comment]
@EMuhlbradt @czwickl @BSnoeijerCD will pick up on the new CT spreadsheet once we have resolved few queries above and the renames in the other ticket for release 2.6 for the API changes

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD 
[DDF.Terminology_Sprint.8.changes_2023-10-26.xlsx](https://github.com/cdisc-org/DDF-RA/files/13177648/DDF.Terminology_Sprint.8.changes_2023-10-26.xlsx)

Updated draft CT file listing all changes (new and changes) with updates from today's discussions

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @daveih @czwickl 

Checked Excel file and found the following issues:

- AS indicated before, I renamed the relationship that goes from studyDesign to studyIntervention class to studyInterventions instead of investigationalInterventions. This is in alignment with the class name change. It is also more appropriate as we do not only want the include investigational Interventions in this new class but all study related intervention. Can you align the CT with that new name?
- the class name was only partly removed from the following attributes in CT. Dave and I indicated to remove the full name in the Excel file: 
    - propertyResponseCodes should be responseCodes in CT
    - surrogateReference should be reference in CT
 - CT missed these changes for previous/next relationships
     - previousEncounter, nextEncounter should be previous and next
     - previousActivity, nextActivity should be previous and next
 - CT missed the following name changes for children relationships (as discussed during one of the scrums this week and indicated in the Excel, we were planning to change them as well )
     - bcCategoryChildren should be children
     - contentChildren should be children
 - I send out an E-mail about the re-added content relationship to studyDesign. I think that is not correct as it was moved from studyDesign to studyProtocolDocumentVersion (see UML). Version 2.5 already includes a new relationship from studyDesign to this new studyProtocolDocumentVersion class called documentVersion.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc @czwickl : All draft CT updates have been made in the 2-6 release branch on Github. I look forward to QC comments.

**Comment by EMuhlbradt** [comment]
> @EMuhlbradt @daveih @czwickl
> 
> Checked Excel file and found the following issues:
> 
> * AS indicated before, I renamed the relationship that goes from studyDesign to studyIntervention class to studyInterventions instead of investigationalInterventions. This is in alignment with the class name change. It is also more appropriate as we do not only want the include investigational Interventions in this new class but all study related intervention. Can you align the CT with that new name?
> * the class name was only partly removed from the following attributes in CT. Dave and I indicated to remove the full name in the Excel file:
>   
>   * propertyResponseCodes should be responseCodes in CT
>   * surrogateReference should be reference in CT
> * CT missed these changes for previous/next relationships
>   
>   * previousEncounter, nextEncounter should be previous and next
>   * previousActivity, nextActivity should be previous and next
> * CT missed the following name changes for children relationships (as discussed during one of the scrums this week and indicated in the Excel, we were planning to change them as well )
>   
>   * bcCategoryChildren should be children
>   * contentChildren should be children
> * I send out an E-mail about the re-added content relationship to studyDesign. I think that is not correct as it was moved from studyDesign to studyProtocolDocumentVersion (see UML). Version 2.5 already includes a new relationship from studyDesign to this new studyProtocolDocumentVersion class called documentVersion.

@BSnoeijerCD -> Thanks for these; all changes made in the CT deliverables in 2-6 branch release.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc Uploaded CT aligned UML version.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl 
While preparing the presentation for the SME meeting, I found that during my check I missed the new relationship from procedure to StudyIntervention. 
Could you add this relationship to the CT? The relationship is called studyIntervention. 
This relationship allows users to link a procedure to a specific study intervention. In that way the intervention can be  is directly related to the study timeline.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl 
While preparing the presentation for the SME meeting, I found that during my check I missed the new relationship from procedure to StudyIntervention. 
Could you add this relationship to the CT? The relationship is called studyIntervention. 
This relationship allows users to link a procedure to a specific study intervention. In that way the intervention can be  is directly related to the study timeline.

**Comment by dih-cdisc** [comment]
Summary of changes for Intervention and Dosing. Also includes name changes

![DDF USDM Model Informative](https://github.com/cdisc-org/DDF-RA/assets/115090009/16954816-1640-4b9a-86f7-f25df6959453)
