### ISSUE TITLE
Ability to group activities [IG]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#400]
See #309

**Comment by BSnoeijerCD** [comment]
@dih-cdisc : 
I updated the UML in the IG. To explain the children further I would like to add an hypothetical example with the following text:

The example below shows how the values for activities that are usually presented in the first column of the schedule of activities are stored in the USDM activity class. The previous and next attribute identify the order of representation while the children attribute is filled in case this representation is identified as a grouping header, for example 'Efficacy'  or 'Safety'. A grouping activity (e.g. having children) is typically only used for representation purposes and is not expected not to be referred to from an scheduled activity Instance or to point to biomedical concepts or procedures.
<img width="1872" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTE2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e622238df6be1e48857500e1f1e7d62dd1054f7/image.png" alt="image.png" />

**Comment by dih-cdisc** [comment]
> The example below shows how the values for activities that are usually presented in the first column of the schedule of activities are stored in the USDM activity class. The previous and next attribute identify the order of representation while the children attribute is filled in case this representation is identified as a grouping header, for example 'Efficacy' or 'Safety'. A grouping activity (e.g. having children) is typically only used for representation purposes and is not expected not to be referred to from an scheduled activity Instance or to point to biomedical concepts or procedures.

The example below shows how the values for activities that are typically present in the first column of the schedule of activities are stored in the USDM activity class and how "grouping" headings can be accommodated. The previous and next attribute is used to identify the order of presentation while the children attribute is used to identify the group members, for example 'Efficacy' or 'Safety'. This grouping activity (e.g. having children) is typically only used for presentation purposes and is not expected not to be referred to from an scheduled activity Instance or to point to biomedical concepts or procedures. It is recommended that only two levels of grouping (i.e, parent and child) are used.
