### ISSUE TITLE
Ability to group activities [Rules]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#402]
See #309

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : 
Probably we need some rules like:
- If there are children then BC categories, BCs, timeline, procedures etc are not expected.
- Ordering aligning parent/children relationship e.g.: parent is first and then the children will follow...
Any thoughts?

**Comment by BSnoeijerCD** [comment]
@dih-cdisc : just discussed with @ASL-rmarshall . Do you agree with the following rules aligning with this feature:
- An activity that includes children are not expected to include any procedures, biomedical concepts, biomedical concept categories, biomedical concept surrogates or a timeline. => this would be a WARNING.
- ordering to be discussed -> what is allowed?

**Comment by dih-cdisc** [comment]
1. Happy with the rule, makes sense and it can always change through experience
2. See my horrid rough diagram below, suggest we use prev / next t order as one list
3. Probably want to say something in IG that only two "levels" recommended, i.e. parent / child activities not grand-parent / parent / child etc

![activity](https://github.com/cdisc-org/DDF-RA/assets/115090009/e5396683-592c-43b5-b823-f089ab3ff0b5)

**Comment by BSnoeijerCD** [comment]
> 1. Happy with the rule, makes sense and it can always change through experience
> 2. See my horrid rough diagram below, suggest we use prev / next t order as one list
> 3. Probably want to say something in IG that only two "levels" recommended, i.e. parent / child activities not grand-parent / parent / child etc
> 
> ![activity](https://private-user-images.githubusercontent.com/115090009/342212398-e5396683-592c-43b5-b823-f089ab3ff0b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTk1NjUsIm5iZiI6MTcxOTIxOTI2NSwicGF0aCI6Ii8xMTUwOTAwMDkvMzQyMjEyMzk4LWU1Mzk2NjgzLTU5MmMtNDNiNS1iODIzLWYwODlhYjNmZjBiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwODU0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjdjYjUwZjRmYTQ2OWNjMTkxNjdmNTkzMTMzMGE0MjVmYWQxZjRiYmI1YzI5N2RkNDEwNjhkZGQyZDkyNWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HqKSkCl_vvDvjjic1E-UoPJMolIrbtqDTDRoPPKnMsY)

Thank you Dave. That aligns with my thoughts. See also the proposed example for the IG in ticket #400.
