### ISSUE TITLE
Multiple Template Support [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#406]
USDM would become more flexible if it could support multiple templates for a single study version. It might be that some documents are extracts of the protocol and not the full document
=> See feature ticket #354

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD Please see the attached list of proposed changes and new additions to the model to support ticket 354 and 406.
[354-406 Sprint 5.xlsx](https://github.com/user-attachments/files/16135232/354-406.Sprint.5.xlsx)

**Comment by BSnoeijerCD** [comment]
Thank you @EMuhlbradt and @czwickl 
To be discussed at scrum: 
- use of template or templateName for the attribute
Tbd:
- starter list of valid values for document type
- text to be deleted from NarrativeContent class 
Notes:
- documentedBy is already a relationship in Study. Might need a small change in definition instead.
- documentVersion is already a relationship in StudyVersion class which was now made plural. Might need a small change in definition instead.

**Comment by BSnoeijerCD** [comment]
Changed template to templateName in UML

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc Changes and additions to support this ticket are now in the CT deliverables in Github, if you want to start reviewing those changes.
(FYI I am still working on changes for ticket 399 and 417 so those aren't ready in Github yet.)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl 
I have the following comments based on the files in Github:
- I did not show the dateValue relationship in the new documents UML but was not intending to remove this. I will adjust the UML to be complete. Can you add it again to the StudyDefinitionDocumentVersion like it was in the StudyProtocolDocumentVersion?
- The definition of relationships study.documentedBy and documentVersions still mentions the study protocol document instead of study definition document. and maybe you also want to make it plural in the description.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt and @czwickl 

The documentVersion attribute in the StudyDesign class is now also pointing to StudyDefinitionDocumentVersion instead of StudyProtocolDocumentVersion. So this should be updated in this definition as well.

And I would suggest to adjust the preferred names for NarrativeContent sectionNumber and sectionTitle to "Narrative Content Section Number" and "Narrative Content Section Title" to be consistent with the preferred names of displaySectionNumber and displaySectionTitle as well.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD done and pushed to 3-4-0 release on Github
