### ISSUE TITLE
Multiple Template Support [Rules]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#408]
USDM would become more flexible if it could support multiple templates for a single study version. It might be that some documents are extracts of the protocol and not the full document
=> See feature ticket #354

**Comment by ASL-rmarshall** [comment]
Proposed rules:

- A child or a narrative content item is expected to be specified for every piece of narrative content.
- If a section number is to be displayed for a piece of narrative content (displaySectionNumber = true) then a section number must be specified (sectionNumber is not blank), and vice versa.
- If a section title is to be displayed for a piece of narrative content (displayTitle = true) then a section title must be specified (sectionTitle is not blank), and vice versa.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : referring to your numbering above
1. Ok as a warning
2. Yes: I proposed to make the sectionNumber and SectionTitle optional based on our discussions during scrum and also the findings in CPT.
3. Yes. see 2.
4. Narrative content is not defined within a studyDefinitionDocumentVersion but on the StudyVersion or Study level (so 1 general container of content for a submitted studyVersion (as there is only 1 submitted per API call). This makes the within the same study version part not necessary as this is the highest level.  narrative content. 
5. ok
6. ok
7. Good one. We also have a ref from studyDesign which can be included.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : we also have the existing rules for narrative content. 
CHK0050 => set to N for V4.0 and created new rule (CHK0181) pointing at the text within NarrativeContentItem. I copied the textual statement as that would stay the same.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall @dih-cdisc :
I uploaded the new version of the rules and corresponding changes file to the Github 3.4 branch for review.

**Comment by BSnoeijerCD** [comment]
All rules are uploaded to the Rules part of Github.
