### ISSUE TITLE
Multiple Template Support [IG]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#409]
USDM would become more flexible if it could support multiple templates for a single study version. It might be that some documents are extracts of the protocol and not the full document
=> See feature ticket #354

**Comment by dih-cdisc** [comment]
> The recursive nature of this class **with its attribute children** provides the user

The recursive nature of this class, using the "children" attribute, provides the user?

I tend to put attribute name in quotes so it is obvious which is the actual attribute name. Most of time it is obvious but it just makes sure it is clear. Being lower case they tend to get lost in the text.
