### ISSUE TITLE
Update Should to Must in CORE rule definitions

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#412]

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I have replaced all occurrences of "should" with "must" in the "Textual statement of rule" column (57 replacements).

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I have also changed "can" to "must" and "cannot" to "must not".

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : thank you. I checked all the warnings are now 'expected'. 
However, not all the errors are 'must'. Should we add must to the others as well?

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD: I think that's a good idea for consistency. I have made changes - if it was a simple insert of "must" or replacement of a few words, I just updated the text, but if it involved a more significant rewording, I added the new text as a suggestion for you to review before applying.  I added a comment for each of the 3 checks marked as ERROR that contained "expected" - I think these should probably be changed to WARNING.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD 
There are no SDTM rules relating to the units for either of these. Min/max age is represented using ISO 8601 duration format in TS, so the units are built-in.

- I agree that planned enrollment number "must not" have units.
- For the age units, I think it would be better to say 'The unit for planned age must be coded according to the SDTM "Age Unit" codelist (C66781)'

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : the defined codelist in the CT is C71620. This also includes the codes for the age unit. Is it ok to take the subset for age unit as reference? and are all age units included in C71620?
