### ISSUE TITLE
Define criteria for conformant USDM XHTML tags

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/DDF-RA#413]
In order to define rules for checking XHTML tags in USDM data, which will be implemented using regular expressions, the conformance criteria need to be specified - some of which will be general and others will depend on where the tags are used. Things that need to be defined include:

1. When a tag or tags can be included in free text (i.e., in the `text` attribute of either `NarrativeContent` or a `SyntaxTemplate` class), what should we use to determine "this piece of text contains at least one XHTML tag" (that must be in the right format)? I'd imagine this would involve looking for a specific pattern of characters, but which ones. Some options include:
    - `<usdm` - should we check for `< usdm` too (with a space between `<` and `usdm`)?
    - `<usdm:` - should we check for `< usdm:`, `<usdm :` and `< usdm :` too (with a space between any of `<`, `usdm`, and `:`)?
    - Specific tags value (e.g., `usdm:ref` or `usdm:tag`) - with the same questions about spaces.
    - For any of these, should we ignore text case?
3. The examples in the IG all use the shorthand closing of each tag (i.e., `/>`) but the example JSON data files include named closings for references (i.e., `></usdm:ref>`). Both are valid form XHTML but are both acceptable for USDM (including named closings for tag tags too: `></usdm:tag>`)? 
4. Is any whitespace acceptable in any of these locations?:
    ```html
    < usdm : ref/tag...[ / > or  > < / usdm : ref/tag >]
     ^    ^ ^           ^ ^     ^ ^ ^ ^    ^ ^       ^
    ```
5. For references, it's already confirmed that `klass`, `id`, and `attribute` can be in any order.
6. For attribute specifications (`klass`, `id`, `attribute`, and `name`):
    - Is any whitespace allowed around the `=` sign?
    - Values will always be quoted text, but are only double quotes allowed? 
7. How strict should we be about the spacing between the `klass`, `id`, and `attribute` assignments?
    - Should there only be a single space or can there be more?
    - Are other whitespace characters allowed?
    - Are end-of-line characters allowed (i.e., can you deliberately split an XHTML tag onto separate lines be inserting a line break)?
7. Are any additional attribute specifications (e.g., sponsor "extensions") allowed?
8. For attribute values, what values are allowed?
    - `klass`: upper/lower case letters only?
    - `attribute`: upper/lower case letters only?
    - `id`: are there any restrictions at all? Whitespace? Quotes?
    - `name`: the parameter name examples in the IG contain only upper/lower case letters and underscores. I'd imagine that numbers might be wanted too. Or should `name` be (un)constrained in the same way as `id`?

**Comment by dih-cdisc** [comment]
One comment on this bit "In order to define rules for checking XHTML tags in USDM data, which will be implemented using regular expressions," ... don't :)

The "X" in XHTML is the giveaway. XHTML is XML. Use an XML parser and follow the XML rules.

**Comment by dih-cdisc** [comment]
Going to close this. Part of implementing CORE engine, not part of USDM

**Comment by dih-cdisc** [comment]
Going to close this. Part of implementing CORE engine, not part of USDM
