### ISSUE TITLE
Update set 3 of CORE rules for v 3.0 in rule editor.

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/DDF-RA#414]

**Comment by ASL-rmarshall** [comment]
Third set of rules:
| Check_ID | Textual statement of rule                                                                                                                                                       | JIRA Issue Summary (Rule ID) | JIRA Issue ID                                                  |
| -------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------- | -------------------------------------------------------------- |
| CHK0021  | Within subject enrollment, the quantity must be a number or a percentage (i.e. the unit must be empty or %)                                                                     | DDF00017                     | [CORERULES-9368](https://jira.cdisc.org/browse/CORERULES-9368) |
| CHK0025  | If a biomedical concept property is required then it must also be enabled, while if it is not enabled then it must not be required.                                             | DDF00013                     | [CORERULES-9369](https://jira.cdisc.org/browse/CORERULES-9369) |
| CHK0027  | A specified condition for assessments must apply to at least to a procedure, biomedical concept, biomedical concept surrogate, biomedical concept category or a whole activity. | DDF00016                     | [CORERULES-9370](https://jira.cdisc.org/browse/CORERULES-9370) |
| CHK0060  | A biomedical concept category is expected to have at least a member or a child.                                                                                                 | DDF00014                     | [CORERULES-9371](https://jira.cdisc.org/browse/CORERULES-9371) |
| CHK0100  | A scheduled activity instance must not point (via the "timeline" relationship) to the timeline in which it is specified.                                                        | DDF00026                     | [CORERULES-9372](https://jira.cdisc.org/browse/CORERULES-9372) |
| CHK0148  | If the duration of an administration will vary, a quantity must not be specified for the administration duration.                                                               | DDF00003                     | [CORERULES-9373](https://jira.cdisc.org/browse/CORERULES-9373) |

**Comment by BSnoeijerCD** [comment]
Reviewed first version of rules. Finalized DDF00026 and provided comments for all the other rules.
Rules will be updated in next iteration.
