### ISSUE TITLE
CPT Table of Contents

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#42]
Next set of CPT updates based on the CPT Table of Content attributes

**Comment by dih-cdisc** [comment]
Next set of CPT updates based on the CPT Table of Content attributes

**Comment by EMuhlbradt** [comment]
[Sprint 6_eCPT_Chpt1_OutsideToC.xlsx](https://github.com/cdisc-org/DDF-RA/files/10246104/Sprint.6_eCPT_Chpt1_OutsideToC.xlsx)

**Comment by dih-cdisc** [comment]
Reviewed, needs discussion

**Comment by dih-cdisc** [comment]
Going to close, overtaken by M11
