### ISSUE TITLE
Abbreviations, should these be handled [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#421]
Do we need to handle abbreviations. Currently we can place these in NarrativeContent without issue but we see repeated definitions. A lot of them will be common across protocols.

See feature ticket #308

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc See attached file with our proposed draft terminology for this ticket.
[421.xlsx](https://github.com/user-attachments/files/16194360/421.xlsx)

**Comment by BSnoeijerCD** [comment]
> @BSnoeijerCD @dih-cdisc See attached file with our proposed draft terminology for this ticket. [421.xlsx](https://github.com/user-attachments/files/16194360/421.xlsx)

Thank you. This looks good and aligns with what I put in the model. So you can add it to the CT terminology spreadsheet.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc: Changes added to 3-5-0 release deliverables in Github. Ready for review

@czwickl can you move this ticket to Review/QA column in Zenhub?

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD changes as discussed today pushed to 3-5-0 release on Github. Please review.
