### ISSUE TITLE
Abbreviations, should these be handled [IG]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#425]
Do we need to handle abbreviations. Currently we can place these in NarrativeContent without issue but we see repeated definitions. A lot of them will be common across protocols.

See feature ticket #308

**Comment by BSnoeijerCD** [comment]
@dih-cdisc, @ASL-rmarshall @EMuhlbradt @czwickl   Apart from updating the UML, I added the following text to the IG:
"Abbreviations that are used to describe the study design are defined at the study version level and can be reused (eg referenced) both in the syntax template text (e.g. for eligibility criteria or assessment conditions) as well as in unstructured document content. The full list defined for the study can also be used to automatically create the full list of abbreviations in the protocol document. "
(See https://wiki.cdisc.org/display/USDMIGv4/Study%2C+Protocols%2C+and+Amendments)

Please suggest improvements if any? I am also wondering whether I need to give an example or whether this is enough explanation?

**Comment by dih-cdisc** [comment]
@BSnoeijerCD I think we need some examples to show how abbreviations are intended to be used within a document
