### ISSUE TITLE
Abbreviations, should these be handled [Rules]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#426]
Do we need to handle abbreviations. Currently we can place these in NarrativeContent without issue but we see repeated definitions. A lot of them will be common across protocols.

See feature ticket #308

**Comment by BSnoeijerCD** [comment]
- An abbreviation must be unique - case sensitive 
- A long name is expected to be unique for each abbreviation - not case sensitive

To consider:
 - Are spaces allowed in abbreviations?

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD Corresponding checks have been added to the RuleRequirements_v4 spreadsheet and are ready for your review:
| Check_ID | Textual statement of rule                                                                   | Warning/Error | Version 3.0 | Version 4.0 |
| -------- | ------------------------------------------------------------------------------------------- | ------------- | ----------- | ----------- |
| CHK0191  | All abbreviations defined for a study version must be unique.                               | ERROR         | N           | Y           |
| CHK0192  | The long names for all abbreviations defined for a study version are expected to be unique. | WARNING       | N           | Y           |

**Comment by BSnoeijerCD** [comment]
> @BSnoeijerCD Corresponding checks have been added to the RuleRequirements_v4 spreadsheet and are ready for your review:
> 
> Check_ID	Textual statement of rule	Warning/Error	Version 3.0	Version 4.0
> CHK0191	All abbreviations defined for a study version must be unique.	ERROR	N	Y
> CHK0192	The long names for all abbreviations defined for a study version are expected to be unique.	WARNING	N	Y

@daveih : If you agree: I can add these to the Rules list and include them in the 3.5 release.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc : added rules and pushed to Github.
