### ISSUE TITLE
Create Set 5 of CORE rules in rule editor

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#428]

**Comment by ASL-rmarshall** [comment]
Fifth set of rules:
| Check_ID | Textual statement of rule                                                                                                                                | Final CORE Rule ID | JIRA Issue ID                                                  |
| -------- | -------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------ | -------------------------------------------------------------- |
| CHK0003  | A timing must only be defined relative to/from a scheduled activity/decision instance that is defined within the same timeline as the timing.            | DDF00046           | [CORERULES-9441](https://jira.cdisc.org/browse/CORERULES-9441) |
| CHK0056  | A study cell must only reference elements that are defined within the same study design as the study cell.                                               | DDF00047           | [CORERULES-9442](https://jira.cdisc.org/browse/CORERULES-9442) |
| CHK0066  | A procedure must only reference a study intervention that is defined within the same study design as the activity within which the procedure is defined. | DDF00048           | [CORERULES-9443](https://jira.cdisc.org/browse/CORERULES-9443) |
| CHK0067  | A study arm must only reference populations that are defined within the same study design as the study arm.                                              | DDF00049           | [CORERULES-9444](https://jira.cdisc.org/browse/CORERULES-9444) |
| CHK0190  | A study arm must only reference cohorts that are defined within the population that is defined within the same study design as the study arm.            | DDF00050           | [CORERULES-9445](https://jira.cdisc.org/browse/CORERULES-9445) |
