### ISSUE TITLE
CPT Chapter 1

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#43]
Next set of CPT updates based on the CPT Chapter 1 attributes

**Comment by EMuhlbradt** [comment]
[Sprint 6_eCPT_Chpt1_OutsideToC.xlsx](https://github.com/cdisc-org/DDF-RA/files/10246106/Sprint.6_eCPT_Chpt1_OutsideToC.xlsx)

**Comment by dih-cdisc** [comment]
Reviewed, needs discussion

**Comment by dih-cdisc** [comment]
Going to close, overtaken by M11

**Comment by dih-cdisc** [comment]
Going to close, overtaken by M11
