### ISSUE TITLE
Pediatric investigational plan number needs to be addressed. [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#434]
Pediatric investigational plan number needs to be addressed. It is more a reference than an identifier. 
See EMA template https://www.ema.europa.eu/en/documents/template-form/paediatric-investigation-plan-pip-key-elements-guidance_en.pdf
See feature ticket #420

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc I have completed adding the items from this ticket into the CT deliverables in the 3-6-0 branch.
