### ISSUE TITLE
Pediatric investigational plan number needs to be addressed. [API]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#436]
Pediatric investigational plan number needs to be addressed. It is more a reference than an identifier. 
See EMA template https://www.ema.europa.eu/en/documents/template-form/paediatric-investigation-plan-pip-key-elements-guidance_en.pdf
See feature ticket #420

**Comment by ASL-rmarshall** [comment]
@dih-cdisc I've updated the API specs in the release-3-6-0 branch in both usdm_api and DDF-RA to:

- Add the `Identifier` class - copied from `StudyIdentifier` and then:
    -  renamed `studyIdentifier` to `text` 
    - renamed `identifierScope` to `scope`
    - updated `instanceType`
- Changed the `StudyIdentifier` class to:
    - Inherit from `Identifier` instead of the base model
    - Remove specifications for `studyIdentifier` and `identifierScope`
- Added `ReferenceIdentifier` class as a copy of the updated `StudyIdentifier` class and
    - Added `type` as `Code`
    - Updated `instanceType`
- Updated `StudyVersion` to:
    - Add `referenceIdentifiers` as a copy of `studyIdentifiers`, updating name and class
    - Make `studyIdentifiers` required (removed `= []`)

Let me know if I missed anything...
