### ISSUE TITLE
Trial Blinding Schema (TBLIND)

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#44]
Addition of TSPARM codelist for TBLIND/Trial Blinding Schema (valid values in codelist C66735). This should be a new attribute associated with the StudyDesign class.

**Comment by cupkes** [comment]
So. would this be ever be an AliasCode property vs a standard Code property?

**Comment by dih-cdisc** [comment]
The following to be checked/confirmed with @czwickl and @EMuhlbradt 

- Attribute Name: studyDesignBlindingScheme (definition C code?)
- DataType: AliasCode (allow for sponsor own code lists)
- Standard Code List: C66735, TBLIND
-
