### ISSUE TITLE
Abbreviation Examples in IG

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#441]
Add examples of how abbreviation will be used to the IG

**Comment by BSnoeijerCD** [comment]
@dih-cdisc : I created a new paragraph for this. See https://wiki.cdisc.org/display/USDMIGv4/Abbreviations
Is this what you expected and clear?

**Comment by dih-cdisc** [comment]
@BSnoeijerCD Reviewed the text. Have a read. I thought it best to show the abbreviations first and then the use of abbreviations (build it up from the bottom), so I reordered your text.

**Comment by BSnoeijerCD** [comment]
> @BSnoeijerCD Reviewed the text. Have a read. I thought it best to show the abbreviations first and then the use of abbreviations (build it up from the bottom), so I reordered your text.

Thank you. Looks good. I re-entered a cross link (will be replaced by paragraph numbers in final editing) and corrected an error in a tag name that I made.
