### ISSUE TITLE
Interventions [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#444]
Formulation missing from intervention and alignment with IDMP.
See feature ticket #316

See [JIRA 520](https://jira.cdisc.org/browse/DDF-520)

**Comment by EMuhlbradt** [comment]
> @EMuhlbradt @czwickl I think there are a few minor problems with the CT file:
> 
> 1. The value in Role column (column C) is incorrectly shown as "Class" instead of "Entity" for the following entities/classes:
>    
>    * AdministrableProduct
>    * AdministrableProductIdentifier
>    * AdministrableProductProperty
>    * Substance
>    * Strength
>    * Ingredient
> 2. The numbering in column A has got out of sync - 458 is missing.
> 3. There's an "N/A" missing from the "Has Value List" column (column J) for `Ingredient` `substance` (row 506).
> 
> Also, shouldn't "Has Value List" for `Identifier` `scope` (row 472) be "N/A" instead of "N"?

@ASL-rmarshall fixed in 3-6-0 release
