### ISSUE TITLE
Evaluate 2 specified text ordering CORE rules for v3.

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#449]
Chk0107 and Chk0132 are both specified for USDM version 3.
Both rules are considering section numbering. However, do we want the constraints of
- no gaps in section numbering (CHK0107)
- following the same ordering as previous/next attributes (CHK0132)
Note that we can also have pieces of narrative content without section numbers and/or titles. 
Note that the checking logic, although possible, will be hard and creating them will cost a lot of effort.

**Comment by BSnoeijerCD** [comment]
Discussed with @ASL-rmarshall and as @dih-cdisc already expressed his concerns before on these rules, we decided to delete them from the list.

**Comment by dih-cdisc** [comment]
No action needed
