### ISSUE TITLE
CORE: Exactly 1 value checks consistency

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#453]
Due to CORE limitations checks for expectations of exactly 1 value or specified reference were split up. However, this was not consistent and the options are now changes so the exactly 1 check can be done in 1 CORE rule. 
Therefore: all those rules should be reviewed regarding formulation and combined again into 1 check if more than 1 was specified due to the CORE limitations.

**Comment by BSnoeijerCD** [comment]
this applies to:
- exactly 1 sponsor study identifier (chk0012 and chk0102 already combined)
- exactly 1 main timeline (combine chk0082 and Chk0030)
- exactly 1 primary objective (combine chk0035 and CHk0130)

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : 
I have made the changes in the ruleRequirements spreadsheet -> updated Chk0030 and Chk0035 and deleted Chk0082 and Chk0130. Can you review?
For the main timeline rule: we had core rule DDF00011 and DDF00012 which now need to be combined.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I've reviewed the ruleRequirements updates and they look good. I have also deleted DDF00011 from the rules editor.
