### ISSUE TITLE
CT terminology governanceDate type [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#457]
The governanceDate.type relationship has a preferred name "Protocol Approval Date Type". A governance date might be applicable to a study version or a study document version now. So "protocol" is too specific.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc @czwickl This terminology change has been completed in the 3-6-0 deliverables. This ticket can be moved to the QC column in Zenhub.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc 
Reviewed: Preferred term for GovernanceDate.type changed from "Protocol Approval Date Type" to "Study Governance Date Type".
This is in alignment to other preferred terms for attributes of the GovernanceDate class. 
So approved and moved to Done.

**Comment by dih-cdisc** [comment]
@BSnoeijerCD 
Should there not be a corresponding UML and API ticket?

**Comment by BSnoeijerCD** [comment]
@dih-cdisc It was a small change and only concerned the CT. No changes in attribute names or relationships were involved.
