### ISSUE TITLE
Organizations [Model]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#458]
Update the USDM regarding Organizations to align with M11, and include different organization types mentioned in protocols. See ticket #293 for scoping.
Other related tickets are #264 and #253.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc : I was wondering whether we should make the appliesTo relationship from StudyRole to StudyDesign plural: e.g 'A study role applies to a study version or one or more study designs' instead of 'A study role applies to a study version or **a** study design'. 
Now the relationship is 0..1.
fyi @ASL-rmarshall

**Comment by dih-cdisc** [comment]
> @dih-cdisc : I was wondering whether we should make the appliesTo relationship from StudyRole to StudyDesign plural: e.g 'A study role applies to a study version or one or more study designs' instead of 'A study role applies to a study version or **a** study design'.
> Now the relationship is 0..1.
> fyi @ASL-rmarshall

Make sense

**Comment by BSnoeijerCD** [comment]
@daveih @ASL-rmarshall : As discussed above, I updated the appliesTo cardinality from StudyRole to StudyDesign to 0..*
To be adjusted for API
