### ISSUE TITLE
Organizations [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#459]
Update the USDM regarding Organizations to align with M11, and include different organization types mentioned in protocols. See ticket #293 for scoping.
Other related tickets are #264 and #253.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl 
Small comment:

I believe the studyRole applies to (appliesTo) the Study Version or StudyRole. Not the other way areound as stated now in the definition.

Furthermore, since study Site is both a role and a separate class, we need to discuss what the implications are of this. 
E.g. if study stie is a role then the study site specifications are stored in the organizations class and not in the StudySite class. If we want that then we can make managesSites a recurrent relationship to organizations class instead of having a separate StudySite class. But then as a result, appliesTo from the subjectEnrollment class should point to Organizations as well and the meaning of this relationship is then less clear and needs further clarification and rules.
@dih-cdisc : What are your thoughts? If we want to do this then it could be changed for the next release.

Furhtermore, as we are including more different kinds of organizations I like to question the requirement for filling in the requirement for identifier and identifierScheme. Can we make it optional?

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt 
We might also need to extend the organization.type list with more types of organizations.  Something like
- Health care institute
- Laboratory

Furthermore: the organization.type is in the DDF value set sheet still organization.**organization**type

**Comment by EMuhlbradt** [comment]
> @EMuhlbradt We might also need to extend the organization.type list with more types of organizations. Something like
> 
> * Health care institute
> * Laboratory
> 
> Furthermore: the organization.type is in the DDF value set sheet has still organization.**organization**type

@BSnoeijerCD fixed the DDF value set tab and pushed change to 3-6-0 release in Github. Do you want to add the two additional organization types NOW or should we create a separate ticket for next spring?

**Comment by dih-cdisc** [comment]
> @EMuhlbradt @czwickl Small comment:
> 
> I believe the studyRole applies to (appliesTo) the Study Version or StudyRole. Not the other way areound as stated now in the definition.
> 
> Furthermore, since study Site is both a role and a separate class, we need to discuss what the implications are of this. E.g. if study stie is a role then the study site specifications are stored in the organizations class and not in the StudySite class. If we want that then we can make managesSites a recurrent relationship to organizations class instead of having a separate StudySite class. But then as a result, appliesTo from the subjectEnrollment class should point to Organizations as well and the meaning of this relationship is then less clear and needs further clarification and rules. See also ticket #264 for this issue. @dih-cdisc : What are your thoughts? If we want to do this then it could be changed for the next release.
> 
> Furhtermore, as we are including more different kinds of organizations I like to question the requirement for completing the requirement for identifier and identifierScheme. Can we make it optional?

Review when we look at Sites and enrollment in next sprint. It would make sense to merge Org and StudySite. As for identifiers, an org always needs some form of identification

**Comment by BSnoeijerCD** [comment]
> > @EMuhlbradt We might also need to extend the organization.type list with more types of organizations. Something like
> > 
> > * Health care institute
> > * Laboratory
> > 
> > Furthermore: the organization.type is in the DDF value set sheet has still organization.**organization**type
> 
> @BSnoeijerCD fixed the DDF value set tab and pushed change to 3-6-0 release in Github. Do you want to add the two additional organization types NOW or should we create a separate ticket for next spring?

Let's create a separate ticket. There are some overlaps also with roles and organization types now that I like to review in the next sprint.
