### ISSUE TITLE
Organizations [Rules]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#461]
Update the USDM regarding Organizations to align with M11, and include different organization types mentioned in protocols. See ticket #293 for scoping.
Other related tickets are #264 and #253.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall: As discussed during scrum today
consider rules:
- Sponsor role should point to organization
- Role should point to organization or role

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I've reviewed the updated model and have come up with the following rules, comments and questions:
- Every study role must apply to either a study version or a study design, but not both.
- A masking, at least one organization, or at least one assigned person must be referenced by every study role. (Can there be a mix?)
- There seems to be quite a lot of overlap between `Organization` `type` and `StudyRole` `code`. The only organization type that does not currently have a corresponding study role is "Clinical Study Registry" but, given the mix of study roles, it wouldn't seem out of place as a study role.  Does this make organization type redundant? If not, do we need rules like the following to ensure alignment?:
    - An organization with a type of "Research Organization" is expected to be referenced for every contract research organization study role.
    - Organizations with a type that is not "Research Organization" must not be referenced for a contract research organization study role.
    - An organization with a type of "Clinical Study Sponsor" is expected to be referenced for every sponsor or co-sponsor study role.
    - Organizations with a type that is not "Clinical Study Sponsor" must not be referenced for a sponsor, co-sponsor or local sponsor study role.
    - An organization with a type of "Regulatory Agency" is expected to be referenced for every regulatory agency study role.
    - Organizations with a type that is not "Regulatory Agency" must not be referenced for a regulatory agency study role.
- It's not clear how the "Study Site" study role should relate to the `StudySite` class, but it would seem strange for there not to be some sort of association.  I think that an organization that **performs the role of** a study site is not the same as an organization that **manages** study sites.
- It's also not clear if there are study roles that are expected to reference assigned persons or organizations, or if a role can reference both. Do we need rules like the following?:
    - The following roles are not expected to have an organization:
        - Clinical Trial Physician
        - Investigator
        - Medical Expert
        - Principal investigator
        - Project Manager
        - Statistician
        - Study Subject
    - The following roles are not expected to have an assigned person:
        - Contract Research Organization
        - Co-Sponsor
        - Laboratory
        - Manufacturer
        - Pharmacovigilance
        - Regulatory Agency 
        - Sponsor
        - Study Site
- An organization that has managed sites must be either a clinical study sponsor or a research organization.
- If a role can have both a organizations and assigned persons, is there any expected, required or restricted correspondence between the role's organization(s) and the assigned person's organization?
- What sorts of values are expected/required for `Masking` `description`?  Might the definitions of maskings be expanded in future (e.g., to reference specific BCs - such as lab test - whose results are masked for specific roles)?  For now, I don't think there are any rules for `Masking`.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I have now finished drafting the rule specifications for CHK0233 - CHK0237 in the RulesRequirement spreadsheet - please take a look and amend if necessary.

**Comment by BSnoeijerCD** [comment]
As discussed today. Rules added to the overview by @ASL-rmarshall, reviewed and published in github for internal review.

**Comment by BSnoeijerCD** [comment]
Discussed with @ASL-rmarshall :
   •	Every study role must apply to either a study version or to at least one study design, but not both.
o	Agree – to be added
•	A masking, at least one organization, or at least one assigned person must be referenced by every study role. (Can there be a mix?)
o	There is no y/n masking. So I assumed you would only specify masking if applicable. Not specified would mean no masking. That means that this rule is not ok. As stated below – we need to review Masking/Blinding in the light of M11.
•	There seems to be quite a lot of overlap between Organization type and StudyRole code. The only organization type that does not currently have a corresponding study role is "Clinical Study Registry" but, given the mix of study roles, it wouldn't seem out of place as a study role. Does this make organization type redundant? If not, do we need rules like the following to ensure alignment?:
Although there seems to be an overlap, an organization type is something different then a role within a study. A sponsor organization for example can have different roles. In addition, if you specify a role by an assignedPerson then you do not want the organization directly referenced but via one or more persons.
o	An organization with a type of "Research Organization" is expected to be referenced for every contract research organization study role. => yes / or should the role be: contract research? Instead of contract research organization. 
o	Organizations with a type that is not "Research Organization" must not be referenced for a contract research organization study role. => what if someone else is doing the contract research 
o	An organization with a type of "Clinical Study Sponsor" is expected to be referenced for every sponsor or co-sponsor study role. => makes sense. In this case the role is not mentioning the organization. Or should the organization type be => pharmaceutical company? And maybe we have other organizations that would also be sponsors?
o	Organizations with a type that is not "Clinical Study Sponsor" must not be referenced for a sponsor, co-sponsor or local sponsor study role. => see previous.
o	An organization with a type of "Regulatory Agency" is expected to be referenced for every regulatory agency study role. => Ok. Not sure whether we would have this role .
o	Organizations with a type that is not "Regulatory Agency" must not be referenced for a regulatory agency study role. Ok.
•	It's not clear how the "Study Site" study role should relate to the StudySite class, but it would seem strange for there not to be some sort of association. I think that an organization that performs the role of a study site is not the same as an organization that manages study sites. To be discussed for next version.
•	It's also not clear if there are study roles that are expected to reference assigned persons or organizations, or if a role can reference both. Do we need rules like the following?: As it is up to the user to define this or not we do not want to create rules for this. In some cases it is to be defined in the study design phase in a number of other cases it is not yet defined in the study design phase. Must not have both
o	The following roles are not expected to have an organization:
	Clinical Trial Physician
	Investigator
	Medical Expert
	Principal investigator
	Project Manager
	Statistician
	Study Subject
o	The following roles are not expected to have an assigned person:
	Contract Research Organization
	Co-Sponsor
	Laboratory
	Manufacturer
	Pharmacovigilance ?? => could be assigned persons within an organization
	Regulatory Agency
	Sponsor
	Study Site
•	An organization that has managed sites must be either a clinical study sponsor or a research organization. Expected? => and/or leave this one until the next version?
•	If a role can have both a organizations and assigned persons, is there any expected, required or restricted correspondence between the role's organization(s) and the assigned person's organization? Yes: either one or more organizations or 1 or more assignedPersons. Not both!
•	What sorts of values are expected/required for Masking description? Might the definitions of maskings be expanded in future (e.g., to reference specific BCs - such as lab test - whose results are masked for specific roles)? For now, I don't think there are any rules for Masking. Indeed – see comment above and we will review M11 and example protocols for this. => they changed to blinding and I do not see any restrictions regarding blinding now.
	Single Blind/Double Blind: expect at least one/two roles masked? Applies to either the studyVersion or the specific corresponding study design.
