### ISSUE TITLE
Protocol Amendments

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#469]
Need to ensure that M11 protocol amendments can be supported. Three aspects

1. Amendment support aligns with the updated M11 specification
2. Ensure we can support the detailed rationale for changes. Note we dont need exact details of change as an electronic comparison can be made (see #305)
3. Align with any review comments on Organizations arising from release 3.6. This overlaps because of the need to note enrollment at the time of an amendment being approved.

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #473 |
| CT |  #474 |
| API | #475 |
| Rules | #477 |
| IG | #476 |
| Test Data |  #478 |
| Associated Tickets |  #305, #264  |

**Comment by BSnoeijerCD** [comment]
GeographicScope and dates

Considerations:
- The scope is a direct feature of an amendment according to M11. At the same time it is the feature of the study Version (date) that links to the current amendment. We have included that based on the governance date of the studyVersion.
- An amendment is a feature of a study version. We do not want to include multiple versions of a study in the USDM (using a previous attribute in StudyVersion) as all other classes are nested in the StudyVersion class and that would require to keep submitting all information of previous versions. At the same time we want to store dates, scopes and current enrollment of each amendment which is also required by M11.
- Enrollment, geographic scope and signature dates are all directly related and linked to 1 version of the study/amendment. All three features are required for the amendment history.
- We now have a versionIdentifier in StudyVersion and a StudyAmendment.number which (partly?) overlapping.

Based on this I will propose an idea at the scrum today.

**Comment by BSnoeijerCD** [comment]
Based on the template, the protocol requires:
Front page(s)
-	Original Protocol identifier
-	Version number
-	Version Date – (without a scope)
-	Amendment identifier (if applicable)
-	Amendment scope (global / country(ies) / region(s) / site(s) )
-	Sponsor approval date
Current amendment
-	Approximate number/percentage enrolled at time of approval
-	Reason(s) for amendment (primary/secondary)
o	Select closest match / if none apply – choose “other”
-	Summary
-	Substantial impact on safety or rights of participants
-	Substantial impact on reliability and robustness of the data generated in the clinical trial
-	Changes
o	Description
o	Brief rationale
o	Section # and Name
Paragraph 12.3 Prior Protocol Amendments
-	Summary of changes from previous amendments
-	Keep number/percentage enrolled at time of approval
-	Listing approximate enrolment by cohort in an option
-	The overview of changes from all prior protocol amendment (i.e. description, brief rationale, section # and name)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @czwickl @EMuhlbradt @ASL-rmarshall 
See points to consider in the ticket above. Below the suggested changes. 
Some points of discussion for scrum today: 
- Scope linked to date/direct? 
- Date types
- Substantial impact types - separate class? or two attributes?
![StudyVersions_annot](https://github.com/user-attachments/assets/34ebeacf-de82-4e69-b964-c7c704080349)

**Comment by daveih** [comment]
Suggestions

### Impact Class
Make impact a separate class, AmendmentImpact, with attributes

- rationale: string
- substantial: boolean
- type: Code (code list extensible, SafetyRights and ReliabilityRobustness)

This will allow for the two substantial impacts but allow sponsors to add other impacts (substantial or non-substantial) if they wanted.

### Geographic Scope
Rather than GeographicScope having a type of 'site' which just feels wrong, keep the existing SubjectEnrollment appliesTo to the StudySite class, feels like a more consistent approach (enrollment statistics apply to either a geographic scope, or a cohort or a site and only one of them).
 
The site will thus need some geographic info. Site could be an Organization in its own right (type = StudySite) and thus an address or could explicitly state the site's geographic location using a AliasCode attribute (or point at GeographicScope)

### Governance Dates
For governance date the referring class provides the context for a date, we might want to consider 'Approval Date' and 'Effective Date' for the code list which then gives:

- StudyVersion Approval
- Amendment Approval
- Document Approval
- StudyVersion Effective
- Amendment Effective
- Document Effective

Thus, from an implementation perspective, from a Document class for example it is "give me my (the document's) effective date" 

Might also be useful to nice to have an 'Issued Date' or something similar, for draft versions?

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @dih-cdisc @ASL-rmarshall 
See below the updated StudyVersion/amendment part of the data model based on the discussions today.
**Note** that the boolean attribute substantialimpact has been deleted from the studyAmendment class and has been replaced by a relationship called 'substantialImpacts to the new StudyAmendmentImpact class.
![StudyVersions_new2](https://github.com/user-attachments/assets/8dae655b-4f67-4d82-8bff-374d0b3e526f)

**Comment by BSnoeijerCD** [comment]
corrected small typo in substantialImpacts and pushed to Github

**Comment by dih-cdisc** [comment]
@BSnoeijerCD @EMuhlbradt @ASL-rmarshall @czwickl 

Have a think about the name of the relationship from StudyAmendment to StudyAmendmentImpact labelled 'substantialImpacts'. The 'substantialness', if there is such a word, is. incorporated in the 'substantial' attribute of the Impact class. It was to allow a sponsor to add their own 'impacts' that they may not consider substantial in addition to the ones required by M11. Has the downside that you need to set the flag True for the M11 ones. Anyway, the relationship might be better named 'impacts' or something along those lines.

**Comment by BSnoeijerCD** [comment]
> @BSnoeijerCD @EMuhlbradt @ASL-rmarshall @czwickl
> 
> Have a think about the name of the relationship from StudyAmendment to StudyAmendmentImpact labelled 'substantialImpacts'. The 'substantialness', if there is such a word, is. incorporated in the 'substantial' attribute of the Impact class. It was to allow a sponsor to add their own 'impacts' that they may not consider substantial in addition to the ones required by M11. Has the downside that you need to set the flag True for the M11 ones. Anyway, the relationship might be better named 'impacts' or something along those lines.

Good point. For background info, I just found a related protocol reference Article 10(a) of Directive 2001/20/EC of the European Parliament:
<img width="197" alt="Article10a_dirEU" src="https://github.com/user-attachments/assets/fed3aca4-b136-4be8-858b-7a4cba375e42">

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD It's interesting that, according to that Article, it's the amendments that are substantial, not the impacts. If M11 is trying to implement that Article, the resultant M11 questions aren't quite accurate.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @czwickl @EMuhlbradt @ASL-rmarshall 
I made the updates as discussed during scrum today. This includes some cardinality changes. See diagram below:
![StudyVersions_new3](https://github.com/user-attachments/assets/86d72890-e56f-4e13-82a0-51263e24791e)

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD @EMuhlbradt A couple of thoughts triggered by looking at the new `country` relationship from `StudySite`:
- This relationship looks like it's intended to be defined in the same way as the `country` relationship from `Address` - i.e., it goes to `Code` and am I right to assume that the expectation is that the ISO 3166-1 alpha-3 codelist will be used?
- The `code` relationship from `GeographicScope` looks like it might perform a similar function when `GeographicScope.type` = "Country" but, in this case, the relationship is to `AliasCode` and the CT file says:
    > Point out to external dictionaries: Standard code is ISO-3166; Alias codes drawn from GENC, UN Region Codes, etc.

    However, I don't think this will work because the `code` relationship is also used to identify regions when the `GeographicScope.type` = "Region" (hence the reference to "UN Region Codes"). In order to use `AliasCode`, you must specify a standard codelist and always provide a standard code from that codelist - but the ISO-3166 codelist does not contain the type of region codes we need for geographic regions. I think we probably just need to change the comment in the CT file to say:
    > Point out to external dictionaries: Standard code is ISO-3166 alpha-3 for countries and UN Region Codes for regions; Alias codes drawn from GENC, etc.

    We might then need a rule to ensure the correct standard coding for countries vs regions - but we'd need to define what's checkable for ISO 3166 vs UN Region codes (possibly just the `codeSystem`).
- Is it OK to insist on only ISO 3166 codes for address and study site, but to allow other types of country coding for geographic scopes? Or should we allow country alias codes for address and study site too?

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD Also:
- The target cardinality for `StudyEnrollment` -- `appliesTo` -> `GeographicScope` should be 0..1, not 1..*. A study enrollment applies to either a (single) geographic scope, a (single) study site, or a (single) cohort. If you need to define enrollments for multiple geographic scopes, sites or cohorts, you'd just create additional instances of `StudyEnrollment`, each with an `appliesTo` relationship to a single target.
- Does every study amendment have to have a defined study enrollment (even if it's for something as trivial as typographical changes)? If not, the target cardinality for `StudyAmendment` -- `enrollments` -> `StudyEnrollment` should be 0..\*, not 1..\*. (It may have been defined as 1..* before because `StudyEnrollment` "was" the geographic scope (via inheritance), and a geographic scope is required for every amendment).

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall
I looked in the template and technical specs but did not see in both that there can be multiple section numbers and titles specified for a change. Can you indicate where you got that indication from. 

@EMuhlbradt, @dih-cdisc  @czwickl : I see that M11 specifies the whole list of optional section numbers and titles as CT. What are your opinions about including this CT in USDM? Should we point to a codelist with the prespecified section numbers and titles aligning to M11 as indicated in ticket #472? On the other hand, this is very M11 specific, might be subject to change and if an (older) protocol template is used not applicable.

**Comment by BSnoeijerCD** [comment]
> @BSnoeijerCD Also:
> 
> * The target cardinality for `StudyEnrollment` -- `appliesTo` -> `GeographicScope` should be 0..1, not 1..*. A study enrollment applies to either a (single) geographic scope, a (single) study site, or a (single) cohort. If you need to define enrollments for multiple geographic scopes, sites or cohorts, you'd just create additional instances of `StudyEnrollment`, each with an `appliesTo` relationship to a single target.
> * Does every study amendment have to have a defined study enrollment (even if it's for something as trivial as typographical changes)? If not, the target cardinality for `StudyAmendment` -- `enrollments` -> `StudyEnrollment` should be 0..*, not 1..*. (It may have been defined as 1..* before because `StudyEnrollment` "was" the geographic scope (via inheritance), and a geographic scope is required for every amendment).

I will correct appliesTo in the model to 0..1.
Also, since enrollment is optional according to the M11 technical specis I will change that cardinality too to optional.

**Comment by ASL-rmarshall** [comment]
> @ASL-rmarshall I looked in the template and technical specs but did not see in both that there can be multiple section numbers and titles specified for a change. Can you indicate where you got that indication from.
> 
@BSnoeijerCD See:
- Template: lines 94-95 on page 5:
    > If the same change affects multiple parts of the protocol, it is acceptable to list multiple locations in the right column.
- Technical Specification: item 113 on pages 46-50:
    > **Repeating and/or Reuse Rules**: Yes, repeatable for each description of change in the amendment

    It's also interesting that the technical spec suggests that controlled terminology will be used for section numbers and titles.

**Comment by BSnoeijerCD** [comment]
> > @ASL-rmarshall I looked in the template and technical specs but did not see in both that there can be multiple section numbers and titles specified for a change. Can you indicate where you got that indication from.
> 
> @BSnoeijerCD See:
> 
> * Template: lines 94-95 on page 5:
>   > If the same change affects multiple parts of the protocol, it is acceptable to list multiple locations in the right column.
> * Technical Specification: item 113 on pages 46-50:
>   > **Repeating and/or Reuse Rules**: Yes, repeatable for each description of change in the amendment
>   
>   
>   It's also interesting that the technical spec suggests that controlled terminology will be used for section numbers and titles

Thank you. The "Repeating and/or Reuse Rules" are identical for rationale of the change and for description of the change itself. So therefore can be interpreted in different ways. However, the template text and also the logic of having the same change represented at different places in the protocol. Let's discuss at the scrum how to handle, as section numbers and titles are pairs and we have that CT issue as well.

**Comment by dih-cdisc** [comment]
@BSnoeijerCD @ASL-rmarshall 

Be careful. Divide the logic into what USDM needs to model versus how M11 presents the information, the two may not be the same. In this case I reckon the model versus presentation could well be quite different. 

Also be careful in the sense that we need to accommodate M11 but not necessarily be driven by it.

Also, if M11 is not clear or we consider it to be in error, we can feedback this information into the ICH review

**Comment by BSnoeijerCD** [comment]
Based on input above and scrum discussion yesterday we felt that an amendment change is likely to reference to multiple sections of a document. E.g. one specific change may be reflected in multiple sections of the protocol. 
The reference includes a pair of section number and title. Combining both into 1 reference attribute would make the data less structured and limit the option to link this to the actual previous document. However, the link between the two needs to be preserved also when we have multiple references. Therefore we decided that creating a separate class for the references would make sense (see diagram below).

Other changes discussed will not be included. 
- We do not include CT for section numbers and titles as USDM can include other types of (historical) protocols
- We keep the country code relationships as is for now. 
- StudyAmendmentImpact class and relationships are to be reviewed based on actual use cases

See updated diagram below:
![StudyVersions_new3](https://github.com/user-attachments/assets/d7d5a254-62e4-4f65-948b-38a88941146b)

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc @ASL-rmarshall See draft CT file here: 
[469.xlsx](https://github.com/user-attachments/files/17138090/469.xlsx)

**Comment by BSnoeijerCD** [comment]
@czwickl : Did you already review the M11 CT that is applicable for amendments?
- Are there any changes expected for amendment reason (e.g. what about other / NA? )
- The rest can be more generalized and then mapped to M11. I did not see any other potential CT issues for the amendments part. 

One more general question: Do we want to include Location of Sponsor Approval Date as specified in the template?

**Comment by BSnoeijerCD** [comment]
@daveih @ASL-rmarshall @EMuhlbradt @czwickl 

See below snippets of how amendment changes were covered in a sample of 8 studies. 3 additional studies (of which 2 were from big pharma companies) did not include a list of changes at all.

The following examples are all including a short description and rationale. two are from the same company.
<img width="496" alt="Screenshot ListOfChanges_A" src="https://github.com/user-attachments/assets/4c8e146d-00c7-4059-8f52-e94a0c0be286">
<img width="533" alt="Screenshot ListOfChanges_B" src="https://github.com/user-attachments/assets/892f7f8d-1970-43dc-ac05-56bd9b08eb57">
<img width="593" alt="Screenshot ListOfChanges_M" src="https://github.com/user-attachments/assets/28fd3175-cb9a-47e6-b632-3f2e1594cb78">
<img width="604" alt="Screenshot ListOfChanges_M2" src="https://github.com/user-attachments/assets/620f4be6-df80-4ff4-87d8-1b37c86b7ccc">
<img width="561" alt="Screenshot ListOfChanges_S" src="https://github.com/user-attachments/assets/0b6b673c-cba1-4961-b487-a45f60301511">

Only 1 had the strikethrough/replacement option. The description and rationale of change as others present them were both combined in the rationale field:
<img width="415" alt="Screenshot ListOfChanges_J" src="https://github.com/user-attachments/assets/57049892-4090-40ab-ab8b-4703941d702e">

There were a few other variants as well:
<img width="424" alt="Screenshot ListOfChanges_N" src="https://github.com/user-attachments/assets/1db91dd5-bfcd-471f-8144-9bc606e2fe55">
<img width="539" alt="Screenshot ListOfChanges_U" src="https://github.com/user-attachments/assets/5bb80c81-2255-4139-9bef-67189c242e3f">
