### ISSUE TITLE
Add BC Capability

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#47]
See ticket DDF-RA #18 

- Need BC collections added to sketch design
- Discuss role of StudyData. We need a "placeholder" mechanism for:
  - when a BC is not available so just a "label" is added by the user with maybe a description
  - when we just want to refer to a BC not include it

**Comment by dih-cdisc** [comment]
BC Collections / Recursion / Groupings are all referring to the same concept on being able to group BCs into various levels.
 
e.g.,
- Safety assessments (grouping 1)
  - Vital signs (grouping 2)
    - Blood Pressure (Grouping 3)
      - Systolic (grouping 4)
      - Diastolic (grouping 4)

**Comment by cupkes** [comment]
I have been going back and forth over the semantics of this all night.  I'll create an actual class diagram shortly, but one thing I have decided on is that there will likely be two classes:  one that plays a piece in the ontology and one that associates BCs with the ontology.  The mechanics are straightforward.  The semantics (class names, etc..) I've been flip-flopping on.  I'll try and just make a command decision here shortly.

**Comment by cupkes** [comment]
![BiomedicalConcepts](https://user-images.githubusercontent.com/3847691/214044570-53b27a15-89ed-4e8b-aa41-790f3cb2e21d.png)

**Comment by cupkes** [comment]
So, at first I had two different types of classes, one the parent class Category and a sub class CategoryLeaf.  This polymorphism would just confuse too many.
So, the rules for when members can be added is now not the job of the SDR class.  That logic would exist in the ontology or taxonomy builder class that generates the doubly-linked list of of categories.

**Comment by cupkes** [comment]
As for the BC itself, not sure of what kind of Code or AliasCode properties it might have.  Just have a label (non-conformant) at the moment.

**Comment by cupkes** [comment]
Also note, this design does not restrict the ontology to single inheritance as any category can have multiple parents..

**Comment by cupkes** [comment]
![BiomedicalConcept](https://user-images.githubusercontent.com/3847691/214050657-19d1f7f4-e18f-4bb1-94ed-534162c32018.png)

**Comment by dih-cdisc** [comment]
Responses to @EMuhlbradt @czwickl 
[DDF.Terminology_Sprint.7.changes_2023-01-20.xlsx](https://github.com/cdisc-org/DDF-RA/files/10487729/DDF.Terminology_Sprint.7.changes_2023-01-20.xlsx)

**Comment by cupkes** [comment]
![BiomedicalConcept](https://user-images.githubusercontent.com/3847691/215075249-dd4f7a76-6dd4-4990-b4fa-3f487c847120.png)

**Comment by cupkes** [comment]
Let's discuss.

**Comment by cupkes** [comment]
![BiomedicalConcept](https://user-images.githubusercontent.com/3847691/215154721-ca88cef5-268c-4fbb-bb39-0130169e62b8.png)

**Comment by cupkes** [comment]
One more time:
![BiomedicalConcept](https://user-images.githubusercontent.com/3847691/215156239-c07d9177-e4a4-40ae-9f34-a8585622c5a3.png)

**Comment by EMuhlbradt** [comment]
Question from Erin/Craig: What do you mean by 'bcPropertyDatatype'? Do you actually mean the datatype of the property itself or the datatype of the valid responses for the stated property? Is the attribute better named as 'Biomedical Concept Property Response Data Type'

The model seems to imply that bcPropertyDatatype is a string based on the latest model diagram?! So why do we need this info? Shouldn't the datatype be on the response code instead?

**Comment by EMuhlbradt** [comment]
Question from Craig/Erin: What do the modelers mean by a biomedical concept surrogate? Like A1C level being a surrogate for diabetes diagnosis? Or something else entirely?

**Comment by EMuhlbradt** [comment]
Please see attached draft CT for sprint 7 and biomedical concept modeling: 
[DDF.Terminology_Sprint.7.changes_2023-01-30.xlsx](https://github.com/cdisc-org/DDF-RA/files/10539048/DDF.Terminology_Sprint.7.changes_2023-01-30.xlsx)

**Comment by dih-cdisc** [comment]
> Question from Craig/Erin: What do the modelers mean by a biomedical concept surrogate? Like A1C level being a surrogate for diabetes diagnosis? Or something else entirely?

It is for when we know we need a BC but dont have a BC definition available, we can fill in a placeholder definition, maybe point at a LOINC or Snomed code for an equivalent definition

**Comment by dih-cdisc** [comment]
> 



> Question from Erin/Craig: What do you mean by 'bcPropertyDatatype'? Do you actually mean the datatype of the property itself or the datatype of the valid responses for the stated property? Is the attribute better named as 'Biomedical Concept Property Response Data Type'
> 
> The model seems to imply that bcPropertyDatatype is a string based on the latest model diagram?! So why do we need this info? Shouldn't the datatype be on the response code instead?

It is the response datatype but the name gets too long. The model names are implementation "unfriendly" as it is.

**Comment by EMuhlbradt** [comment]
Comment from Erin/Craig: There appears to be some mis-alignment between Dave's latest Ball and Stick diagram and the latest model pict from Gaston. Which is the source of truth?
1. In the ResponseCode class, Dave's diagram has 'code' as an attribute only while Gaston's model has 'code' as an attribute AND a relationship.
2. In the BiomedicalConceptCategory class, Dave's diagram has one additional attribute 'bcReference'  and two additional relationships 'bcCategoryParents' and 'bcCategoryChildren'. Gaston's model does not have these.
3. In the BiomedicalConcept class, Dave's diagram has an attribute 'bcConceptId' while Gaston's model has 'biomedicalConceptId' as the attribute. We think these are the same.
4. In the BiomedicalConceptProperty class, Dave's diagram has an attribute 'bcPropertyConceptId' while Gaston's model shows an attribute of 'bcPropertyId'. Please check inconsistency. Also please note that Gaston's model shows 'bcPropertyResponseCodes' as an attribute and a relationship while Dave's diagram only shows 'bcPropertyResponseCodes' as a relationship. What's correct?
5. None of the new attributes and relationships for the Activity class are reflected in Dave's diagram.

**Comment by dih-cdisc** [comment]
Response to above for @EMuhlbradt and @czwickl 

# Not seeing the relationship in Gaston's UML 
# Removed 'bcReference' from DIH diagram. The relationships on DIH are the List<BiomedicalConceptCategory>, it is a drawing style. Where in the UML you see an attribute that has a type of another class it is a "relationship" but in the UML does not get drawn as such. So OK. Follow the UML
# No. In Gaston's diagram this is the id of the BC. In mine I dont show the id fields for any class. This  bcConceptId is the CT reference for the definition of the BC, so the C Code for "Systolic Blood Pressure". Use an alias code in case we want to refer to other terminologies
# For the concept Id same answer as above. The relationship thing is OK, style issue as above
# Amended the names in the DIH picture of the three relationships relating to the List<Class Name> attributes. Should now align

**Comment by dih-cdisc** [comment]
Given @EMuhlbradt's checking @ggasg, couple of tweaks needed

1. Activity class, studyDataCollection attribute can be deleted (replaced by the surrogate class)
2. 'biomedicalConcept' attribute name -> 'biomedicalConcepts' ... add an 's'

**Comment by dih-cdisc** [comment]
New DIH sketch for @EMuhlbradt @czwickl @ggasg  Note the blue comments down bottom left of diagram

![2023 01 31 DDF Model Plus BCs](https://user-images.githubusercontent.com/115090009/215792524-53f23e69-b47b-40d5-97f0-d5ebe3b1ad1a.png)

**Comment by EMuhlbradt** [comment]
Regarding BiomedicalConcept: bcConceptDefinition (AliasCode) and BiomedicalConceptProperty: bcPropertyDefinition (AliasCode): I'm worried that we are using the word 'definition' and 'name' interchangeably and I'm not sure we want to do that. Based on @dih-cdisc comment: 'holds the CT definition of what the BC is called'....so does it hold a name or definition? If a name, is it the standard or preferred name given by the BC source?

**Comment by dih-cdisc** [comment]
> 

The information we get from the CDISC API for a BC is this. 

For the BC itself

![Screenshot 2023-02-01 at 06 27 41](https://user-images.githubusercontent.com/115090009/215959289-785c2172-a2cc-4dd8-86e2-c68c1b60373e.png)

For a property

![Screenshot 2023-02-01 at 06 27 50](https://user-images.githubusercontent.com/115090009/215959317-df6f698a-100b-4ec7-9ae5-916a2485b3fd.png)

So, I assume, the C code "conceptId" is the definition

**Comment by dih-cdisc** [comment]
> @dih-cdisc @EMuhlbradt @czwickl Thank you very much for the feedback. Model has been updated to reflect the corrections. Also, at the risk of proposing something off the mark:
> 
> 1. BiomedicalConcept: bcConceptDefinition (AliasCode)
> 2. BiomedicalConceptProperty: bcPropertyDefinition (AliasCode)
> 
> Thoughts? See below for updated diagram. <img alt="Screen Shot 2023-01-31 at 14 11 29" width="753" src="https://user-images.githubusercontent.com/8659660/215859354-2fb784fa-39d4-4d91-b56f-a6ab60c39806.png">

@ggasg @czwickl @EMuhlbradt I am good with the attribute names suggested as long as Craig/Erin happy.

**Comment by dih-cdisc** [comment]
Image sent via email on Wednesday 1st Feb
![2023 02 01 DDF Model Plus BCs](https://user-images.githubusercontent.com/115090009/216520622-902b6912-4704-4fb1-83f7-3b7fd2e25d9f.png)

**Comment by dih-cdisc** [comment]
Updated version of sketch

![2023 02 03 DDF Model Sprint 7](https://user-images.githubusercontent.com/115090009/216530293-078d9091-0671-4f27-90ce-ff309654a9da.png)
