### ISSUE TITLE
M11 controlled terminology alignment [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#472]
- Review existing CT in USDM and update to make them aligned with M11 CT.
- Review M11 CT and discuss with team if CT list not included in model yet.

**Comment by czwickl** [comment]
Evaluation of M11 and DDF controlled terminology alignment (columns T-Z in the attached spreadsheet). Suggest that these are reviewed as a team to determine whether any changes to DDF terminology or suggestions for changing M11 terminology are warranted.

Columns A-R include notes and comments for the full evaluation of the M11 template (party review version) vs M11 CT Public Review file. This portion of the spreadsheet may not be of interest to the DDF development team.

  
[Terminology_ICH_M11_Protocol_cz working.xlsx](https://github.com/user-attachments/files/17292596/Terminology_ICH_M11_Protocol_cz.working.xlsx)

**Comment by BSnoeijerCD** [comment]
Moved to Done as this will be continued in ticket #510
