### ISSUE TITLE
Protocol Amendments [IG]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#476]
Need to ensure that M11 protocol amendments can be supported. Three aspects

1. Amendment support aligns with the updated M11 specification
2. Ensure we can support the detailed rationale for changes. Note we don't need exact details of change as an electronic comparison can be made (see #305)
3. Align with any review comments on Organizations arising from release 3.6. This overlaps because of the need to note enrollment at the time of an amendment being approved.

See feature ticket #469

**Comment by BSnoeijerCD** [comment]
Note for the IG update:
I removed some classes from the Study Version view to keep the structure comprehensive. 
We need to be aware of the corresponding implications - maybe we need a separate paragraph for abbreviations or other smaller links that were before in the study version view.

**Comment by dih-cdisc** [comment]
Add a new view?

**Comment by BSnoeijerCD** [comment]
- Updated https://wiki.cdisc.org/display/USDMIGv4/Study%2C+Protocols%2C+and+Amendments with new UML and updated text
- Updated https://wiki.cdisc.org/display/USDMIGv4/Study+Design with new UML and updated text
