### ISSUE TITLE
Protocol Amendments [Rules]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#477]
Need to ensure that M11 protocol amendments can be supported. Three aspects

1. Amendment support aligns with the updated M11 specification
2. Ensure we can support the detailed rationale for changes. Note we don't need exact details of change as an electronic comparison can be made (see #305)
3. Align with any review comments on Organizations arising from release 3.6. This overlaps because of the need to note enrollment at the time of an amendment being approved.

See feature ticket #469

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD Proposed rules:
- Each study enrollment must apply to a geographic scope, a study site, or a study cohort.
- There must be a one-to-one relationship between section number and section title for all sections changed for the same amendment.
- There is expected to be no more than one study amendment impact for each combination of type and substantialness. [Not 100% sure about this one - theoretically, you might have more than one impact of the same type/substantialness that you wanted to explain separately]

The following proposals are defined not according to the design of the model, but according to what is expected to be transferred in an API "payload" that relates to a single study version:
- A study version is expected to be documented by only one version of a study definition document of a particular type.
- Each study definition document version is expected to be referenced by a study version or a study design.
- Each study definition document is expected to have at least one version.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall 
I like to make the third rule more strict even. As we are note asking for a description but rather a rationale why the type of impact is substantial (or not). So then you would expect per amendment only one instance for each type.
As the rationale is only required in case substantial =Y we probably should make it optional in the API and require that it is filled when substantial=Y.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall 
Regarding the more general rules:
- A study version is expected to be documented by only one version of a study definition document of a particular type. _**agree**_
- Each study definition document version is expected to be referenced by a study version or a study design. _**I would make it and/or **_
- Each study definition document is expected to have at least one version. _** ok **_

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : I have added rules CHK0239-CHK0242. Please review text
- CHK0239 - ERROR - Each study enrollment must apply either to a geographic scope, a study site, or a study cohort.
- CHK0240 - ERROR - There must be a one-to-one relationship between referenced section number and title within a study amendment.
- CHK0241 - WARNING - A study version is expected to be documented by only one version of a study definition document.
- CHK0242 - WARNING - Each study definition document version is expected to be referenced by either a study version or a study design.

I did not include the rule for having at least 1 version for a studyDefinition document. If we want to stress that I think we should enforce this by referential integrity.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I've reviewed the rules and they look good.  There were only a couple of minor things:
1. I changed "apply either to" to "apply to either" in the first rule.
2. It seems strange that we have can have multiple `documentVersions` for `StudyVersion` but only one `documentVersion` for `StudyDesign`.  I think we made `documentVersions` plural for `StudyVersion` when we updated the model to allow more than one type of `StudyDefinitionDocument`.  Isn't it possible that we'd also want to say that a `StudyDesign` is associated with more than one `StudyDefinitionDocumentVersion` (e.g., if there are two types of document that both document the study design)?

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall 
regarding 2. There can be 2 or more documents representing the same study design. That will be reflected by multiple instances in the StudyDefinitionDocument class. However, for 1 study Version in the USDM we would only expect max 1 version of each study definition document (which is expressed in the rule).  So because we can refer to versions of multiple study definition documents, the relationship from studyVersion to documentVersion is plural.

**Comment by BSnoeijerCD** [comment]
Updated rule overview and pushed to GitHub
