### ISSUE TITLE
Amendment Document Content References

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#483]
Study Changes may refer to one or more sections of the (protocol) document. These references are not handled by the DocumentContentReference class. However, we need to reconsider whether a direct to narrativeContent or another method of referencing would be better.

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #496 |
| CT |  #497 |
| API | #498 |
| Rules | #500 |
| IG | #499 |
| Test Data | #501  |

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @ASL-rmarshall @EMuhlbradt @czwickl 
See below suggestion for change based on this issue:
![Changes_suggested](https://github.com/user-attachments/assets/1d08f2a4-7d99-4480-8326-e3f0b5635f8c)

**Comment by dih-cdisc** [comment]
Just thinking about pointing from the structured content to the document (StudyChange -> NarrativeContent). Currently we only point in to the structured content from the document.

Also pondering content shared across documents, so ...

![IMG_9626](https://github.com/user-attachments/assets/d7b6ff64-1a08-4c2a-94cf-bedb956188d9)

If we reversed the direction of the relationship, so from NarrativeContentItem to StudyChange (this content was changed as a result of this change to the study definition) [the Blue Arrow] an application could navigate (the Red paths] to the respective sections impacted in multiple documents.

Have a think.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @ASL-rmarshall 
Options are: 
1) from change perspective:
ChangedSections will point to the corresponding sections in the NarrativeContent class. The context of this narrativeContent class then indicates the document we are looking at. So that also covers changes in different sections of different protocols. 
2) from content perspective:
NarrativeContentItem will point to StudyChange indicating when and why changed including the rationale. This is also within the context of the corresponding document. 
3) Keep the DocumentContentReference class since it also documents changes to document sections that might not be included any more in the current version or section numbers are changed in the current version.  Although this is more from a text perspective we still can link via the specified section numbers/titles. However, we are now lacking the specific document id here to identify the document that is changed. For this we could add (optionally) a reference to the document that is changed.

**Comment by BSnoeijerCD** [comment]
Hi @ASL-rmarshall @dih-cdisc @czwickl @EMuhlbradt 
As promised: see instance diagram below with corresponding discussion points included as comments.
<img width="891" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkJQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87e9ce2d9ef1e199c07d0ccef9c7af1fa572c625/Changed%20Sections.png" alt="Changed Sections.png" />

**Comment by BSnoeijerCD** [comment]
![Changed Sections](https://github.com/user-attachments/assets/99e8c645-18fc-4071-99ea-376c37f33f6e)

**Comment by ASL-rmarshall** [comment]
Here's my attempt.  I've worked on the assumption that each `StudyChange` references the section that is the result of the change ("the referenced section looks like it does because of the change that has been applied"), which is part of the document version that documents the `StudyVersion` that contains the amendment.  The instance diagram shows three study versions (first version at the top, third at the bottom), with `StudyVersion` content on the left and corresponding documentation content on the right:
![Study Amendments](https://github.com/user-attachments/assets/ef56a557-0268-4f5d-b208-e631627a456a)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @ASL-rmarshall @czwickl @dih-cdisc 
As discussed during scrum today: we will only add 1 relationship from the DocumentContentReference class to the StudyDefinitionDocument class named: appliesTo
This will be a required 1 to 1 relationship.

**Comment by BSnoeijerCD** [comment]
Final UML view:
![StudyVersions](https://github.com/user-attachments/assets/e53e2db8-456b-4c0d-8ead-89367b66af51)

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @ASL-rmarshall @dih-cdisc: Relationship added in 3-8-0 release in github.
@czwickl
