### ISSUE TITLE
Estimands [Rules]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#490]
From an @BSnoeijerCD email (related to PHSE estimand paper)

Although we already cover the basics of the estimands we could consider how to further improve it in phase IV by for example:
- Making the analysis populations a sub of the study and/or cohort populations
- Allow reference to intercurrent event variables (either by syntax text templates or other references)  
- Allowing a link to a reference treatment (not in the paper or ICH E9R1 – but proposed by Diane as a logic -> a treatment of interest is often compared to a reference in the analysis)

**Comment by ASL-rmarshall** [comment]
> @ASL-rmarshall : I think we can specifiy rules for the intervention part based on the StudyIntervention.role e.g.
> 
> * At least 1 intervention referred which is an "Experimental Intervention"
> * The role of referred interventions should be either "Experimental Intervention", "Placebo" or "Active Comparator"
> 
> With regards to the "subset of" relationship I cannot think of any rules. Since intercurrent events are now based on syntax templates we can add this to any relevant syntax template rules.

@BSnoeijerCD I can't think of any rules for "subset of" or intercurrent events. However, I'm also not sure that it's even worth defining rules for the interventions:
- If you specify that one of the interventions must (or is expected to) be an "Experimental Intervention", this implies that the USDM model is only to be used with interventional study designs.
- I think it's possible that any of the other types of study intervention might be referenced by an estimand
