### ISSUE TITLE
Sites & Organizations [IG]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#492]
Observation from building test data

Original comment: 
May be better to make sites Organizations and allow Organizations to have "children" / "subsidiaries". That way Sites can have addresses and thus a geographic presence separate from the enrollment.

This ticket is now aiming at reviewing CT for organization type vs role type and to make it consistent and usable in relation to each other.
Using the types in relation to each other can then be explained in the IG.

See ticket #264 for CT.

**Comment by BSnoeijerCD** [comment]
From US Interchange: Add reference organization specifications for organizations like EMA, CT.gov etc to IG

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @ASL-rmarshall In order to explain the different organizations and corresponding entry requirements in the IG, I created the following instance diagrams. It depicts what is expected for specific study identifiers. 
Do you have any comments / thoughts. Should I add other registry / agency identifiers as well?
![Study Identifier](https://github.com/user-attachments/assets/349b5ee4-8aa5-4c3f-bcc6-73ea858c219d)

![NCT Number](https://github.com/user-attachments/assets/3da9fef5-706b-4277-a336-447229417f17)
![IND number](https://github.com/user-attachments/assets/3e0a6e63-4951-4e7b-bed5-0c30a1fdb785)
![EUDRACT number](https://github.com/user-attachments/assets/77035239-0ec4-4b09-8893-63921d268f96)

**Comment by dih-cdisc** [comment]
We may need to update the identifierScheme attribute values. The ones you have are the ones I used in the examples. I think we need something slightly more "formal"

- "US Federal Government" (for FDA, CT.gov and anything else in the US government)
- "European Union" for any EU institution (EMA, EUDRACT, CTIS ...)

**Comment by BSnoeijerCD** [comment]
Adjusted instance diagrams above and added to IG for Identifiers and Titles: https://wiki.cdisc.org/display/USDMIGv4/Study+Identifiers+and+Titles
Added also instances to Roles and Organizations to IG: https://wiki.cdisc.org/display/USDMIGv4/Study+Roles+and+Organizations
