### ISSUE TITLE
StudyDesign document versions [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#494]
A study design can now only refer to 0 or 1 document versions. If we have more document types, in alignment with study versions, it should be possible to refer to multiple different documents (versions).

This requires a small update to the Model which needs to be reflected in the corresponding UML view(s) presented in the IG.
Furthermore the name studyDesign.documentversion needs to become plural. 
And the corresponding changes need to be made to the API and test data.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl 
Two comments from my review:
I thought you wanted to remove clinical study sponsor as a organization type. As this is now covered by the role. It is still included in the CT file.
Is it ok to have contract research organization both as role as well as organization.type? I think it is bt might be confusing.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD we agreed to remove 'Research Organization' from the Organization Type codelist but did not discuss removing Clinical Study Sponsor. To me CRO can be both a role as well as an organization type so this may be one of those that stays in both places. @czwickl what do you think?

**Comment by BSnoeijerCD** [comment]
Reviewed and moved to Done
