### ISSUE TITLE
Multiple Study Types

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#5]
Should we allow for multiple study types (attribute studyType be a List of Codes rather than a single code) for the Study Class?

**Comment by cupkes** [comment]
This is an interesting idea.  There seems to be an argument for multiple study types, or the idea of supporting a study that could be considered to "fall into" the realm of more than one study type.

**Comment by drewcdisc** [comment]
@dih-cdisc (this info comes from the Planning meeting). Can you provide more details?  We need a firm decision yes/no (we need multiple study types). If yes, could you provide more info.

- What are study types? Can you give examples? 
- Does this mean trial type?
- What are the other kinds of studies?
- Are their sub-studies? Is this what is meant?
- Is this something about umbrella, basket, etc studies?
- Does additional study types require extra classes or is this just a categorization attribute?

If this still needs more discussion should we remove it from the Product Backlog?

**Comment by dih-cdisc** [comment]
Study Type is defined in the CT as C142175 Study Type Classification. It is "The nature of the investigation for which study information is being collected. (After clinicaltrials.gov)" and has a code list of values C99077:

- INTERVENTIONAL
- OBSERVATIONAL
- PATIENT REGISTRY

Should we allow for multiple values? My feeling is not, but want to check @EMuhlbradt @czwickl

**Comment by dih-cdisc** [comment]
Determined that we should probably stick with a single code. Moved to Icebox

**Comment by dih-cdisc** [comment]
This has now been handled by the work on #431 so will close
