### ISSUE TITLE
Amendment Document Content References [Rules]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#500]
Study Changes may refer to one or more sections of the (protocol) document. These references are not handled by the DocumentContentReference class. However, we need to reconsider whether a direct to narrativeContent or another method of referencing would be better.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall 
A rule for checking that the referenced document ID is indeed a reference to an actual document in the API call could be helpful. This aligns with other similar checks we are doing.
Any thoughts?

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I agree that the decision on how to do general id checking should be handled as part of #454:
- Either we should have one generic rule (and remove any specific rules)
- Or we should make a list of all the cross-reference (id-based) relationships and then make sure that we have a specific rule for each of them - I do think we are missing some of these.

If you agree, I think this means that we do not to define any specific rules for `DocumentContentReference` at this time, so this PBI can be closed.

**Comment by BSnoeijerCD** [comment]
Yes. I agree
