### ISSUE TITLE
StudyDesign Document Versions [Rules]

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#504]
A study design can now only refer to 0 or 1 document versions. If we have more document types, in alignment with study versions, it should be possible to refer to multiple different documents (versions).

This requires a small update to the Model which needs to be reflected in the corresponding UML view(s) presented in the IG.
Furthermore the name studyDesign.documentversion needs to become plural in CT.
And the corresponding changes need to be made to the API and test data.

Part of #484

**Comment by BSnoeijerCD** [comment]
Changed Chk0242 = attribute to only documentVersions

CHK0187: "A study definition document version must not be referenced more than once by the same study version." 
was essentially equal to the newly added rule:
CHK0241: "A study version is expected to be documented by only one version of a study definition document."

Therefore, I removed this text of this new CHK0241 and made it applicable to study design as follows:
A study definition document version must not be referenced more than once by the same study **design**.

@ASL-rmarshall can you please check and see if you agree?

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I agree with the updated wording for CHK0241- it makes sense for the wording of CHK0187 and CHK0241 to be consistent.  However, I wonder if we should consider a generic rule as an alternative - similar to CHK0009 - e.g., "The ids of all child instances referenced by the same parent class must be unique."
