### ISSUE TITLE
Change Code to AliasCode for Range unit

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/DDF-RA#505]
Unit coding for `Quantity` was changed to use `AliasCode` instead of `Code` for #324 but a corresponding change was not made for `Range.unit`. I think it would be better for unit coding to be consistent throughout the model.

**Comment by dih-cdisc** [comment]
@ASL-rmarshall @BSnoeijerCD I think this has been done, please check and close if so.

**Comment by BSnoeijerCD** [comment]
Yes, it is done. So will close.

**Comment by BSnoeijerCD** [comment]
This has been done. So ticket closed.
