### ISSUE TITLE
Sites & Organizations

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#506]
Observation from building test data

Original comment: 
May be better to make sites Organizations and allow Organizations to have "children" / "subsidiaries". That way Sites can have addresses and thus a geographic presence separate from the enrollment.

This ticket is now aiming at reviewing CT for organization type vs role type and to make it consistent and usable in relation to each other.
Using the types in relation to each other can then be explained in the IG.

Child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  NA |
| CT |  #264 |
| API | NA |
| Rules | #507 |
| IG | #492 |
| Test Data | #501 |

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @ASL-rmarshall @dih-cdisc 
I made a crosstable of role.codes vs organization types. See attached. In yellow the ones that are overlapping but that can be ok. I suggested 4 more organization types based on this.
[Role_vs_Type.xlsx](https://github.com/user-attachments/files/17292430/Role_vs_Type.xlsx)

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @ASL-rmarshall @czwickl @dih-cdisc See the attached list of additions to the organization type codelist. We also agreed to remove the existing/published term 'Research Organization' from the codelist.
[2024-10-11_DDF 506.xlsx](https://github.com/user-attachments/files/17342915/2024-10-11_DDF.506.xlsx)
