### ISSUE TITLE
Sites & Organizations [Rules]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#507]
Observation from building test data

Original comment: 
May be better to make sites Organizations and allow Organizations to have "children" / "subsidiaries". That way Sites can have addresses and thus a geographic presence separate from the enrollment.

This ticket is now aiming at reviewing CT for organization type vs role type and to make it consistent and usable in relation to each other.
Using the types in relation to each other can then be explained in the IG.

See ticket #264 for CT.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall 
To consider: rules that align options between organization.type and studyRole.code?

I believe they should all be warnings. So expected:
- A study role of 'Sponsor', 'Co-Sponsor', or 'Local Sponsor' is expected to refer to an Pharmaceutical company, Medical Device Company or Academic institution
- A manufacturer role is expected to refer to a Pharmaceutical company or Medical Device Company 

Of course we can think of more. However, maybe this is all too much and the users can apply there own logic in this regard. Any thoughts

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall 
Apart from the above, we need to work on the study identifier organization restrictions as the sponsor identification is now in the role class. What about these?
- There must be exactly one organization linked to a sponsor study role
- There must be exactly one identifier linked to an organization which has the sponsor study role.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : 
While working on the IG, I believe we should look at the applies to for sponsor study role as well. This should be at the overall study version level otherwise the logic for the corresponding identifier is lost.

**Comment by BSnoeijerCD** [comment]
> @ASL-rmarshall To consider: rules that align options between organization.type and studyRole.code?
> 
> I believe they should all be warnings. So expected:
> 
> * A study role of 'Sponsor', 'Co-Sponsor', or 'Local Sponsor' is expected to refer to an Pharmaceutical company, Medical Device Company or Academic institution
> * A manufacturer role is expected to refer to a Pharmaceutical company or Medical Device Company
> 
> Of course we can think of more. However, maybe this is all too much and the users can apply there own logic in this regard. Any thoughts

Discussed and decided to not do these checks as how an organization identifies itself is up to the organization.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : could you please review the below:
Based on the discussions today and further insights I made the following updates:
- Chk0205: Set to N for version 4 as it still includes Researchorganization class and organizationType attributes.
- Added Chk0244 instead for V4: "An organization type must be specified according to the extensible organization type (C188724) DDF codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
- Added Chk0245: "There must be exactly one study role which identifies as the sponsor. "
- Added Chk0245: "The sponsor study role must point to exactly one organization."
- Added Chk0247: "The sponsor study role must be applicable to a study version."
- updated Chk0193: "There must be exactly one study identifier referring to an organization that is referred to from the sponsor study role."

Note that I split up the above mentioned first rule to be more clear and univocal. Also that will be more easy to implement from a core perspective.

**Comment by ASL-rmarshall** [comment]
> @ASL-rmarshall : could you please review the below: Based on the discussions today and further insights I made the following updates:
> 
> * Chk0205: Set to N for version 4 as it still includes Researchorganization class and organizationType attributes.

Agree
> * Added Chk0244 instead for V4: "An organization type must be specified according to the extensible organization type (C188724) DDF codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."

Agree - this is the same text as CHK0205, but the Entity/Attribute will just be `Organization`/`type`
> * Added Chk0245: "There must be exactly one study role which identifies as the sponsor. "

Is this better: "There must be exactly one study role with a code of 'Sponsor'."
> * Added Chk0245: "The sponsor study role must point to exactly one organization."

Agree (though this should be CHK0246)
> * Added Chk0247: "The sponsor study role must be applicable to a study version."

Agree
> * updated Chk0193: "There must be exactly one study identifier referring to an organization that is referred to from the sponsor study role."

Is this better: "There must be exactly one sponsor study identifier (i.e., a study identifier whose scope is an organization that is identified as the organization for the sponsor study role)."
> 
> Note that I split up the above mentioned first rule to be more clear and univocal. Also that will be more easy to implement from a core perspective.

I agree with these changes, with the tweaks/suggestions included above.
