### ISSUE TITLE
M11/USDM Codelist Terms Alignment Evaluation [CT]

### ISSUE THREAD

**Issue by czwickl** [cdisc-org/DDF-RA#510]
Evaluation of the alignment between M11 and DDF codelist terms that apply to the same data element concept.

**Comment by BSnoeijerCD** [comment]
@czwickl I have reviewed your original Excel while travelling today and added mapping and points to consider from a model perspective. I think I have added a few more mappings than you had and I hope it helps.

[Terminology_ICH_M11_Protocol_cz.working_bs.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGRnQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c2fb3562741f198ea864e63928870bf523710a1/Terminology_ICH_M11_Protocol_cz.working_bs.xlsx)

fyi @EMuhlbradt @dih-cdisc

**Comment by czwickl** [comment]
Thank-you Berber. Hope you are enjoying the Interchange.

**Comment by czwickl** [comment]
@BSnoeijerCD @EMuhlbradt @daveih I completed reviewing codelist alignment and include the spreadsheet below. The individual tabs containing the M11 codelists and values also show a comparison to any corresponding DDF codelist in greater detail (where they align and where they don't) so be sure to look at those tabs as well.

[Terminology_ICH_M11_Protocol_cz.working_bs_cz.xlsx](https://github.com/user-attachments/files/17555935/Terminology_ICH_M11_Protocol_cz.working_bs_cz.xlsx)

**Comment by BSnoeijerCD** [comment]
Updated Excel during Scrum @czwickl @EMuhlbradt 
[Terminology_ICH_M11_Protocol_cz.working_bs_cz_scrum31Oct.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemFKQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c74fe7104ea5ad44fc13f180380b835a6986a07/Terminology_ICH_M11_Protocol_cz.working_bs_cz_scrum31Oct.xlsx)

**Comment by BSnoeijerCD** [comment]
See ticket #513 for follow/up actions regarding amendment reason.
