### ISSUE TITLE
Devices [Rules]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#520]
See feature ticket #442

Devices are a separate part of IDMP and will be handled after the interventions part.
See #316 for including Interventions in the USDM model according to IDMP.

We can include #508 (Product designation) and #259 (Other intervention names) with changes based on this ticket.

**Comment by ASL-rmarshall** [comment]
First ideas:
- An administration must reference either an administrable product or a medical device (or both).
- An administrable product must not be referenced as both the administrable product for an administration and the embedded product of a medical device that is referenced by the same administration.

**Comment by BSnoeijerCD** [comment]
Thank you @ASL-rmarshall . See my ideas and comments below
- An administration must reference either an administrable product or a medical device (or both).
   -> I would not do that as we also can in theory have an administration of a non-device/administrable product like a questionnaire or psychologic intervention. 
- An administrable product must not be referenced as both the administrable product for an administration and the embedded product of a medical device that is referenced by the same administration.
    -> agreed 
An administration is expected to have a dose only when it also has an administrable product. (Also equivalent rules for route and frequency?)
   -> yes but then the administrable product can also be embedded in the device. So maybe we need to specify that in the rule

Additional:
- Coding rules for all the new CT
    - MedicalDeviceIdentifier.type
    - AdministrableProduct.sourcing
    - MedicalDevice.sourcing
    - move the productDesignation rule to new class

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall 
See for the 3rd rule above also CHK0220: "If a dose is specified then a corresponding administrable product must also be specified and vice versa."
We can update that one with adding -> either directly or embedded in the medical device 

The dose and route/frequency dependencies are handled in CHK0201 and CHK0202.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall I have made the following updates:
- Set CHK0150 to N for v4 as producDesignation is moved and added CHK0254 for v4.0 instead.
- Updated CHK0220 to "If a dose is specified, then a corresponding administrable product must also be specified either directly or embedded in the medical device and vice versa."
- Added CHK0249: "An administrable product must not be referenced as both the administrable product for an administration and the embedded product of a medical device that is referenced by the same administration."
- Added CHK0250: "In case a medical device includes an embedded product then the sourcing information must be defined at the medical device level not at the embedded product level."
- Added CHK0251: "A medical device identifier type must be specified according to the extensible medical device identifier type (Cxxx) DDF codelist (e.g. an entry with a code or decode used from the codelist should be consistent with the full entry in the codelist)."
- Added CHK0252: "An administrable product sourcing must be specified using the sourcing (Cxxx) DDF codelist."
- Added CHK0253: "A medical device sourcing must be specified using the sourcing (Cxxx) DDF codelist."

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall: Based on the newly added class, I added another rule:
CHK0255: A product organization role is expected to either apply to at least a medical device or an administrable product.

**Comment by ASL-rmarshall** [comment]
> @ASL-rmarshall: Based on the newly added class, I added another rule: CHK0255: A product organization role is expected to either apply to at least a medical device or an administrable product.

I think this should be:
> A product organization role must only apply to medical devices or administrable products.

I've set up the API to make `appliesToIds` required, so some sort of id value should be provided.  The rule just needs to verify that each id value is valid for either a medical device or an administrable product.  I think it would be an error (not a warning) if id values do not reference the right class.
