### ISSUE TITLE
Fix CT issues

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/DDF-RA#522]
The following fixes need to be made in the CT spreadsheet:
- Change Role from "Relationship" to "Attribute" for:
    - AssignedPerson.name
    - AssignedPerson.description
    - AssignedPerson.label
    - AssignedPerson.jobTitle
- Change Role from "Attribute" to "Complex Datatype Relationship" for:
    - CommentAnnotation.codes
    - StudySite.country

**Comment by dih-cdisc** [comment]
@BSnoeijerCD @EMuhlbradt @czwickl This should be a quick fix for this sprint

**Comment by EMuhlbradt** [comment]
@ASL-rmarshall @dih-cdisc @BSnoeijerCD : Fixes put into 3-9-0 release on Github.
@czwickl this ticket can be moved to QA column.
