### ISSUE TITLE
Errors in CT Spreadsheet

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#65]
During use of the CT spreadsheet noticed that:
 
1. #Row 154 onwards in the Role column you start using “Class” instead or “Entity”. 
2. Address entity Logical Data Model name is AliasCode, should be Address. 

![Screenshot](https://images.zenhubusercontent.com/633d8ab6ddc209bec9f522e1/de91735c-84a2-4457-a40f-52d59e5ad63d)

**Comment by glow-mdsol** [comment]
Also #73
