### ISSUE TITLE
CT: Class ScheduledDecisionInstance, Attribute conditonAssignments

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#67]
In the CT Spreadsheet, ScheduledDecisionInstance class, conditonAssignments attribute missing. The attribute is a map of conditions to detinations

**Comment by EMuhlbradt** [comment]
@dih-cdisc Craig accidentally 'closed' this ticket and doesn't have permission to change it back to review. Can you please re-open this ticket?
