### ISSUE TITLE
CT. Class Timing, Attribute timingReleativeToFrom

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#68]
In the CT Spreadsheet, class Timing, attribute timingReleativeToFrom, should have a code list

[See JIRA-426](https://jira.cdisc.org/browse/DDF-426) as well

**Comment by EMuhlbradt** [comment]
@czwickl and @EMuhlbradt agree to create codelist of valid values and update the attribute name slightly to better align the meaning of the attribute with the valid values developed.
