### ISSUE TITLE
Activities, Procedures and Study Data - Optional

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#7]
The following capability should be added to the model

1. Procedures & Data Capture Can be optional, Ordered
2. Optional Activities Should activities have the capability to be optional?

**Comment by drewcdisc** [comment]
Work to be done:

- [ ] Develop the design for data capture (@cupkes, Gaston, @jared-schreibman-cdisc).
- [ ] Build USDM
- [ ] Build API
- [ ] Develop associated CT

**Comment by cupkes** [comment]
So. For now, we just leave eCRF link on StudyData.  Otherwise we have to figure out the query field configuration, endpoints, etc...  We are going to add Boolean classnameIsOptional fields to procedures and encounters to provide a way to mark them as optional.

**Comment by cupkes** [comment]
Activities already contains lists of procedures and study data.  Ordering is inferred, right?  The procedure in the list at index 0 is the first.  So, I don't know if anything else needs to be done to support ordering of procedures and study data.

**Comment by cupkes** [comment]
@daveih do we want to discuss replacing the eCRF links with fields that represent form field data, (queries, field names or whatever)?

**Comment by dih-cdisc** [comment]
The Optional Requirement: 

1.  The boolean is good for now. 
2.  For the future we might want to consider adding some means of recording "why" it is optional, are their circumstances when it is optional etc?

**Comment by dih-cdisc** [comment]
The Ordering Requirement

1.  Yes ordering can be implied from the array ordering. However, in other places we have "prev" and "next" attributes. So from consistency perspective, what is the best model approach. We could also use an ordinal but that can get messy from implementation perspective when inserting etc.

**Comment by dih-cdisc** [comment]
Comment re Data Collection

1. Nothing needs to change. This will all be considered as pat of the EDC / BC changes that are coming
