### ISSUE TITLE
In the USDM_CT please don't use strikethrough in the official tabs

### ISSUE THREAD

**Issue by glow-mdsol** [cdisc-org/DDF-RA#72]
The USDM_CT file uses cells with struck through text.  This is difficult to process programmatically, changes like this should be tracked in a different way (maybe a changelog tab or similar), the Entities & Attributes and Value set tabs should represent the current state

**Comment by jowencdisc** [comment]
For Internal Review onwards these strike throughs will be removed. The USDM_CT_Changes.xls file will document the changes made.
