### ISSUE TITLE
USDM_CT: Encounter.encounterContactMode needs updating in valid value sets

### ISSUE THREAD

**Issue by glow-mdsol** [cdisc-org/DDF-RA#73]
"DDF valid value sets" sheet has a Encounter.encounterContactMode attribute
"DDF Entities&Attributes" references Encounter.encounterContactModes (this matches the EAP)

The "DDF valid value sets" reference needs updating

**Comment by jowencdisc** [comment]
@glow-mdsol - since we are now in internal review we are tracking comments using the JIRA system.
I have therefore transferred this comment to https://jira.cdisc.org/browse/DDF-397

**Comment by glow-mdsol** [comment]
Thanks!

**Comment by glow-mdsol** [comment]
Thanks!
