### ISSUE TITLE
Data Dictionary "Upgrade"

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#75]
Add new columns to the data dictionary within the IG. New columns are 

1. Cardinality
2. Preferred Term
3. NCI Code of the definition

If possible, split the codelist Ref into two columns, one for CDISC terms (Cnnnnn) called "CDISC Codelist" and one for external CT (all other non Cnnnnn references) called "External CT"

Rename existing columns

1. Property Name -> Attribute Name
2. Description -> Definition

See [JIRA 401](https://jira.cdisc.org/browse/DDF-401)

**Comment by jowencdisc** [comment]
[usdm_main 2.xlsx](https://github.com/cdisc-org/DDF-RA/files/11028156/usdm_main.2.xlsx)

**Comment by jowencdisc** [comment]
Sorry made a mistake adding the comment and accidentally closed the ticker. Reopened it now.

**Comment by ggasg** [comment]
So, I've updated the Data Dictionary Table with the new names and columns "Preferred Term" and "NCI Code...". 
The Cardinality remains a challenge. A comparison of the sample spreadsheet from Geoff and the "multiplicity" data available in the UML XML makes me think their definitions of "Cardinality" are not the same. The XML states multiplicity for a property **only in the context of a connection** between two classes. Say, for example, in the connection between _Activity_ and _Procedure_ there is a 0..* multiplicity with the property _definedProcedures_. Looks like our current tabular format in this wiki page does not allow for properly displaying this exact information per the UML XML, but I could be very mistaken so I'd like to check in tomorrow with @cupkes and clarify. Feel free to share comments and thoughts @jowencdisc @dih-cdisc

**Comment by ggasg** [comment]
@cupkes @jowencdisc @dih-cdisc Cardinality has been added to the Data Dictionary wiki page. I'm anticipating Chris and I will revisit this topic as the default constructors are updated in the near term. Thus the reason behind all cardinalities showing "0..*"

**Comment by dih-cdisc** [comment]
@ggasg @cupkes Small "format" issues.

1. Type "String" -> "string" in column, keep upper case first char for class names. Also consistent with  "boolean", so all primitive datatypes to all lower case?
2. Column heading "Type" -> "Data Type"
3. Code list column, refs such as "[(C66735)]" -> "C66735"

**Comment by ggasg** [comment]
@dih-cdisc Ok, a new update has been made to the Data Dictionary wiki page. It has the three format changes, though I'd ask to reconsider stating a "**string**" type as a primitive, given that the majority of languages implement it as an Object. On the other hand, and in this context, it may help calling out visually those types that are specific to the CDISC realm to those that are not.
About the cardinality for the "ids" fields. We can assume they will always take the same cardinality (i.e. placing a single cardinality type to all fields that end in "ids"). Or, we can create a reference file as suggested and use it to look up and populate the cardinality. The downside of this is that there will be another file to maintain. @cupkes What do you think?

**Comment by dih-cdisc** [comment]
@ggasg @cupkes 

Yes, agree, most languages use classes for simple data types, it is more of a visual thing and the "String" v "boolean" stuck out for me.

As for the Ids, fields we have three types, we have the actual instance Id <class name>Id attributes where we do not need a cardinality though it might be nice to state "instance identifier", the we have <target class based name>Id  1:0..1 and <target class based name>Ids 1:0..*. A file solves it but, as you say, maintenance. But for phase 2 it might be the easiest.

**Comment by ggasg** [comment]
Ok @dih-cdisc @cupkes I've adapted the Wiki generation tool to include cardinalities stated in this json file, along with the cardinalities stated in the UML xmi. But before I post an update to the wiki page, please review the file contents and make corrections as needed.
[cardinalities.txt](https://github.com/cdisc-org/DDF-RA/files/11093124/cardinalities.txt)

**Comment by glow-mdsol** [comment]
yeah, the sheet I sent in had a bug.  Cardinality was incorrect based on a misinterpretation of the tables.  Here's the updated version.
[usdm_main.xlsx](https://github.com/cdisc-org/DDF-RA/files/11099086/usdm_main.xlsx)

**Comment by jowencdisc** [comment]
@ggasg here are the changes to the data dictionary that we discussed at the meeting.
1) In the cardinality column, 1:0..1 should be amended to 0:1 and 1:1 should be amended to 1..1
2) For data type List<string>, default in 0..* into the cardinality column

**Comment by ggasg** [comment]
@dih-cdisc @cupkes Data Dictionary changes around cardinalities have been made in the wiki and are ready for review.
