### ISSUE TITLE
DDF valid value sets for Encounter.encounterContactModes

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#76]
See [JIRA 397](https://jira.cdisc.org/browse/DDF-397). 

Check if this is a List of Codes or a single Code (I think it is a List of codes). If list should be plural, if single code then singular name. Make sure UML / CT / API align.

**Comment by EMuhlbradt** [comment]
@dih-cdisc , this is a list of codes so should be plural. We agree that the attribute name in column B of the DDF Valid Value Sets tab should be updated to 'encounterContactModes'. This is related to backlog item number 73.
