### ISSUE TITLE
CodeList for Class Type (subclasses)

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#77]
**Original Query**
CT Spreadsheet, ScheduledInstance, ScheduledInstanceType, marked as code list, we may want to think about this in next sprint / review

**Note from Erin**
EM-Valid value list contains 'ACTIVITY' and 'DECISION'. Two values added as per modelers request. Are they rethinking this?

**Comment by dih-cdisc** [comment]
Action:
Remove codelist rows 'Scheduled Instance Type Response' (rows 133, 134 of the Valid Value Sets tab).

2023-03-21: DIH says ignore these as they are more technical/systems focused in nature such that they don't need to be incorporated into the CT spreadsheet at all.

**Comment by dih-cdisc** [comment]
**Action:**
Remove codelist rows 'Scheduled Instance Type Response' (rows 133, 134 of the Valid Value Sets tab).

**Comment by EMuhlbradt** [comment]
@EMuhlbradt @czwickl agree to remove codelist from valid value set tab and update codelist reference to 'N' in the Entities&Attributes tab of the sprint 11 deliverable.
