### ISSUE TITLE
Procedure Class

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#79]
See [JIRA 405](https://jira.cdisc.org/browse/DDF-405)

1. procedureType should probably be better named "procedureName" and add in a "procedureDescription" given that there is a procedureCode attribute.
2. Add further detail to the IG

**Comment by EMuhlbradt** [comment]
@czwickl and @EMuhlbradt agree that procedureName and procedureDescription are good to add to the model. We will create the semantics for that. However, thoughts on keeping procedureType in the model in case people are categorizing/classifying procedures?

**Comment by dih-cdisc** [comment]
Add name and description and leave type in place

**Comment by jowencdisc** [comment]
@cupkes @ggasg  and @jared-schreibman-cdisc 
The model and the API need updating with this change

**Comment by jowencdisc** [comment]
Added @daveih as an assignee as there was a reference to add info to the IG

**Comment by jared-schreibman-cdisc** [comment]
@daveih The API has been updated with these changes in branch `api-sprint-11`
