### ISSUE TITLE
CT Definitions

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#84]
bcCategoryParentIds, bcCategoryChildIds and bcCategoryMemberIds definition missing from CT?

These are relationships, do we include definitions for these?

See [JIRA-411](https://jira.cdisc.org/browse/DDF-411)

**Comment by EMuhlbradt** [comment]
@dih-cdisc we have 'modeled' these as relationships in the CT deliverable so have chosen to not define those items in the CT. 
On a slightly related note, I notice that 'bcCategoryChildIds' was typed above while we have 'bcCategoryChildrenIds' in the CT deliverable. Just to confirm is it meant to be 'Child' or 'Children'? Is that an error in the CT deliverable we need to address?

**Comment by dih-cdisc** [comment]
bcCategoryChildrenIds in the UML so stick with that.

**Comment by EMuhlbradt** [comment]
@dih-cdisc: Parent and Member are singular so potentially 'Child' could/should be singular too. I can make the change now or wait until PR. Your call. That would require updates to the model and in other places potentially so we may want to discuss this tomorrow morning.

**Comment by dih-cdisc** [comment]
@EMuhlbradt [DDF-RA 85](https://github.com/cdisc-org/DDF-RA/issues/85) created to handle the rename of bcCategoryChildrenIds  -> bcCategoryChildIds. Do this as part of public review comment resolution so we can close this one now.
