### ISSUE TITLE
Trial Intent Type

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#89]
StudyDesign class, trialIntentType atribute

1. UML has trialIntentType as ```List<code>```
2. CT has trialIntentType
3. API has trialIntentTypes as ```List<code>```

So questions are:

1. Single or multiple values
2. If single then name should be trialIntentType with a single Code
3. If multiple name should be trialIntentTypes with a List of Code

See [JIRA-428](https://jira.cdisc.org/browse/DDF-428)

**Comment by dih-cdisc** [comment]
This was a List at end of phase 1 so I see little reason to change it from multiple. So I suggest name change in UML and CT (add the 's' to end of attribute name)

**Comment by ggasg** [comment]
@dih-cdisc @cupkes All artifacts updated. Moving to under review.
