### ISSUE TITLE
Study Definitions Repository Definition

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#91]
From [JIRA DDF-427](https://jira.cdisc.org/browse/DDF-427)

We lack a clear CDISC governed glossary definition for a 'Study Definition Repository (SDR)' as well as how we define 'Study Definition'.
 
On DDF GitHub we have:
"The Study Definitions Repository is a novel central component aimed at facilitating the exchange of structured study definitions across clinical systems using both technical and data standards."
 
In previous DDF material we had:
Repository that holds the specific study instances. Each study definition includes both the study structure (design) plus the applied standards (metadata that were selected in the study builder.
This will be versioned, and cover the process from study definition from planning, setup, execution, analysis, reporting to submission.
The Study Definition will reference the Industry Standards as well as the Sponsor Standards.
Some instances will be managed and defined via the connected Study Builders; other instances will be sourced in from other Study Definition Data Sources.

**Comment by czwickl** [comment]
@EMuhlbradt @cupkes @dih-cdisc @jared-schreibman-cdisc @jowencdisc @drewcdisc 

Erin and I are meeting Friday morning (19-May) to work out definitions for "Study Definition" and "Study Definition Repository". Erin found a couple of sources (CDISC DDF Project and Trancelerate), however it's still not clear what these really are and how they are intended to be used and appear to even contradict one another. One source implies these relate to the complete definition of a specific instance of a study (e.g., identifies all of the components, standards, design elements, and technical/metadata) whereas the other suggests that each study definition is a reusable snippit that can be used with other study definitions to completely describe a study. The first case suggest a 1:1 relationship between a Study and a Study Definition and the second case suggests a 1:many relationship.

It would be very helpful if each of you could provide a comment in this ticket with your own idea of what we mean by the term "Study Definition". Is this even the most accurate term? Your input will help us to synthesize thoughts into an accurate and somewhat precise glossary-type definition for this term. The "Study Definition Repository" is straightforward in that it will be a digitally stored collection of individual Study Definitions.

Thanks for your thoughts on this.

**Comment by dih-cdisc** [comment]
You are going to love this one :)

Study Definition: An imprecise label used to denote a set of metadata (defined with a version of the USDM) that defines some or all of a clinical [trial/study] design. This collection of metadata may well expand over time to encompass an entire clinical [trial/study] protocol.

**Comment by EMuhlbradt** [comment]
Study Definitions Repository: A digital management and storage system for study definitions.

Accompanying Waffle: 
NOTE: The study definitions repository: 
...allows retrieval of study definitions for the creation of a study instance.
...facilitates the exchange of structured study definitions across clinical systems using both technical and data standards.
...will be versioned, and cover the process of study planning, setup, execution, analysis, reporting to submission.
