### ISSUE TITLE
Error in Definition

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#92]
From [JIRA DDF-437](https://jira.cdisc.org/browse/DDF-437)

Change "A characterization or classification of the study endpoint that determines its category of importance relative to other study objectives." to "A characterization or classification of the study objective that determines its category of importance relative to other study objectives."

**Comment by EMuhlbradt** [comment]
Good catch by Mikkel. We agree to make the update to the definition as proposed by commenter.
