### ISSUE TITLE
Main Timeline

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#93]
See [JIRA DDF-432](https://jira.cdisc.org/browse/DDF-432) & [DDF-445](https://jira.cdisc.org/browse/DDF-445)

From JIRA DDF-432

"When reviewing the SDR implementation, we realized that there is no indication of what timeline is the main timeline except for a textual description. A timelineLevel or TimelineOrder could help in identifying which one is the main referring to the sub timelines. "

We have a collection of timelines currently. Best way to add an indicator for the main timeline?

Also from JIRA DDF-445

"In a study if there is no main SOA (generic SOA table) but Armwise SOA tables. In this case, there is technically no main timeline. Can in such cases, only 'otherTimelines' field in 'studyDesign' tab be populated and 'maintimeline' field be left blank OR
should the main IMP arm SOA table be considered as 'maintimeline' and other SOA tables as 'otherTimelines'?"

**Comment by cupkes** [comment]
If we have a collection, we can always reference them ordinally.  However, I'm not sure we can semantically "enforce" the order that way.  Maybe a map?  We should discuss.

**Comment by dih-cdisc** [comment]
Sketch

![2023 05 26 DDF Model](https://github.com/cdisc-org/DDF-RA/assets/115090009/9bf6def7-04a6-4543-891a-78cf98103271)
