### ISSUE TITLE
Decision & Activity

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#94]
See [JIRA DDF-434](https://jira.cdisc.org/browse/DDF-434)

"In the current SDR RI API implementation, the POST/PUT endpoints will ignore the additional elements that don't match the model. Couple of examples mentioned below.

activityIds in the request will be ignored if the scheduledInstanceType is "DECISION"
conditionAssignments in the request will be ignored if the scheduledInstanceType is "ACTIVITY"
SDR will not throw any validation errors in above scenarios, instead the API will ignore the additional elements like activityIds/conditionAssignment as they are not mandatory in the corresponding sub-class model.

This ticket is added for CIDSC to explore the possibility of tweaking the model/API Specs to add proper validation rules on SDR side."

Can we update the model to impose these constraints in the class / sub class definition?

**Comment by cupkes** [comment]
I need to think this through, however, I'm not sure that validation is typical for the model layer, as it should be unaware of things at the control layer.  I'm going to talk this through with my new dev.

**Comment by dih-cdisc** [comment]
Discussed on sprint call of 15th May.

**Comment by dih-cdisc** [comment]
Sketch

![2023 05 26 DDF Model](https://github.com/cdisc-org/DDF-RA/assets/115090009/9bf6def7-04a6-4543-891a-78cf98103271)

**Comment by dih-cdisc** [comment]
Include in this change the update in the API of the enums from 1 & 2 to literals "ACTIVITY" and "DECISION"

**Comment by dih-cdisc** [comment]
@cupkes Checking, name of attribute. Should we name "scheduledActivityInstanceEncounterId" so as to match the naming convention?

**Comment by cupkes** [comment]
Yes.  Fixed.
    On Thursday, June 1, 2023 at 06:48:53 AM MDT, Dave IH ***@***.***> wrote:  
 
 


@cupkes Checking, name of attribute. Should we name "scheduledActivityInstanceEncounterId" so as to match the naming convention?
