### ISSUE TITLE
Country level amendments

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#95]
From [JIRA DDF-439](https://jira.cdisc.org/browse/DDF-439)

Do we have provision in USDM 2.0 to handle study design amendments at Global/Country level? If yes, how this will be managed. Are we going to add new study design with changes at study level?

**Comment by dih-cdisc** [comment]
Link with #118 M11 will guide us on this topic.

**Comment by BSnoeijerCD** [comment]
This relates to the cohort discussions as well since different countries might have differences in some assessments and activities.
We will discuss this at the SME meeting of coming Tuesday.

**Comment by dih-cdisc** [comment]
This will be covered in #118. Any further changes we need for cohorts can be handled within a separate change in another sprint
