### ISSUE TITLE
Objectives & Endpoints Update

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#98]
[JIRA DDF-461](https://jira.cdisc.org/browse/DDF-461)

Should endpoints have a relationship to BiomedicalConcept so that automation from Objective and Endpoint selection to choose proper BiomedicalConcepts could be possible?

Child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model | #152 |
| CT | #151 |
| API | #152 |
| IG | # |
| Examples | # |

**Comment by dih-cdisc** [comment]
Upgrade objectives and Endpoints to use the SyntaxTemplate generic capability

**Comment by BSnoeijerCD** [comment]
See attached Excel for alignment with M11 and other standards. No attributes to be added in that regard.[Objective_Endpoints_Standards.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTFRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bb9c108bb3b3d98de1b2236b4c2184f91107e35c/Objective_Endpoints_Standards.xlsx)

**Comment by EMuhlbradt** [comment]
For the remark above 'Consider to remove class name from level attributes', Erin/Craig agree that the attribute endpointLevel should be changed to 'level', and 'objectiveLevel' should be changed to 'level' in the CT and model.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD , for item 1 above we agree that it makes sense to update the attributes 'objectiveLevel' and 'endpointlevel' to simply 'level' for both Endpoint and Objective Classes.
For item 2, please see excel file. We are unsure exactly what was meant so this was our best guess.
[backlog item 98 draft.xlsx](https://github.com/cdisc-org/DDF-RA/files/12575697/backlog.item.98.draft.xlsx)

**Comment by dih-cdisc** [comment]
Design Sketch

![DDF USDM Model Informative](https://github.com/cdisc-org/DDF-RA/assets/115090009/800372f9-ca9e-4eb5-89e4-aa62e03c7e2a)
