### ISSUE TITLE
ISO 8601 Dates, times and durations

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#99]
See JIRA 

[DDF-456](https://jira.cdisc.org/browse/DDF-456)
[DDF-431](https://jira.cdisc.org/browse/DDF-431)

Dates and times should be ISO 8601 compliant.

Durations should be ISO 8601 complian. Examples appear to be free text eg:

[scheduledInstanceTimings][0]['timingValue']

**Comment by cupkes** [comment]
ok. So we use a date type and an interval type instead of strings?  We can't represent this solution in the UML as property, so I can't just build conformance rules in the setter method.  I would assume that most basic language libraries support these ISO time specs.

**Comment by dih-cdisc** [comment]
I was thinking two fields? One human readable (as we have), one machine-readable/processable coded. Now, they can get out of line but I see circumstances like a 2 day value. 8601 could encode as 2 day or 48 hr duration. Text might want to be "2 days" or "48 hours", the duration and the desired text migth not always align on units. Thoughts?

**Comment by dih-cdisc** [comment]
PS ISO 8601 used by other CDISC standards, especially SDTM

**Comment by cupkes** [comment]
ok.  So, what type should we use for timingValue?  A code?  or a language specific Date object?  I'm down with the value and text combos, I just need to know if this ISO data is a code object from an ISO origin or a ISO approved date object.

**Comment by dih-cdisc** [comment]
@cupkes We should probably encode the window as well. We would probably need a description field, a lower bound and an upper bound, with the bounds being the encoded fields???

**Comment by dih-cdisc** [comment]
Latest Sketch

![2023 05 25 DDF Model III](https://github.com/cdisc-org/DDF-RA/assets/115090009/43950bbf-8864-4987-a0e3-d7ccc226a277)

**Comment by dih-cdisc** [comment]
Also may need to tweak the sequence number field and replace with a "default" id so that we can link every ScheduleInstance to the next in the sequence with a  pointer rather than. For ActivityInstances it is the only link. For Decisions it is the default (the one used if no other condition met)
